# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev/CC.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(531, 431)
        Dialog.setMinimumSize(QtCore.QSize(531, 431))
        Dialog.setMaximumSize(QtCore.QSize(531, 431))
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 30, 511, 80))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 58))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.cmdString = QtWidgets.QLineEdit(self.groupBox_2)
        self.cmdString.setMinimumSize(QtCore.QSize(0, 0))
        self.cmdString.setObjectName("cmdString")
        self.gridLayout.addWidget(self.cmdString, 0, 0, 1, 1)
        self.createKPPsettings = QtWidgets.QPushButton(Dialog)
        self.createKPPsettings.setGeometry(QtCore.QRect(80, 130, 160, 27))
        self.createKPPsettings.setObjectName("createKPPsettings")
        self.ccClose = QtWidgets.QPushButton(Dialog)
        self.ccClose.setGeometry(QtCore.QRect(340, 130, 79, 27))
        self.ccClose.setObjectName("ccClose")
        self.ccMonitor = QtWidgets.QPlainTextEdit(Dialog)
        self.ccMonitor.setGeometry(QtCore.QRect(10, 170, 511, 251))
        self.ccMonitor.setObjectName("ccMonitor")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create KPP settings"))
        self.groupBox_2.setTitle(_translate("Dialog", "Command string"))
        self.createKPPsettings.setText(_translate("Dialog", "Create KPP settings"))
        self.ccClose.setText(_translate("Dialog", "Close"))
