# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSD2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(9, 9, 961, 720))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainFrame.setObjectName("MainFrame")
        self.tabWidget = QtWidgets.QTabWidget(self.MainFrame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 960, 660))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(460, 20, 221, 160))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(10, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 30, 139, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_che = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_che.setEnabled(True)
        self.checkBox_che.setChecked(True)
        self.checkBox_che.setObjectName("checkBox_che")
        self.verticalLayout.addWidget(self.checkBox_che)
        self.checkBox_acd = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_acd.setChecked(True)
        self.checkBox_acd.setObjectName("checkBox_acd")
        self.verticalLayout.addWidget(self.checkBox_acd)
        self.checkBox_aer = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_aer.setEnabled(True)
        self.checkBox_aer.setChecked(True)
        self.checkBox_aer.setObjectName("checkBox_aer")
        self.verticalLayout.addWidget(self.checkBox_aer)
        self.layoutWidget.raise_()
        self.label_43.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 441, 291))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 30, 410, 250))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.runtime = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.runtime.setFont(font)
        self.runtime.setMaximum(999.99)
        self.runtime.setProperty("value", 24.0)
        self.runtime.setObjectName("runtime")
        self.gridLayout_2.addWidget(self.runtime, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.description = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.description.setFont(font)
        self.description.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description.setMaximumBlockCount(0)
        self.description.setObjectName("description")
        self.gridLayout_2.addWidget(self.description, 4, 1, 2, 5)
        spacerItem = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 3)
        self.run_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.run_name.setFont(font)
        self.run_name.setPlaceholderText("")
        self.run_name.setObjectName("run_name")
        self.gridLayout_2.addWidget(self.run_name, 2, 1, 1, 4)
        self.case_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.case_name.setFont(font)
        self.case_name.setPlaceholderText("")
        self.case_name.setObjectName("case_name")
        self.gridLayout_2.addWidget(self.case_name, 1, 1, 1, 4)
        self.indexRadioDate = QtWidgets.QRadioButton(self.layoutWidget1)
        self.indexRadioDate.setChecked(True)
        self.indexRadioDate.setObjectName("indexRadioDate")
        self.gridLayout_2.addWidget(self.indexRadioDate, 3, 0, 1, 1)
        self.browseCase = QtWidgets.QToolButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseCase.setFont(font)
        self.browseCase.setObjectName("browseCase")
        self.gridLayout_2.addWidget(self.browseCase, 1, 5, 1, 1)
        self.browseRun = QtWidgets.QToolButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseRun.setFont(font)
        self.browseRun.setObjectName("browseRun")
        self.gridLayout_2.addWidget(self.browseRun, 2, 5, 1, 1)
        self.indexRadioIndex = QtWidgets.QRadioButton(self.layoutWidget1)
        self.indexRadioIndex.setObjectName("indexRadioIndex")
        self.gridLayout_2.addWidget(self.indexRadioIndex, 3, 3, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setDate(QtCore.QDate(2025, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        self.indexEdit = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.indexEdit.setFont(font)
        self.indexEdit.setMaximum(999999)
        self.indexEdit.setObjectName("indexEdit")
        self.gridLayout_2.addWidget(self.indexEdit, 3, 4, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(460, 190, 221, 270))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton.setGeometry(QtCore.QRect(420, 140, 27, 21))
        self.toolButton.setObjectName("toolButton")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_4.setEnabled(True)
        self.frame_4.setGeometry(QtCore.QRect(0, 20, 211, 240))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 190, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 0, 0, 1, 1)
        self.n_bins_particle = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n_bins_particle.setFont(font)
        self.n_bins_particle.setMinimum(1)
        self.n_bins_particle.setMaximum(1000)
        self.n_bins_particle.setProperty("value", 100)
        self.n_bins_particle.setObjectName("n_bins_particle")
        self.gridLayout_8.addWidget(self.n_bins_particle, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 1, 0, 1, 1)
        self.psd_mode = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.psd_mode.setFont(font)
        self.psd_mode.setObjectName("psd_mode")
        self.psd_mode.addItem("")
        self.psd_mode.addItem("")
        self.psd_mode.addItem("")
        self.gridLayout_8.addWidget(self.psd_mode, 2, 0, 1, 2)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 99, 190, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 3)
        self.min_particle_diam = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.min_particle_diam.setFont(font)
        self.min_particle_diam.setObjectName("min_particle_diam")
        self.gridLayout_12.addWidget(self.min_particle_diam, 1, 0, 1, 2)
        self.max_particle_diam = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.max_particle_diam.setFont(font)
        self.max_particle_diam.setObjectName("max_particle_diam")
        self.gridLayout_12.addWidget(self.max_particle_diam, 1, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 2, 0, 1, 3)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 4, 0, 1, 3)
        self.dmps_read_in_time = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dmps_read_in_time.setFont(font)
        self.dmps_read_in_time.setMaximum(999.99)
        self.dmps_read_in_time.setProperty("value", 2.0)
        self.dmps_read_in_time.setObjectName("dmps_read_in_time")
        self.gridLayout_12.addWidget(self.dmps_read_in_time, 3, 0, 1, 1)
        self.use_dmps = QtWidgets.QCheckBox(self.layoutWidget3)
        self.use_dmps.setObjectName("use_dmps")
        self.gridLayout_12.addWidget(self.use_dmps, 3, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 320, 441, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setGeometry(QtCore.QRect(367, 122, 50, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setGeometry(QtCore.QRect(11, 130, 320, 16))
        self.label_48.setObjectName("label_48")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 40, 420, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_2.addWidget(self.label_46)
        self.inout_dir = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.inout_dir.setFont(font)
        self.inout_dir.setText("")
        self.inout_dir.setPlaceholderText("")
        self.inout_dir.setObjectName("inout_dir")
        self.horizontalLayout_2.addWidget(self.inout_dir)
        self.browseCommonIn = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseCommonIn.setFont(font)
        self.browseCommonIn.setObjectName("browseCommonIn")
        self.horizontalLayout_2.addWidget(self.browseCommonIn)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 160, 420, 120))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_9.addWidget(self.label_44, 0, 0, 1, 1)
        self.env_file = QtWidgets.QLineEdit(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.env_file.setFont(font)
        self.env_file.setObjectName("env_file")
        self.gridLayout_9.addWidget(self.env_file, 0, 1, 1, 1)
        self.stripRoot_env = QtWidgets.QCheckBox(self.layoutWidget5)
        self.stripRoot_env.setText("")
        self.stripRoot_env.setObjectName("stripRoot_env")
        self.gridLayout_9.addWidget(self.stripRoot_env, 0, 2, 1, 1)
        self.browseEnv = QtWidgets.QToolButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseEnv.setFont(font)
        self.browseEnv.setObjectName("browseEnv")
        self.gridLayout_9.addWidget(self.browseEnv, 0, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_9.addWidget(self.label_45, 1, 0, 1, 1)
        self.mcm_file = QtWidgets.QLineEdit(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mcm_file.setFont(font)
        self.mcm_file.setObjectName("mcm_file")
        self.gridLayout_9.addWidget(self.mcm_file, 1, 1, 1, 1)
        self.stripRoot_mcm = QtWidgets.QCheckBox(self.layoutWidget5)
        self.stripRoot_mcm.setText("")
        self.stripRoot_mcm.setObjectName("stripRoot_mcm")
        self.gridLayout_9.addWidget(self.stripRoot_mcm, 1, 2, 1, 1)
        self.browseMcm = QtWidgets.QToolButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseMcm.setFont(font)
        self.browseMcm.setObjectName("browseMcm")
        self.gridLayout_9.addWidget(self.browseMcm, 1, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 2, 0, 1, 1)
        self.dmps_file = QtWidgets.QLineEdit(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dmps_file.setFont(font)
        self.dmps_file.setObjectName("dmps_file")
        self.gridLayout_9.addWidget(self.dmps_file, 2, 1, 1, 1)
        self.stripRoot_par = QtWidgets.QCheckBox(self.layoutWidget5)
        self.stripRoot_par.setText("")
        self.stripRoot_par.setObjectName("stripRoot_par")
        self.gridLayout_9.addWidget(self.stripRoot_par, 2, 2, 1, 1)
        self.browsePar = QtWidgets.QToolButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browsePar.setFont(font)
        self.browsePar.setObjectName("browsePar")
        self.gridLayout_9.addWidget(self.browsePar, 2, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_53.setObjectName("label_53")
        self.gridLayout_9.addWidget(self.label_53, 3, 0, 1, 1)
        self.extra_particles = QtWidgets.QLineEdit(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.extra_particles.setFont(font)
        self.extra_particles.setObjectName("extra_particles")
        self.gridLayout_9.addWidget(self.extra_particles, 3, 1, 1, 1)
        self.stripRoot_xtr = QtWidgets.QCheckBox(self.layoutWidget5)
        self.stripRoot_xtr.setText("")
        self.stripRoot_xtr.setObjectName("stripRoot_xtr")
        self.gridLayout_9.addWidget(self.stripRoot_xtr, 3, 2, 1, 1)
        self.browseXtr = QtWidgets.QToolButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseXtr.setFont(font)
        self.browseXtr.setObjectName("browseXtr")
        self.gridLayout_9.addWidget(self.browseXtr, 3, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(460, 460, 220, 160))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 193, 90))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 2)
        self.print_interval = QtWidgets.QSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.print_interval.setFont(font)
        self.print_interval.setMinimum(0)
        self.print_interval.setMaximum(1000000)
        self.print_interval.setSingleStep(100)
        self.print_interval.setProperty("value", 600)
        self.print_interval.setObjectName("print_interval")
        self.gridLayout_5.addWidget(self.print_interval, 0, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 2)
        self.fsave_interval = QtWidgets.QSpinBox(self.layoutWidget6)
        self.fsave_interval.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsave_interval.setFont(font)
        self.fsave_interval.setMaximum(1000000)
        self.fsave_interval.setSingleStep(100)
        self.fsave_interval.setProperty("value", 300)
        self.fsave_interval.setObjectName("fsave_interval")
        self.gridLayout_5.addWidget(self.fsave_interval, 1, 2, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 2, 0, 1, 1)
        self.fsave_division = QtWidgets.QSpinBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsave_division.setFont(font)
        self.fsave_division.setMaximum(1000000)
        self.fsave_division.setObjectName("fsave_division")
        self.gridLayout_5.addWidget(self.fsave_division, 2, 1, 1, 3)
        self.print_acdc = QtWidgets.QCheckBox(self.groupBox_5)
        self.print_acdc.setEnabled(True)
        self.print_acdc.setGeometry(QtCore.QRect(10, 130, 137, 20))
        self.print_acdc.setChecked(True)
        self.print_acdc.setObjectName("print_acdc")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(700, 20, 240, 600))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.names_sel = QtWidgets.QListWidget(self.groupBox_6)
        self.names_sel.setGeometry(QtCore.QRect(10, 26, 220, 560))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.names_sel.setFont(font)
        self.names_sel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.names_sel.setLineWidth(0)
        self.names_sel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.names_sel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.names_sel.setProperty("showDropIndicator", False)
        self.names_sel.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.names_sel.setBatchSize(100)
        self.names_sel.setObjectName("names_sel")
        item = QtWidgets.QListWidgetItem()
        self.names_sel.addItem(item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(700, 10, 241, 600))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.namesdat = QtWidgets.QListWidget(self.frame_2)
        self.namesdat.setGeometry(QtCore.QRect(10, 30, 221, 560))
        self.namesdat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.namesdat.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.namesdat.setBatchSize(100)
        self.namesdat.setObjectName("namesdat")
        self.label_54 = QtWidgets.QLabel(self.frame_2)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 220, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.butMoveToSelVars = QtWidgets.QToolButton(self.tab_3)
        self.butMoveToSelVars.setGeometry(QtCore.QRect(615, 230, 70, 40))
        self.butMoveToSelVars.setArrowType(QtCore.Qt.LeftArrow)
        self.butMoveToSelVars.setObjectName("butMoveToSelVars")
        self.selected_vars = QtWidgets.QTableWidget(self.tab_3)
        self.selected_vars.setGeometry(QtCore.QRect(10, 29, 590, 560))
        self.selected_vars.setObjectName("selected_vars")
        self.selected_vars.setColumnCount(8)
        self.selected_vars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.selected_vars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(7, item)
        self.butRemoveSelVars = QtWidgets.QToolButton(self.tab_3)
        self.butRemoveSelVars.setGeometry(QtCore.QRect(615, 370, 70, 40))
        self.butRemoveSelVars.setArrowType(QtCore.Qt.RightArrow)
        self.butRemoveSelVars.setObjectName("butRemoveSelVars")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(615, 190, 70, 40))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setWordWrap(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(615, 330, 70, 40))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.markAll = QtWidgets.QPushButton(self.tab_3)
        self.markAll.setGeometry(QtCore.QRect(610, 520, 90, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.markAll.setPalette(palette)
        self.markAll.setFlat(True)
        self.markAll.setObjectName("markAll")
        self.invertMarks = QtWidgets.QPushButton(self.tab_3)
        self.invertMarks.setGeometry(QtCore.QRect(610, 550, 90, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.invertMarks.setPalette(palette)
        self.invertMarks.setFlat(True)
        self.invertMarks.setObjectName("invertMarks")
        self.loadFixed = QtWidgets.QPushButton(self.tab_3)
        self.loadFixed.setGeometry(QtCore.QRect(410, 600, 190, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.loadFixed.setPalette(palette)
        self.loadFixed.setFlat(True)
        self.loadFixed.setObjectName("loadFixed")
        self.loadFixedChemistry = QtWidgets.QPushButton(self.tab_3)
        self.loadFixedChemistry.setGeometry(QtCore.QRect(10, 600, 280, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.loadFixedChemistry.setPalette(palette)
        self.loadFixedChemistry.setFlat(True)
        self.loadFixedChemistry.setObjectName("loadFixedChemistry")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.PLOTHERE = QtWidgets.QFrame(self.tab_4)
        self.PLOTHERE.setGeometry(QtCore.QRect(10, 10, 674, 611))
        self.PLOTHERE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PLOTHERE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PLOTHERE.setObjectName("PLOTHERE")
        self.PLOT = PlotWidget(self.PLOTHERE)
        self.PLOT.setGeometry(QtCore.QRect(10, 10, 650, 420))
        self.PLOT.setObjectName("PLOT")
        self.fLin = QtWidgets.QRadioButton(self.PLOTHERE)
        self.fLin.setGeometry(QtCore.QRect(420, 440, 61, 20))
        self.fLin.setChecked(True)
        self.fLin.setObjectName("fLin")
        self.fLog = QtWidgets.QRadioButton(self.PLOTHERE)
        self.fLog.setGeometry(QtCore.QRect(490, 440, 101, 20))
        self.fLog.setObjectName("fLog")
        self.layoutWidget7 = QtWidgets.QWidget(self.PLOTHERE)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 440, 390, 23))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 0, 0, 1, 1)
        self.fMin = QtWidgets.QLineEdit(self.layoutWidget7)
        self.fMin.setObjectName("fMin")
        self.gridLayout_10.addWidget(self.fMin, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_59.setObjectName("label_59")
        self.gridLayout_10.addWidget(self.label_59, 0, 2, 1, 1)
        self.fMax = QtWidgets.QLineEdit(self.layoutWidget7)
        self.fMax.setObjectName("fMax")
        self.gridLayout_10.addWidget(self.fMax, 0, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.PLOTHERE)
        self.widget.setGeometry(QtCore.QRect(10, 471, 651, 131))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.resW = QtWidgets.QToolButton(self.widget)
        self.resW.setObjectName("resW")
        self.gridLayout.addWidget(self.resW, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.fWidth = QtWidgets.QScrollBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fWidth.sizePolicy().hasHeightForWidth())
        self.fWidth.setSizePolicy(sizePolicy)
        self.fWidth.setMaximum(200)
        self.fWidth.setProperty("value", 39)
        self.fWidth.setOrientation(QtCore.Qt.Horizontal)
        self.fWidth.setInvertedAppearance(False)
        self.fWidth.setInvertedControls(True)
        self.fWidth.setObjectName("fWidth")
        self.gridLayout.addWidget(self.fWidth, 0, 2, 1, 1)
        self.resP = QtWidgets.QToolButton(self.widget)
        self.resP.setObjectName("resP")
        self.gridLayout.addWidget(self.resP, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 1, 1, 1, 1)
        self.fPeak = QtWidgets.QScrollBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fPeak.sizePolicy().hasHeightForWidth())
        self.fPeak.setSizePolicy(sizePolicy)
        self.fPeak.setMinimum(-10)
        self.fPeak.setMaximum(190)
        self.fPeak.setProperty("value", 84)
        self.fPeak.setOrientation(QtCore.Qt.Horizontal)
        self.fPeak.setInvertedAppearance(False)
        self.fPeak.setInvertedControls(True)
        self.fPeak.setObjectName("fPeak")
        self.gridLayout.addWidget(self.fPeak, 1, 2, 1, 1)
        self.resA = QtWidgets.QToolButton(self.widget)
        self.resA.setObjectName("resA")
        self.gridLayout.addWidget(self.resA, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.widget)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 2, 1, 1, 1)
        self.fFreq = QtWidgets.QScrollBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fFreq.sizePolicy().hasHeightForWidth())
        self.fFreq.setSizePolicy(sizePolicy)
        self.fFreq.setMinimum(-20)
        self.fFreq.setMaximum(220)
        self.fFreq.setOrientation(QtCore.Qt.Horizontal)
        self.fFreq.setInvertedAppearance(False)
        self.fFreq.setInvertedControls(True)
        self.fFreq.setObjectName("fFreq")
        self.gridLayout.addWidget(self.fFreq, 2, 2, 1, 1)
        self.resPh = QtWidgets.QToolButton(self.widget)
        self.resPh.setObjectName("resPh")
        self.gridLayout.addWidget(self.resPh, 3, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.widget)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 3, 1, 1, 1)
        self.fPhase = QtWidgets.QScrollBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fPhase.sizePolicy().hasHeightForWidth())
        self.fPhase.setSizePolicy(sizePolicy)
        self.fPhase.setMinimum(-100)
        self.fPhase.setMaximum(100)
        self.fPhase.setOrientation(QtCore.Qt.Horizontal)
        self.fPhase.setInvertedAppearance(False)
        self.fPhase.setInvertedControls(True)
        self.fPhase.setObjectName("fPhase")
        self.gridLayout.addWidget(self.fPhase, 3, 2, 1, 1)
        self.resAm = QtWidgets.QToolButton(self.widget)
        self.resAm.setObjectName("resAm")
        self.gridLayout.addWidget(self.resAm, 4, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.widget)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 4, 1, 1, 1)
        self.fAmp = QtWidgets.QScrollBar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fAmp.sizePolicy().hasHeightForWidth())
        self.fAmp.setSizePolicy(sizePolicy)
        self.fAmp.setMaximum(200)
        self.fAmp.setProperty("value", 20)
        self.fAmp.setOrientation(QtCore.Qt.Horizontal)
        self.fAmp.setInvertedAppearance(False)
        self.fAmp.setInvertedControls(True)
        self.fAmp.setObjectName("fAmp")
        self.gridLayout.addWidget(self.fAmp, 4, 2, 1, 1)
        self.wScalei = QtWidgets.QSpinBox(self.widget)
        self.wScalei.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.wScalei.setMaximum(5)
        self.wScalei.setProperty("value", 1)
        self.wScalei.setObjectName("wScalei")
        self.gridLayout.addWidget(self.wScalei, 0, 3, 1, 1)
        self.peScale = QtWidgets.QSpinBox(self.widget)
        self.peScale.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.peScale.setMaximum(5)
        self.peScale.setProperty("value", 1)
        self.peScale.setObjectName("peScale")
        self.gridLayout.addWidget(self.peScale, 1, 3, 1, 1)
        self.anScale = QtWidgets.QSpinBox(self.widget)
        self.anScale.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.anScale.setMaximum(5)
        self.anScale.setProperty("value", 1)
        self.anScale.setObjectName("anScale")
        self.gridLayout.addWidget(self.anScale, 2, 3, 1, 1)
        self.phScale = QtWidgets.QSpinBox(self.widget)
        self.phScale.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.phScale.setMaximum(5)
        self.phScale.setProperty("value", 1)
        self.phScale.setObjectName("phScale")
        self.gridLayout.addWidget(self.phScale, 3, 3, 1, 1)
        self.amScale = QtWidgets.QSpinBox(self.widget)
        self.amScale.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.amScale.setMaximum(5)
        self.amScale.setProperty("value", 1)
        self.amScale.setObjectName("amScale")
        self.gridLayout.addWidget(self.amScale, 4, 3, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(700, 10, 241, 521))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.names_sel_2 = QtWidgets.QListWidget(self.frame_3)
        self.names_sel_2.setGeometry(QtCore.QRect(10, 30, 221, 481))
        self.names_sel_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.names_sel_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.names_sel_2.setBatchSize(100)
        self.names_sel_2.setObjectName("names_sel_2")
        item = QtWidgets.QListWidgetItem()
        self.names_sel_2.addItem(item)
        self.label_40 = QtWidgets.QLabel(self.frame_3)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 210, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.saveParams = QtWidgets.QPushButton(self.tab_4)
        self.saveParams.setGeometry(QtCore.QRect(790, 540, 150, 25))
        self.saveParams.setObjectName("saveParams")
        self.layoutWidget8 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget8.setEnabled(False)
        self.layoutWidget8.setGeometry(QtCore.QRect(700, 600, 254, 23))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monW = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.monW.setEnabled(False)
        self.monW.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monW.setSuffix("")
        self.monW.setMinimum(-99.0)
        self.monW.setObjectName("monW")
        self.horizontalLayout.addWidget(self.monW)
        self.monP = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.monP.setEnabled(False)
        self.monP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monP.setMinimum(-99.0)
        self.monP.setObjectName("monP")
        self.horizontalLayout.addWidget(self.monP)
        self.monA = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.monA.setEnabled(False)
        self.monA.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monA.setMinimum(-9.9)
        self.monA.setObjectName("monA")
        self.horizontalLayout.addWidget(self.monA)
        self.monPh = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.monPh.setEnabled(False)
        self.monPh.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monPh.setMinimum(-9.9)
        self.monPh.setObjectName("monPh")
        self.horizontalLayout.addWidget(self.monPh)
        self.monAm = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.monAm.setEnabled(False)
        self.monAm.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monAm.setObjectName("monAm")
        self.horizontalLayout.addWidget(self.monAm)
        self.plotTo = QtWidgets.QPushButton(self.tab_4)
        self.plotTo.setGeometry(QtCore.QRect(700, 540, 80, 25))
        self.plotTo.setCheckable(True)
        self.plotTo.setObjectName("plotTo")
        self.loadParams = QtWidgets.QPushButton(self.tab_4)
        self.loadParams.setGeometry(QtCore.QRect(790, 570, 150, 25))
        self.loadParams.setObjectName("loadParams")
        self.confirm = QtWidgets.QLabel(self.tab_4)
        self.confirm.setGeometry(QtCore.QRect(110, 170, 440, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(115, 9, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(115, 9, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.confirm.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm.setObjectName("confirm")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(13, 30, 101, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(220, 30, 56, 21))
        self.label_18.setObjectName("label_18")
        self.dt = QtWidgets.QSpinBox(self.tab_2)
        self.dt.setGeometry(QtCore.QRect(130, 30, 85, 21))
        self.dt.setMaximum(1000000)
        self.dt.setProperty("value", 10)
        self.dt.setObjectName("dt")
        self.acdc_solve_ss = QtWidgets.QCheckBox(self.tab_2)
        self.acdc_solve_ss.setGeometry(QtCore.QRect(21, 70, 671, 20))
        self.acdc_solve_ss.setChecked(False)
        self.acdc_solve_ss.setObjectName("acdc_solve_ss")
        self.model_h2so4 = QtWidgets.QCheckBox(self.tab_2)
        self.model_h2so4.setGeometry(QtCore.QRect(21, 96, 671, 20))
        self.model_h2so4.setChecked(False)
        self.model_h2so4.setObjectName("model_h2so4")
        self.condensation = QtWidgets.QCheckBox(self.tab_2)
        self.condensation.setGeometry(QtCore.QRect(21, 122, 671, 20))
        self.condensation.setChecked(True)
        self.condensation.setObjectName("condensation")
        self.coagulation = QtWidgets.QCheckBox(self.tab_2)
        self.coagulation.setGeometry(QtCore.QRect(21, 148, 671, 20))
        self.coagulation.setChecked(True)
        self.coagulation.setObjectName("coagulation")
        self.use_dmps_special = QtWidgets.QCheckBox(self.tab_2)
        self.use_dmps_special.setEnabled(True)
        self.use_dmps_special.setGeometry(QtCore.QRect(21, 174, 671, 20))
        self.use_dmps_special.setChecked(False)
        self.use_dmps_special.setObjectName("use_dmps_special")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(20, 400, 300, 21))
        self.label_23.setObjectName("label_23")
        self.wait_for = QtWidgets.QSpinBox(self.tab_2)
        self.wait_for.setGeometry(QtCore.QRect(330, 400, 120, 21))
        self.wait_for.setMinimum(-1)
        self.wait_for.setMaximum(1000000)
        self.wait_for.setProperty("value", 0)
        self.wait_for.setObjectName("wait_for")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 30, 201, 170))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 20, 181, 71))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget9)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.lat = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.lat.setDecimals(3)
        self.lat.setMinimum(-90.0)
        self.lat.setMaximum(90.0)
        self.lat.setSingleStep(1.0)
        self.lat.setProperty("value", 60.0)
        self.lat.setObjectName("lat")
        self.gridLayout_3.addWidget(self.lat, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.lon = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.lon.setDecimals(3)
        self.lon.setMinimum(-180.0)
        self.lon.setMaximum(180.0)
        self.lon.setSingleStep(1.0)
        self.lon.setProperty("value", -25.0)
        self.lon.setObjectName("lon")
        self.gridLayout_3.addWidget(self.lon, 1, 1, 1, 1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 120, 181, 30))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 1)
        self.ch_albedo = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.ch_albedo.setDecimals(3)
        self.ch_albedo.setMinimum(0.0)
        self.ch_albedo.setMaximum(1.0)
        self.ch_albedo.setSingleStep(0.01)
        self.ch_albedo.setProperty("value", 0.2)
        self.ch_albedo.setObjectName("ch_albedo")
        self.gridLayout_7.addWidget(self.ch_albedo, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(730, 230, 201, 220))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.resolve_base = QtWidgets.QCheckBox(self.groupBox_4)
        self.resolve_base.setEnabled(True)
        self.resolve_base.setGeometry(QtCore.QRect(10, 30, 179, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resolve_base.setFont(font)
        self.resolve_base.setCheckable(True)
        self.resolve_base.setChecked(False)
        self.resolve_base.setObjectName("resolve_base")
        self.frameBase = QtWidgets.QFrame(self.groupBox_4)
        self.frameBase.setEnabled(True)
        self.frameBase.setGeometry(QtCore.QRect(10, 50, 191, 160))
        self.frameBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBase.setObjectName("frameBase")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frameBase)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 180, 140))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setEnabled(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 1)
        self.fill_formation_with = QtWidgets.QComboBox(self.layoutWidget_2)
        self.fill_formation_with.setEnabled(True)
        self.fill_formation_with.setObjectName("fill_formation_with")
        self.fill_formation_with.addItem("")
        self.fill_formation_with.addItem("")
        self.fill_formation_with.addItem("")
        self.gridLayout_4.addWidget(self.fill_formation_with, 3, 0, 1, 2)
        self.resolve_base_precision = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.resolve_base_precision.setEnabled(True)
        self.resolve_base_precision.setDecimals(3)
        self.resolve_base_precision.setMaximum(2.0)
        self.resolve_base_precision.setSingleStep(0.01)
        self.resolve_base_precision.setProperty("value", 0.05)
        self.resolve_base_precision.setObjectName("resolve_base_precision")
        self.gridLayout_4.addWidget(self.resolve_base_precision, 0, 1, 1, 1)
        self.dma_f = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.dma_f.setEnabled(True)
        self.dma_f.setDecimals(3)
        self.dma_f.setMaximum(2.0)
        self.dma_f.setSingleStep(0.01)
        self.dma_f.setProperty("value", 0.05)
        self.dma_f.setObjectName("dma_f")
        self.gridLayout_4.addWidget(self.dma_f, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setEnabled(True)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setEnabled(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.layoutWidget10 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget10.setGeometry(QtCore.QRect(40, 199, 651, 50))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget10)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.dmps_highband_lower_limit = QtWidgets.QLineEdit(self.layoutWidget10)
        self.dmps_highband_lower_limit.setEnabled(False)
        self.dmps_highband_lower_limit.setObjectName("dmps_highband_lower_limit")
        self.gridLayout_11.addWidget(self.dmps_highband_lower_limit, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_20.setEnabled(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 1, 0, 1, 1)
        self.dmps_lowband_upper_limit = QtWidgets.QLineEdit(self.layoutWidget10)
        self.dmps_lowband_upper_limit.setEnabled(False)
        self.dmps_lowband_upper_limit.setObjectName("dmps_lowband_upper_limit")
        self.gridLayout_11.addWidget(self.dmps_lowband_upper_limit, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 2, 1, 1)
        self.vap_logical = QtWidgets.QCheckBox(self.tab_2)
        self.vap_logical.setGeometry(QtCore.QRect(20, 260, 420, 30))
        self.vap_logical.setChecked(True)
        self.vap_logical.setObjectName("vap_logical")
        self.frameVap = QtWidgets.QFrame(self.tab_2)
        self.frameVap.setGeometry(QtCore.QRect(30, 289, 470, 60))
        self.frameVap.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameVap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVap.setObjectName("frameVap")
        self.layoutWidget11 = QtWidgets.QWidget(self.frameVap)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 0, 460, 50))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget11)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_51.setObjectName("label_51")
        self.gridLayout_13.addWidget(self.label_51, 0, 0, 1, 1)
        self.vap_names = QtWidgets.QLineEdit(self.layoutWidget11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vap_names.setFont(font)
        self.vap_names.setObjectName("vap_names")
        self.gridLayout_13.addWidget(self.vap_names, 0, 1, 1, 1)
        self.butVapourNames = QtWidgets.QToolButton(self.layoutWidget11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.butVapourNames.setFont(font)
        self.butVapourNames.setObjectName("butVapourNames")
        self.gridLayout_13.addWidget(self.butVapourNames, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_50.setObjectName("label_50")
        self.gridLayout_13.addWidget(self.label_50, 1, 0, 1, 1)
        self.vap_props = QtWidgets.QLineEdit(self.layoutWidget11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vap_props.setFont(font)
        self.vap_props.setObjectName("vap_props")
        self.gridLayout_13.addWidget(self.vap_props, 1, 1, 1, 1)
        self.butVapour = QtWidgets.QToolButton(self.layoutWidget11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.butVapour.setFont(font)
        self.butVapour.setObjectName("butVapour")
        self.gridLayout_13.addWidget(self.butVapour, 1, 2, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(730, 480, 201, 140))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.chemistryModules = QtWidgets.QComboBox(self.groupBox_10)
        self.chemistryModules.setEnabled(True)
        self.chemistryModules.setGeometry(QtCore.QRect(10, 50, 178, 21))
        self.chemistryModules.setObjectName("chemistryModules")
        self.label_39 = QtWidgets.QLabel(self.groupBox_10)
        self.label_39.setEnabled(True)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 160, 20))
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.recompile = QtWidgets.QPushButton(self.groupBox_10)
        self.recompile.setGeometry(QtCore.QRect(10, 90, 180, 30))
        self.recompile.setObjectName("recompile")
        self.compileProgressBar = QtWidgets.QProgressBar(self.groupBox_10)
        self.compileProgressBar.setGeometry(QtCore.QRect(10, 90, 180, 30))
        self.compileProgressBar.setProperty("value", 0)
        self.compileProgressBar.setTextVisible(False)
        self.compileProgressBar.setInvertedAppearance(False)
        self.compileProgressBar.setObjectName("compileProgressBar")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 510, 680, 110))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setFlat(False)
        self.groupBox_11.setCheckable(False)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.batchRangeDay = QtWidgets.QRadioButton(self.groupBox_11)
        self.batchRangeDay.setChecked(True)
        self.batchRangeDay.setObjectName("batchRangeDay")
        self.gridLayout_6.addWidget(self.batchRangeDay, 0, 0, 1, 1)
        self.batchRangeDayBegin = QtWidgets.QDateEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.batchRangeDayBegin.setFont(font)
        self.batchRangeDayBegin.setDate(QtCore.QDate(2020, 1, 1))
        self.batchRangeDayBegin.setObjectName("batchRangeDayBegin")
        self.gridLayout_6.addWidget(self.batchRangeDayBegin, 0, 1, 1, 1)
        self.batchRangeDayEnd = QtWidgets.QDateEdit(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.batchRangeDayEnd.setFont(font)
        self.batchRangeDayEnd.setDate(QtCore.QDate(2020, 1, 5))
        self.batchRangeDayEnd.setObjectName("batchRangeDayEnd")
        self.gridLayout_6.addWidget(self.batchRangeDayEnd, 0, 2, 1, 1)
        self.createBashFile = QtWidgets.QCheckBox(self.groupBox_11)
        self.createBashFile.setEnabled(True)
        self.createBashFile.setChecked(False)
        self.createBashFile.setObjectName("createBashFile")
        self.gridLayout_6.addWidget(self.createBashFile, 0, 3, 1, 1)
        self.batchRangeInd = QtWidgets.QRadioButton(self.groupBox_11)
        self.batchRangeInd.setChecked(False)
        self.batchRangeInd.setObjectName("batchRangeInd")
        self.gridLayout_6.addWidget(self.batchRangeInd, 1, 0, 1, 1)
        self.batchRangeIndBegin = QtWidgets.QSpinBox(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.batchRangeIndBegin.setFont(font)
        self.batchRangeIndBegin.setMinimum(0)
        self.batchRangeIndBegin.setMaximum(999999)
        self.batchRangeIndBegin.setProperty("value", 0)
        self.batchRangeIndBegin.setObjectName("batchRangeIndBegin")
        self.gridLayout_6.addWidget(self.batchRangeIndBegin, 1, 1, 1, 1)
        self.batchRangeIndEnd = QtWidgets.QSpinBox(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.batchRangeIndEnd.setFont(font)
        self.batchRangeIndEnd.setMinimum(0)
        self.batchRangeIndEnd.setMaximum(999999)
        self.batchRangeIndEnd.setProperty("value", 0)
        self.batchRangeIndEnd.setObjectName("batchRangeIndEnd")
        self.gridLayout_6.addWidget(self.batchRangeIndEnd, 1, 2, 1, 1)
        self.saveBatch = QtWidgets.QPushButton(self.groupBox_11)
        self.saveBatch.setObjectName("saveBatch")
        self.gridLayout_6.addWidget(self.saveBatch, 1, 3, 1, 1)
        self.frameAtoms = QtWidgets.QFrame(self.tab_2)
        self.frameAtoms.setGeometry(QtCore.QRect(200, 355, 510, 30))
        self.frameAtoms.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameAtoms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAtoms.setObjectName("frameAtoms")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frameAtoms)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 480, 30))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.butVapourAtoms = QtWidgets.QToolButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.butVapourAtoms.setFont(font)
        self.butVapourAtoms.setObjectName("butVapourAtoms")
        self.gridLayout_15.addWidget(self.butVapourAtoms, 0, 2, 1, 1)
        self.vap_atoms = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vap_atoms.setFont(font)
        self.vap_atoms.setObjectName("vap_atoms")
        self.gridLayout_15.addWidget(self.vap_atoms, 0, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_62.setObjectName("label_62")
        self.gridLayout_15.addWidget(self.label_62, 0, 0, 1, 1)
        self.use_atoms = QtWidgets.QCheckBox(self.tab_2)
        self.use_atoms.setGeometry(QtCore.QRect(20, 355, 170, 30))
        self.use_atoms.setChecked(True)
        self.use_atoms.setObjectName("use_atoms")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_5 = QtWidgets.QFrame(self.tab_5)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 911, 540))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MonitorWindow = QtWidgets.QPlainTextEdit(self.frame_5)
        self.MonitorWindow.setGeometry(QtCore.QRect(10, 10, 891, 520))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.MonitorWindow.setFont(font)
        self.MonitorWindow.setAcceptDrops(False)
        self.MonitorWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MonitorWindow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MonitorWindow.setUndoRedoEnabled(False)
        self.MonitorWindow.setReadOnly(True)
        self.MonitorWindow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.MonitorWindow.setBackgroundVisible(False)
        self.MonitorWindow.setObjectName("MonitorWindow")
        self.frameStart = QtWidgets.QFrame(self.tab_5)
        self.frameStart.setGeometry(QtCore.QRect(230, 570, 250, 60))
        self.frameStart.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStart.setObjectName("frameStart")
        self.startButton = QtWidgets.QPushButton(self.frameStart)
        self.startButton.setGeometry(QtCore.QRect(10, 10, 230, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.frameStop = QtWidgets.QFrame(self.tab_5)
        self.frameStop.setEnabled(True)
        self.frameStop.setGeometry(QtCore.QRect(490, 569, 250, 60))
        self.frameStop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameStop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStop.setObjectName("frameStop")
        self.stopButton = QtWidgets.QPushButton(self.frameStop)
        self.stopButton.setEnabled(True)
        self.stopButton.setGeometry(QtCore.QRect(10, 10, 230, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.pauseScroll = QtWidgets.QPushButton(self.tab_5)
        self.pauseScroll.setGeometry(QtCore.QRect(810, 580, 120, 25))
        self.pauseScroll.setCheckable(True)
        self.pauseScroll.setObjectName("pauseScroll")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.plotResultWindow = PlotWidget(self.tab_6)
        self.plotResultWindow.setGeometry(QtCore.QRect(10, 40, 690, 530))
        self.plotResultWindow.setObjectName("plotResultWindow")
        self.show_netcdf = QtWidgets.QLabel(self.plotResultWindow)
        self.show_netcdf.setGeometry(QtCore.QRect(120, 220, 440, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.show_netcdf.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.show_netcdf.setFont(font)
        self.show_netcdf.setAlignment(QtCore.Qt.AlignCenter)
        self.show_netcdf.setObjectName("show_netcdf")
        self.availableVars = QtWidgets.QListWidget(self.tab_6)
        self.availableVars.setGeometry(QtCore.QRect(710, 40, 221, 530))
        self.availableVars.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.availableVars.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.availableVars.setProperty("showDropIndicator", False)
        self.availableVars.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.availableVars.setBatchSize(100)
        self.availableVars.setObjectName("availableVars")
        self.loadNetcdf = QtWidgets.QPushButton(self.tab_6)
        self.loadNetcdf.setGeometry(QtCore.QRect(10, 590, 221, 30))
        self.loadNetcdf.setObjectName("loadNetcdf")
        self.fLog_2 = QtWidgets.QRadioButton(self.tab_6)
        self.fLog_2.setGeometry(QtCore.QRect(600, 590, 101, 20))
        self.fLog_2.setObjectName("fLog_2")
        self.fLin_2 = QtWidgets.QRadioButton(self.tab_6)
        self.fLin_2.setGeometry(QtCore.QRect(530, 590, 61, 20))
        self.fLin_2.setChecked(True)
        self.fLin_2.setObjectName("fLin_2")
        self.findComp = QtWidgets.QLineEdit(self.tab_6)
        self.findComp.setGeometry(QtCore.QRect(770, 580, 160, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.findComp.setFont(font)
        self.findComp.setObjectName("findComp")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(720, 580, 50, 20))
        self.label_4.setObjectName("label_4")
        self.sumSelection = QtWidgets.QCheckBox(self.tab_6)
        self.sumSelection.setGeometry(QtCore.QRect(770, 606, 160, 20))
        self.sumSelection.setObjectName("sumSelection")
        self.tabWidget.addTab(self.tab_6, "")
        self.printButton = QtWidgets.QPushButton(self.MainFrame)
        self.printButton.setGeometry(QtCore.QRect(10, 670, 130, 30))
        self.printButton.setObjectName("printButton")
        self.saveButton = QtWidgets.QPushButton(self.MainFrame)
        self.saveButton.setGeometry(QtCore.QRect(390, 670, 120, 30))
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(self.MainFrame)
        self.loadButton.setGeometry(QtCore.QRect(530, 670, 130, 30))
        self.loadButton.setObjectName("loadButton")
        self.saveDefaults = QtWidgets.QPushButton(self.MainFrame)
        self.saveDefaults.setGeometry(QtCore.QRect(740, 670, 210, 30))
        self.saveDefaults.setObjectName("saveDefaults")
        self.saveCurrentButton = QtWidgets.QPushButton(self.MainFrame)
        self.saveCurrentButton.setGeometry(QtCore.QRect(160, 670, 210, 30))
        self.saveCurrentButton.setObjectName("saveCurrentButton")
        self.currentAddress = QtWidgets.QLabel(self.centralwidget)
        self.currentAddress.setGeometry(QtCore.QRect(190, 740, 570, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.currentAddress.setFont(font)
        self.currentAddress.setObjectName("currentAddress")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 740, 160, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(770, 750, 190, 40))
        self.label_10.setText("")
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.currentInitFile = QtWidgets.QLabel(self.centralwidget)
        self.currentInitFile.setGeometry(QtCore.QRect(190, 766, 570, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.currentInitFile.setFont(font)
        self.currentInitFile.setObjectName("currentInitFile")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 766, 160, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionQuit_Ctrl_Q = QtWidgets.QAction(MainWindow)
        self.actionQuit_Ctrl_Q.setObjectName("actionQuit_Ctrl_Q")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave_to_current = QtWidgets.QAction(MainWindow)
        self.actionSave_to_current.setObjectName("actionSave_to_current")
        self.actionCreate_output_directories = QtWidgets.QAction(MainWindow)
        self.actionCreate_output_directories.setObjectName("actionCreate_output_directories")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_to_current)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionCreate_output_directories)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_Ctrl_Q)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.runtime)
        MainWindow.setTabOrder(self.runtime, self.case_name)
        MainWindow.setTabOrder(self.case_name, self.run_name)
        MainWindow.setTabOrder(self.run_name, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.description)
        MainWindow.setTabOrder(self.description, self.inout_dir)
        MainWindow.setTabOrder(self.inout_dir, self.browseCommonIn)
        MainWindow.setTabOrder(self.browseCommonIn, self.env_file)
        MainWindow.setTabOrder(self.env_file, self.browseEnv)
        MainWindow.setTabOrder(self.browseEnv, self.mcm_file)
        MainWindow.setTabOrder(self.mcm_file, self.browseMcm)
        MainWindow.setTabOrder(self.browseMcm, self.dmps_file)
        MainWindow.setTabOrder(self.dmps_file, self.browsePar)
        MainWindow.setTabOrder(self.browsePar, self.extra_particles)
        MainWindow.setTabOrder(self.extra_particles, self.browseXtr)
        MainWindow.setTabOrder(self.browseXtr, self.checkBox_che)
        MainWindow.setTabOrder(self.checkBox_che, self.checkBox_acd)
        MainWindow.setTabOrder(self.checkBox_acd, self.checkBox_aer)
        MainWindow.setTabOrder(self.checkBox_aer, self.n_bins_particle)
        MainWindow.setTabOrder(self.n_bins_particle, self.psd_mode)
        MainWindow.setTabOrder(self.psd_mode, self.min_particle_diam)
        MainWindow.setTabOrder(self.min_particle_diam, self.max_particle_diam)
        MainWindow.setTabOrder(self.max_particle_diam, self.dmps_read_in_time)
        MainWindow.setTabOrder(self.dmps_read_in_time, self.print_interval)
        MainWindow.setTabOrder(self.print_interval, self.fsave_interval)
        MainWindow.setTabOrder(self.fsave_interval, self.fsave_division)
        MainWindow.setTabOrder(self.fsave_division, self.print_acdc)
        MainWindow.setTabOrder(self.print_acdc, self.toolButton)
        MainWindow.setTabOrder(self.toolButton, self.selected_vars)
        MainWindow.setTabOrder(self.selected_vars, self.namesdat)
        MainWindow.setTabOrder(self.namesdat, self.butMoveToSelVars)
        MainWindow.setTabOrder(self.butMoveToSelVars, self.butRemoveSelVars)
        MainWindow.setTabOrder(self.butRemoveSelVars, self.markAll)
        MainWindow.setTabOrder(self.markAll, self.invertMarks)
        MainWindow.setTabOrder(self.invertMarks, self.loadFixedChemistry)
        MainWindow.setTabOrder(self.loadFixedChemistry, self.loadFixed)
        MainWindow.setTabOrder(self.loadFixed, self.fMin)
        MainWindow.setTabOrder(self.fMin, self.fMax)
        MainWindow.setTabOrder(self.fMax, self.fLin)
        MainWindow.setTabOrder(self.fLin, self.fLog)
        MainWindow.setTabOrder(self.fLog, self.resW)
        MainWindow.setTabOrder(self.resW, self.resP)
        MainWindow.setTabOrder(self.resP, self.resA)
        MainWindow.setTabOrder(self.resA, self.resPh)
        MainWindow.setTabOrder(self.resPh, self.resAm)
        MainWindow.setTabOrder(self.resAm, self.plotTo)
        MainWindow.setTabOrder(self.plotTo, self.saveParams)
        MainWindow.setTabOrder(self.saveParams, self.loadParams)
        MainWindow.setTabOrder(self.loadParams, self.monW)
        MainWindow.setTabOrder(self.monW, self.monP)
        MainWindow.setTabOrder(self.monP, self.monA)
        MainWindow.setTabOrder(self.monA, self.monPh)
        MainWindow.setTabOrder(self.monPh, self.monAm)
        MainWindow.setTabOrder(self.monAm, self.dt)
        MainWindow.setTabOrder(self.dt, self.acdc_solve_ss)
        MainWindow.setTabOrder(self.acdc_solve_ss, self.model_h2so4)
        MainWindow.setTabOrder(self.model_h2so4, self.condensation)
        MainWindow.setTabOrder(self.condensation, self.coagulation)
        MainWindow.setTabOrder(self.coagulation, self.use_dmps_special)
        MainWindow.setTabOrder(self.use_dmps_special, self.dmps_highband_lower_limit)
        MainWindow.setTabOrder(self.dmps_highband_lower_limit, self.dmps_lowband_upper_limit)
        MainWindow.setTabOrder(self.dmps_lowband_upper_limit, self.wait_for)
        MainWindow.setTabOrder(self.wait_for, self.vap_logical)
        MainWindow.setTabOrder(self.vap_logical, self.vap_names)
        MainWindow.setTabOrder(self.vap_names, self.butVapourNames)
        MainWindow.setTabOrder(self.butVapourNames, self.vap_props)
        MainWindow.setTabOrder(self.vap_props, self.butVapour)
        MainWindow.setTabOrder(self.butVapour, self.batchRangeDay)
        MainWindow.setTabOrder(self.batchRangeDay, self.batchRangeDayBegin)
        MainWindow.setTabOrder(self.batchRangeDayBegin, self.batchRangeDayEnd)
        MainWindow.setTabOrder(self.batchRangeDayEnd, self.batchRangeInd)
        MainWindow.setTabOrder(self.batchRangeInd, self.batchRangeIndBegin)
        MainWindow.setTabOrder(self.batchRangeIndBegin, self.batchRangeIndEnd)
        MainWindow.setTabOrder(self.batchRangeIndEnd, self.createBashFile)
        MainWindow.setTabOrder(self.createBashFile, self.saveBatch)
        MainWindow.setTabOrder(self.saveBatch, self.lat)
        MainWindow.setTabOrder(self.lat, self.lon)
        MainWindow.setTabOrder(self.lon, self.ch_albedo)
        MainWindow.setTabOrder(self.ch_albedo, self.resolve_base)
        MainWindow.setTabOrder(self.resolve_base, self.resolve_base_precision)
        MainWindow.setTabOrder(self.resolve_base_precision, self.fill_formation_with)
        MainWindow.setTabOrder(self.fill_formation_with, self.dma_f)
        MainWindow.setTabOrder(self.dma_f, self.chemistryModules)
        MainWindow.setTabOrder(self.chemistryModules, self.recompile)
        MainWindow.setTabOrder(self.recompile, self.MonitorWindow)
        MainWindow.setTabOrder(self.MonitorWindow, self.startButton)
        MainWindow.setTabOrder(self.startButton, self.stopButton)
        MainWindow.setTabOrder(self.stopButton, self.pauseScroll)
        MainWindow.setTabOrder(self.pauseScroll, self.availableVars)
        MainWindow.setTabOrder(self.availableVars, self.loadNetcdf)
        MainWindow.setTabOrder(self.loadNetcdf, self.fLin_2)
        MainWindow.setTabOrder(self.fLin_2, self.fLog_2)
        MainWindow.setTabOrder(self.fLog_2, self.findComp)
        MainWindow.setTabOrder(self.findComp, self.sumSelection)
        MainWindow.setTabOrder(self.sumSelection, self.printButton)
        MainWindow.setTabOrder(self.printButton, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.loadButton)
        MainWindow.setTabOrder(self.loadButton, self.saveDefaults)
        MainWindow.setTabOrder(self.saveDefaults, self.names_sel_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Modules in use"))
        self.label_43.setText(_translate("MainWindow", "More features in Advanced"))
        self.checkBox_che.setText(_translate("MainWindow", "Use Chemistry"))
        self.checkBox_acd.setText(_translate("MainWindow", "Use ACDC"))
        self.checkBox_aer.setText(_translate("MainWindow", "Use Aerosols"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Model run options"))
        self.label_2.setToolTip(_translate("MainWindow", "Total simulation time in decimal hours"))
        self.label_2.setText(_translate("MainWindow", "Runtime (h):"))
        self.label_5.setToolTip(_translate("MainWindow", "Used for calculation of correct Julian day"))
        self.label_5.setText(_translate("MainWindow", "Case name:"))
        self.label_6.setToolTip(_translate("MainWindow", "Group name, Output is saved under directory named after this"))
        self.label_6.setText(_translate("MainWindow", "Run name:"))
        self.label_8.setToolTip(_translate("MainWindow", "Description of the run, max 1000 characters. This will be saved in all output files."))
        self.label_8.setText(_translate("MainWindow", "Desciption:"))
        self.description.setToolTip(_translate("MainWindow", "Description of the run, max 1000 characters. This will be saved in all output files."))
        self.run_name.setToolTip(_translate("MainWindow", "Run name, output is saved under directory named after this, locating in Batch name directory."))
        self.case_name.setToolTip(_translate("MainWindow", "Group name, output is saved under directory named after this."))
        self.indexRadioDate.setText(_translate("MainWindow", "Date:"))
        self.browseCase.setToolTip(_translate("MainWindow", "Browse for existing case directories"))
        self.browseCase.setText(_translate("MainWindow", "..."))
        self.browseRun.setToolTip(_translate("MainWindow", "Browse for existing run directories"))
        self.browseRun.setText(_translate("MainWindow", "..."))
        self.indexRadioIndex.setText(_translate("MainWindow", "Index:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Aerosol structure"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_36.setText(_translate("MainWindow", "Number of bins"))
        self.label_37.setText(_translate("MainWindow", "PSD scheme:"))
        self.psd_mode.setItemText(0, _translate("MainWindow", "Lukas basic"))
        self.psd_mode.setItemText(1, _translate("MainWindow", "Lukas advanced"))
        self.psd_mode.setItemText(2, _translate("MainWindow", "Lukas premium"))
        self.label_35.setText(_translate("MainWindow", "Particle size range (m):"))
        self.min_particle_diam.setText(_translate("MainWindow", "1e-9"))
        self.max_particle_diam.setText(_translate("MainWindow", "1e-6"))
        self.label_41.setText(_translate("MainWindow", "Read in BG particles for*"))
        self.label_38.setText(_translate("MainWindow", "*) if BG particle file is defined"))
        self.dmps_read_in_time.setSuffix(_translate("MainWindow", " h"))
        self.use_dmps.setText(_translate("MainWindow", "dmps"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Paths and files"))
        self.label_14.setText(_translate("MainWindow", "relative\n"
"to case"))
        self.label_48.setToolTip(_translate("MainWindow", "Use tags \"<>\" to fill date or index; y,m,d,i"))
        self.label_48.setText(_translate("MainWindow", "Input files:"))
        self.label_46.setText(_translate("MainWindow", "Common out:"))
        self.browseCommonIn.setText(_translate("MainWindow", "..."))
        self.label_44.setText(_translate("MainWindow", "ENV input:"))
        self.env_file.setPlaceholderText(_translate("MainWindow", "e.g. dm<yy><mm><ii>.sum"))
        self.stripRoot_env.setToolTip(_translate("MainWindow", "Affects only Batch file creator. If checked, the file is always assumed to locate in the case-index input directory."))
        self.browseEnv.setText(_translate("MainWindow", "..."))
        self.label_45.setText(_translate("MainWindow", "MCM input:"))
        self.stripRoot_mcm.setToolTip(_translate("MainWindow", "Affects only Batch file creator. If checked, the file is always assumed to locate in the case-index input directory."))
        self.browseMcm.setText(_translate("MainWindow", "..."))
        self.label_49.setText(_translate("MainWindow", "BG particles:"))
        self.stripRoot_par.setToolTip(_translate("MainWindow", "Affects only Batch file creator. If checked, the file is always assumed to locate in the case-index input directory."))
        self.browsePar.setText(_translate("MainWindow", "..."))
        self.label_53.setText(_translate("MainWindow", "Extra particles:"))
        self.stripRoot_xtr.setToolTip(_translate("MainWindow", "Affects only Batch file creator. If checked, the file is always assumed to locate in the case-index input directory."))
        self.browseXtr.setText(_translate("MainWindow", "..."))
        self.groupBox_5.setTitle(_translate("MainWindow", "Output"))
        self.label_11.setText(_translate("MainWindow", "Print every:"))
        self.print_interval.setSuffix(_translate("MainWindow", " s"))
        self.label_12.setText(_translate("MainWindow", "Save every:"))
        self.fsave_interval.setSuffix(_translate("MainWindow", " s"))
        self.label_15.setText(_translate("MainWindow", "or:"))
        self.fsave_division.setSuffix(_translate("MainWindow", " samples"))
        self.print_acdc.setText(_translate("MainWindow", "print clusters"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Selected input variables"))
        __sortingEnabled = self.names_sel.isSortingEnabled()
        self.names_sel.setSortingEnabled(False)
        item = self.names_sel.item(0)
        item.setText(_translate("MainWindow", "<select variables from next tab>"))
        self.names_sel.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General options"))
        self.label_54.setText(_translate("MainWindow", "Select input variables:"))
        self.butMoveToSelVars.setText(_translate("MainWindow", "<---"))
        item = self.selected_vars.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Variable"))
        item = self.selected_vars.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Column"))
        item = self.selected_vars.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Multiply"))
        item = self.selected_vars.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Shift"))
        item = self.selected_vars.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Use PM"))
        item = self.selected_vars.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "unit"))
        item = self.selected_vars.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ind"))
        self.butRemoveSelVars.setText(_translate("MainWindow", "--->"))
        self.label_60.setText(_translate("MainWindow", "Move to selected"))
        self.label_61.setText(_translate("MainWindow", "Remove selected"))
        self.markAll.setToolTip(_translate("MainWindow", "Set all variable\'s marks to selected (except TEMPK and PRESSURE)"))
        self.markAll.setText(_translate("MainWindow", "mark all"))
        self.invertMarks.setToolTip(_translate("MainWindow", "Invert all variable\'s marks except TEMPK and PRESSURE"))
        self.invertMarks.setText(_translate("MainWindow", "invert"))
        self.loadFixed.setToolTip(_translate("MainWindow", "Loads fixed variables from KPP def-file. These are variables under the #DEFFIX header."))
        self.loadFixed.setText(_translate("MainWindow", "Load fixed from *.def"))
        self.loadFixedChemistry.setToolTip(_translate("MainWindow", "This will select all fixed variables from the current chemistry (see tab Advanced)"))
        self.loadFixedChemistry.setText(_translate("MainWindow", "Select FIXED from selected chemistry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Input variables"))
        self.fLin.setText(_translate("MainWindow", "Linear"))
        self.fLog.setText(_translate("MainWindow", "Logarithmic"))
        self.label_58.setText(_translate("MainWindow", "Minimum"))
        self.fMin.setText(_translate("MainWindow", "10"))
        self.label_59.setText(_translate("MainWindow", "Maximum"))
        self.fMax.setText(_translate("MainWindow", "100000"))
        self.resW.setText(_translate("MainWindow", "R"))
        self.label.setText(_translate("MainWindow", "Width"))
        self.resP.setText(_translate("MainWindow", "R"))
        self.label_34.setText(_translate("MainWindow", "Peaktime"))
        self.resA.setText(_translate("MainWindow", "R"))
        self.label_55.setText(_translate("MainWindow", "Ang.freq"))
        self.resPh.setText(_translate("MainWindow", "R"))
        self.label_56.setText(_translate("MainWindow", "Phase"))
        self.resAm.setText(_translate("MainWindow", "R"))
        self.label_57.setText(_translate("MainWindow", "Amplitude"))
        __sortingEnabled = self.names_sel_2.isSortingEnabled()
        self.names_sel_2.setSortingEnabled(False)
        item = self.names_sel_2.item(0)
        item.setText(_translate("MainWindow", "<select variables from next tab>"))
        self.names_sel_2.setSortingEnabled(__sortingEnabled)
        self.label_40.setText(_translate("MainWindow", "Selected input variables:"))
        self.saveParams.setText(_translate("MainWindow", "Save to selected"))
        self.plotTo.setText(_translate("MainWindow", "Plot 2nd"))
        self.loadParams.setText(_translate("MainWindow", "Load selected"))
        self.confirm.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Function creator"))
        self.label_17.setText(_translate("MainWindow", "Model timestep"))
        self.label_18.setText(_translate("MainWindow", "seconds"))
        self.acdc_solve_ss.setText(_translate("MainWindow", "Solve ACDC to Steady State (might be necessary, if acid/base concentrations vary rapidly)"))
        self.model_h2so4.setText(_translate("MainWindow", "Replace any H2SO4 input with modelled (requires corresponding chemistry)."))
        self.condensation.setText(_translate("MainWindow", "Aerosols includes condensation. If unchecked, condensation is not considered."))
        self.coagulation.setText(_translate("MainWindow", "Aerosols includes coagulation. If unchecked, coagulation is not considered."))
        self.use_dmps_special.setText(_translate("MainWindow", "Use background particles for the whole run"))
        self.label_23.setText(_translate("MainWindow", "Before the simulation starts, pause program for "))
        self.wait_for.setToolTip(_translate("MainWindow", "0=don\'t wait, negative=wait indefinitely"))
        self.wait_for.setSuffix(_translate("MainWindow", " seconds"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Location"))
        self.label_25.setText(_translate("MainWindow", "Latitude"))
        self.lat.setToolTip(_translate("MainWindow", "Negative values = South"))
        self.label_9.setText(_translate("MainWindow", "Longitude"))
        self.lon.setToolTip(_translate("MainWindow", "Negative values = East"))
        self.label_33.setText(_translate("MainWindow", "Surface albedo"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Formation rates"))
        self.resolve_base.setText(_translate("MainWindow", "Solve bases"))
        self.label_26.setText(_translate("MainWindow", "Precision"))
        self.fill_formation_with.setItemText(0, _translate("MainWindow", "Fixed ratio"))
        self.fill_formation_with.setItemText(1, _translate("MainWindow", "Fill with DMA"))
        self.fill_formation_with.setItemText(2, _translate("MainWindow", "Fill with NH3"))
        self.label_28.setText(_translate("MainWindow", "Use fixed ratio or fill gap from ACDC"))
        self.label_27.setText(_translate("MainWindow", "Ratio"))
        self.label_19.setText(_translate("MainWindow", "Highband lower limit (m)"))
        self.label_20.setText(_translate("MainWindow", "Larger (diam) particles will be replaced with background particles."))
        self.label_21.setText(_translate("MainWindow", "Lowband upper limit (m)"))
        self.label_22.setText(_translate("MainWindow", "Smaller (diam) particles will be replaced with background particles."))
        self.vap_logical.setText(_translate("MainWindow", "Vapour properties in use"))
        self.label_51.setText(_translate("MainWindow", "Path to vapour names"))
        self.vap_names.setText(_translate("MainWindow", "Vapour_names.dat"))
        self.butVapourNames.setText(_translate("MainWindow", "..."))
        self.label_50.setText(_translate("MainWindow", "Path to vapour properties    "))
        self.vap_props.setText(_translate("MainWindow", "Vapour_properties.dat"))
        self.butVapour.setText(_translate("MainWindow", "..."))
        self.groupBox_10.setTitle(_translate("MainWindow", "Chemistry module"))
        self.label_39.setText(_translate("MainWindow", "Available modules"))
        self.recompile.setText(_translate("MainWindow", "Recompile program"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Create batch (using the Case, Run and input from General options)"))
        self.batchRangeDay.setText(_translate("MainWindow", "Range (including):"))
        self.batchRangeDayBegin.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.batchRangeDayEnd.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.createBashFile.setText(_translate("MainWindow", "Create bash file"))
        self.batchRangeInd.setText(_translate("MainWindow", "Indices (including)"))
        self.saveBatch.setText(_translate("MainWindow", "Preview batch"))
        self.butVapourAtoms.setText(_translate("MainWindow", "..."))
        self.vap_atoms.setText(_translate("MainWindow", "ModelLib/O_C.dat"))
        self.label_62.setText(_translate("MainWindow", "Path to atom file"))
        self.use_atoms.setText(_translate("MainWindow", "Vapour atom content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced"))
        self.startButton.setText(_translate("MainWindow", "Run with current settings"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.pauseScroll.setText(_translate("MainWindow", "Pause scroll"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Test run"))
        self.show_netcdf.setText(_translate("MainWindow", "This feature needs NetCDF for Python"))
        self.loadNetcdf.setText(_translate("MainWindow", "Load Box output file"))
        self.fLog_2.setText(_translate("MainWindow", "Logarithmic"))
        self.fLin_2.setText(_translate("MainWindow", "Linear"))
        self.findComp.setToolTip(_translate("MainWindow", "Case insensitive filter. Use dot (.) in the end of the search to search for exact match."))
        self.label_4.setText(_translate("MainWindow", "Filter:"))
        self.sumSelection.setText(_translate("MainWindow", "Sum selection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Output graph"))
        self.printButton.setText(_translate("MainWindow", "Print INIT"))
        self.saveButton.setText(_translate("MainWindow", "Save As"))
        self.loadButton.setText(_translate("MainWindow", "Load INIT"))
        self.saveDefaults.setText(_translate("MainWindow", "Save settings as defaults"))
        self.saveCurrentButton.setText(_translate("MainWindow", "Save to current INIT"))
        self.currentAddress.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Current output address:"))
        self.currentInitFile.setText(_translate("MainWindow", "Current INITFILE"))
        self.label_13.setText(_translate("MainWindow", "Current INITFILE:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_2.setText(_translate("MainWindow", "Save As"))
        self.actionSave_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit_Ctrl_Q.setText(_translate("MainWindow", "Quit"))
        self.actionQuit_Ctrl_Q.setToolTip(_translate("MainWindow", "Quit without save"))
        self.actionQuit_Ctrl_Q.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open settings file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionPrint.setText(_translate("MainWindow", "Print settings"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave_to_current.setText(_translate("MainWindow", "Save to current"))
        self.actionSave_to_current.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCreate_output_directories.setText(_translate("MainWindow", "Create output directories"))
        self.actionCreate_output_directories.setShortcut(_translate("MainWindow", "Ctrl+D"))
from pyqtgraph import PlotWidget
