! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : second_Rates.f90
! Time                 : Wed Oct  2 15:56:48 2019
! Working directory    : /Users/boy/Documents/Michael/Model/Chemistry/Test
! Equation file        : second.kpp
! Output root filename : second
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE second_Rates

  USE second_Parameters
  USE second_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE second_Parameters
      !USE second_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST

 
  ! generic reaction rate variables
  REAL(dp) kro2no, kro2ho2, kapho2, kapno, kro2no3, kno3al, kdec, &
    krosec, kalkoxy, kalkpxy, kroprim, k14isom1
  ! variables for calculation of kfpan and kbpan
  REAL(dp) kfpan, kbpan
  REAL(dp) kc0, kci, krc, fcc, nc, fc
  REAL(dp) kd0, kdi, krd, fcd, ncd, fd
  ! variables for calculation of kmt01
  REAL(dp) kmt01
  REAL(dp) k10, k1i, kr1, fc1, nc1, f1
  ! variables for calculation of kmt02
  REAL(dp) kmt02
  REAL(dp) k20, k2i, kr2, fc2, nc2, f2
  ! variables for calculation of kmt03
  REAL(dp) kmt03
  REAL(dp) k30, k3i, kr3, fc3, nc3, f3
  ! variables for calculation of kmt04
  REAL(dp) kmt04
  REAL(dp) k40, k4i, kr4, fc4, nc4, f4
  ! variables for calculation of kmt05
  REAL(dp) kmt05
  ! variables for calculation of kmt06
  REAL(dp) kmt06
  ! variables for calculation of kmt07
  REAL(dp) kmt07
  REAL(dp) k70, k7i, kr7, fc7, nc7, f7
  ! variables for calculation of kmt08
  REAL(dp) kmt08
  REAL(dp) k80, k8i, kr8, fc8, nc8, f8
  ! variables for calculation of kmt09
  REAL(dp) kmt09
  REAL(dp) k90, k9i, kr9, fc9, nc9, f9
  ! variables for calculation of kmt10
  REAL(dp) kmt10
  REAL(dp) k100, k10i, kr10, fc10, nc10, f10
  ! variables for calculation of kmt11
  REAL(dp) kmt11
  REAL(dp) k1,k2,k3,k4
  ! variables for calculation of kmt12
  REAL(dp) kmt12
  REAL(dp) k0, ki, x, ssign,f
  REAL(dp) k120, k12i, kr12, fc12, nc12, f12
  ! variables for calculation of kmt13
  REAL(dp) kmt13
  REAL(dp) k130, k13i, kr13, nc13, fc13, f13
  ! variables for calculation of kmt14
  REAL(dp) kmt14
  REAL(dp) k140, k14i, kr14, nc14, fc14, f14
  ! variables for calculation of kmt15
  REAL(dp) kmt15
  REAL(dp) k150, k15i, kr15, fc15, nc15, f15
  ! variables for calculation of kmt16
  REAL(dp) kmt16
  REAL(dp) k160, k16i, kr16, nc16, fc16, f16
  ! variables for calculation of kmt17
  REAL(dp) kmt17
  REAL(dp) k170, k17i, kr17, fc17, nc17, f17
  ! variables for calculation of kmt17
  REAL(dp) kmt18
  ! variables for calculation of kbppn
  REAL(dp) :: kbppn
  REAL(dp) :: kppn0, kppni, krppn, fcppn, ncppn, fppn

  REAL(dp) kch3o2, k298ch3o2
  
  REAL(dp) kp_rooh, kp_ho2, kp_n2o5, kp_no3, kp_all

! USE constants
 !end of USE statements
 !
 ! start of executable statements
 RO2 = &
 C(ind_CH3O2) + C(ind_NAPINAO2) + C(ind_NAPINBO2) + C(ind_APINAO2) + &
   C(ind_APINBO2) + C(ind_APINCO2) + C(ind_C107O2) + C(ind_C109O2) + &
   C(ind_C96O2) + C(ind_NC101O2) + C(ind_C96CO3) + C(ind_C720O2) + &
   C(ind_PINALO2) + C(ind_C108O2) + C(ind_C89CO3) + C(ind_C920CO3) + &
   C(ind_C920O2) + C(ind_C97O2) + C(ind_C85CO3) + C(ind_C85O2) + &
   C(ind_CH3COCH2O2) + C(ind_CH3CO3) + C(ind_C719O2) + C(ind_NC102O2) + &
   C(ind_C106O2) + C(ind_C717O2) + C(ind_C811CO3) + C(ind_C89O2) + &
   C(ind_C921O2) + C(ind_C98O2) + C(ind_C86O2) + C(ind_CO235C6CO3) + &
   C(ind_CHOC3COCO3) + C(ind_NC71O2) + C(ind_C811O2) + C(ind_CHOC3COO2) + &
   C(ind_H3C25C6CO3) + C(ind_H3C25C6O2) + C(ind_CO235C6O2) + &
   C(ind_C716O2) + C(ind_C810O2) + C(ind_C922O2) + C(ind_C614O2) + &
   C(ind_C511O2) + C(ind_C812O2) + C(ind_C721CO3) + C(ind_C721O2) + &
   C(ind_HCOCH2CO3) + C(ind_BIACETO2) + C(ind_HOCH2CO3) + &
   C(ind_H3C2C4CO3) + C(ind_HMVKAO2) + C(ind_CO23C4CO3) + &
   C(ind_C312COCO3) + C(ind_CHOCOCH2O2) + C(ind_NC72O2) + C(ind_C514O2) + &
   C(ind_HCOCH2O2) + C(ind_C621O2) + C(ind_C813O2) + C(ind_C722O2) + &
   C(ind_CO2H3CO3) + C(ind_NC61CO3) + C(ind_HCOCO3) + C(ind_C516O2) + &
   C(ind_C44O2) + C(ind_H1C23C4CO3) + C(ind_H1C23C4O2 )
 KRO2NO = 2.7D-12*EXP(360/TEMP)
KRO2HO2 = 2.91D-13*EXP(1300/TEMP)
KAPHO2 = 5.2D-13*EXP(980/TEMP)
KAPNO = 7.5D-12*EXP(290/TEMP)
KRO2NO3 = 2.3D-12
KNO3AL = 1.44D-12*EXP(-1862/TEMP)
KDEC = 1.00D+06
KROPRIM = 2.50D-14*EXP(-300/TEMP)
KROSEC = 2.50D-14*EXP(-300/TEMP)
KCH3O2 = 1.03D-13*EXP(365/TEMP)
K298CH3O2 = 3.5D-13
K14ISOM1 = 3.00D7*EXP(-5300/TEMP)
KD0 = 1.10D-05*M*EXP(-10100/TEMP)
KDI = 1.90D17*EXP(-14100/TEMP)
KRD = KD0/KDI
FCD = 0.30
NCD = 0.75-1.27*(LOG10(FCD))
FD = 10**(LOG10(FCD)/(1+(LOG10(KRD)/NCD)**2))
KBPAN = (KD0*KDI)*FD/(KD0+KDI)
KC0 = 3.28D-28*M*(TEMP/300)**-6.87
KCI = 1.125D-11*(TEMP/300)**-1.105
KRC = KC0/KCI
FCC = 0.30
NC = 0.75-1.27*(LOG10(FCC))
FC = 10**(LOG10(FCC)/(1+(LOG10(KRC)/NC)**2))
KFPAN = (KC0*KCI)*FC/(KC0+KCI)
K10 = 1.0D-31*M*(TEMP/300)**-1.6
K1I = 5.0D-11*(TEMP/300)**-0.3
KR1 = K10/K1I
FC1 = 0.85
NC1 = 0.75-1.27*(LOG10(FC1))
F1 = 10**(LOG10(FC1)/(1+(LOG10(KR1)/NC1)**2))
KMT01 = (K10*K1I)*F1/(K10+K1I)
K20 = 1.3D-31*M*(TEMP/300)**-1.5
K2I = 2.3D-11*(TEMP/300)**0.24
KR2 = K20/K2I
FC2 = 0.6
NC2 = 0.75-1.27*(LOG10(FC2))
F2 = 10**(LOG10(FC2)/(1+(LOG10(KR2)/NC2)**2))
KMT02 = (K20*K2I)*F2/(K20+K2I)
K30 = 3.6D-30*M*(TEMP/300)**-4.1
K3I = 1.9D-12*(TEMP/300)**0.2
KR3 = K30/K3I
FC3 = 0.35
NC3 = 0.75-1.27*(LOG10(FC3))
F3 = 10**(LOG10(FC3)/(1+(LOG10(KR3)/NC3)**2))
KMT03 = (K30*K3I)*F3/(K30+K3I)
K40 = 1.3D-3*M*(TEMP/300)**-3.5*EXP(-11000/TEMP)
K4I = 9.7D+14*(TEMP/300)**0.1*EXP(-11080/TEMP)
KR4 = K40/K4I
FC4 = 0.35
NC4 = 0.75-1.27*(LOG10(FC4))
F4 = 10**(LOG10(FC4)/(1+(LOG10(KR4)/NC4)**2))
KMT04 = (K40*K4I)*F4/(K40+K4I)
KMT05 = 1.44D-13*(1+(M/4.2D+19))
KMT06 = 1 + (1.40D-21*EXP(2200/TEMP)*H2O)
K70 = 7.4D-31*M*(TEMP/300)**-2.4
K7I = 3.3D-11*(TEMP/300)**-0.3
KR7 = K70/K7I
FC7 = 0.81
NC7 = 0.75-1.27*(LOG10(FC7))
F7 = 10**(LOG10(FC7)/(1+(LOG10(KR7)/NC7)**2))
KMT07 = (K70*K7I)*F7/(K70+K7I)
K80 = 3.2D-30*M*(TEMP/300)**-4.5
K8I = 3.0D-11
KR8 = K80/K8I
FC8 = 0.41
NC8 = 0.75-1.27*(LOG10(FC8))
F8 = 10**(LOG10(FC8)/(1+(LOG10(KR8)/NC8)**2))
KMT08 = (K80*K8I)*F8/(K80+K8I)
K90 = 1.4D-31*M*(TEMP/300)**-3.1
K9I = 4.0D-12
KR9 = K90/K9I
FC9 = 0.4
NC9 = 0.75-1.27*(LOG10(FC9))
F9 = 10**(LOG10(FC9)/(1+(LOG10(KR9)/NC9)**2))
KMT09 = (K90*K9I)*F9/(K90+K9I)
K100 = 4.10D-05*M*EXP(-10650/TEMP)
K10I = 6.0D+15*EXP(-11170/TEMP)
KR10 = K100/K10I
FC10 = 0.4
NC10 = 0.75-1.27*(LOG10(FC10))
F10 = 10**(LOG10(FC10)/(1+(LOG10(KR10)/NC10)**2))
KMT10 = (K100*K10I)*F10/(K100+K10I)
K1 = 2.40D-14*EXP(460/TEMP)
K3 = 6.50D-34*EXP(1335/TEMP)
K4 = 2.70D-17*EXP(2199/TEMP)
K2 = (K3*M)/(1+(K3*M/K4))
KMT11 = K1 + K2
K120 = 2.5D-31*M*(TEMP/300)**-2.6
K12I = 2.0D-12
KR12 = K120/K12I
FC12 = 0.53
NC12 = 0.75-1.27*(LOG10(FC12))
F12 = 10**(LOG10(FC12)/(1.0+(LOG10(KR12)/NC12)**2))
KMT12 = (K120*K12I*F12)/(K120+K12I)
K130 = 2.5D-30*M*(TEMP/300)**-5.5
K13I = 1.8D-11
KR13 = K130/K13I
FC13 = 0.36
NC13 = 0.75-1.27*(LOG10(FC13))
F13 = 10**(LOG10(FC13)/(1+(LOG10(KR13)/NC13)**2))
KMT13 = (K130*K13I)*F13/(K130+K13I)
K140 = 9.0D-5*EXP(-9690/TEMP)*M
K14I = 1.1D+16*EXP(-10560/TEMP)
KR14 = K140/K14I
FC14 = 0.36
NC14 = 0.75-1.27*(LOG10(FC14))
F14 = 10**(LOG10(FC14)/(1+(LOG10(KR14)/NC14)**2))
KMT14 = (K140*K14I)*F14/(K140+K14I)
K150 = 8.6D-29*M*(TEMP/300)**-3.1
K15I = 9.0D-12*(TEMP/300)**-0.85
KR15 = K150/K15I
FC15 = 0.48
NC15 = 0.75-1.27*(LOG10(FC15))
F15 = 10**(LOG10(FC15)/(1+(LOG10(KR15)/NC15)**2))
KMT15 = (K150*K15I)*F15/(K150+K15I)
K160 = 8D-27*M*(TEMP/300)**-3.5
K16I = 3.0D-11*(TEMP/300)**-1
KR16 = K160/K16I
FC16 = 0.5
NC16 = 0.75-1.27*(LOG10(FC16))
F16 = 10**(LOG10(FC16)/(1+(LOG10(KR16)/NC16)**2))
KMT16 = (K160*K16I)*F16/(K160+K16I)
K170 = 5.0D-30*M*(TEMP/300)**-1.5
K17I = 1.0D-12
KR17 = K170/K17I
FC17 = 0.17*EXP(-51/TEMP)+EXP(-TEMP/204)
NC17 = 0.75-1.27*(LOG10(FC17))
F17 = 10**(LOG10(FC17)/(1.0+(LOG10(KR17)/NC17)**2))
KMT17 = (K170*K17I*F17)/(K170+K17I)
KMT18 = 9.5D-39*O2*EXP(5270/TEMP)/(1+7.5D-29*O2*EXP(5610/TEMP))
KPPN0 = 1.7D-03*EXP(-11280/TEMP)*M
KPPNI = 8.3D+16*EXP(-13940/TEMP)
KRPPN = KPPN0/KPPNI
FCPPN = 0.36
NCPPN = 0.75-1.27*(LOG10(FCPPN))
FPPN = 10**(LOG10(FCPPN)/(1+(LOG10(KRPPN)/NCPPN)**2))
KBPPN = (KPPN0*KPPNI)*FCPPN/(KPPN0+KPPNI)

!CALL mcm_constants(time, temp, M, N2, O2, RO2, H2O)
 
! End INLINED RCONST

  RCONST(1) = (5.6D-34*N2*(TEMP/300)**-2.6*O2+6.0D-34*O2*(TEMP/300)**-2.6*O2)
  RCONST(2) = (8.0D-12*EXP(-2060/TEMP))
  RCONST(3) = (KMT01)
  RCONST(4) = (5.5D-12*EXP(188/TEMP))
  RCONST(5) = (KMT02)
  RCONST(6) = (3.2D-11*EXP(67/TEMP)*O2+2.0D-11*EXP(130/TEMP)*N2)
  RCONST(7) = (1.4D-12*EXP(-1310/TEMP))
  RCONST(8) = (1.4D-13*EXP(-2470/TEMP))
  RCONST(9) = (3.3D-39*EXP(530/TEMP)*O2)
  RCONST(10) = (1.8D-11*EXP(110/TEMP))
  RCONST(11) = (4.50D-14*EXP(-1260/TEMP))
  RCONST(12) = (KMT03)
  RCONST(13) = (2.14D-10*H2O)
  RCONST(14) = (1.70D-12*EXP(-940/TEMP))
  RCONST(15) = (7.7D-12*EXP(-2100/TEMP))
  RCONST(16) = (KMT05)
  RCONST(17) = (2.9D-12*EXP(-160/TEMP))
  RCONST(18) = (2.03D-16*(TEMP/300)**4.57*EXP(693/TEMP))
  RCONST(19) = (4.8D-11*EXP(250/TEMP))
  RCONST(20) = (2.20D-13*KMT06*EXP(600/TEMP)+1.90D-33*M*KMT06*EXP(980/TEMP))
  RCONST(21) = (KMT07)
  RCONST(22) = (KMT08)
  RCONST(23) = (2.0D-11)
  RCONST(24) = (3.45D-12*EXP(270/TEMP))
  RCONST(25) = (KMT09)
  RCONST(26) = (3.2D-13*EXP(690/TEMP)*1.0)
  RCONST(27) = (4.0D-12)
  RCONST(28) = (2.5D-12*EXP(260/TEMP))
  RCONST(29) = (KMT11)
  RCONST(30) = (4.0D-32*EXP(-1000/TEMP)*M)
  RCONST(31) = (KMT12)
  RCONST(32) = (1.3D-12*EXP(-330/TEMP)*O2)
  RCONST(33) = (6.00D-06)
  RCONST(34) = (4.00D-04)
  RCONST(35) = (1.20D-15*H2O)
  RCONST(36) = (J(1))
  RCONST(37) = (J(2))
  RCONST(38) = (J(3))
  RCONST(39) = (J(4))
  RCONST(40) = (J(5))
  RCONST(41) = (J(6))
  RCONST(42) = (J(7))
  RCONST(43) = (J(8))
  RCONST(44) = (KMT04)
  RCONST(45) = (KMT10)
  RCONST(46) = (6.6D-12*EXP(-1240/TEMP))
  RCONST(47) = (1.85D-12*EXP(-1690/TEMP))
  RCONST(48) = (1.2D-12*EXP(490/TEMP)*0.65)
  RCONST(49) = (1.2D-12*EXP(490/TEMP)*0.35)
  RCONST(50) = (8.05D-16*EXP(-640/TEMP)*0.6)
  RCONST(51) = (8.05D-16*EXP(-640/TEMP)*0.4)
  RCONST(52) = (1.2D-11*EXP(440/TEMP)*0.572)
  RCONST(53) = (1.2D-11*EXP(440/TEMP)*0.353)
  RCONST(54) = (1.2D-11*EXP(440/TEMP)*0.075)
  RCONST(55) = (3.8D-13*EXP(780/TEMP)*(1-1/(1+498*EXP(-1160/TEMP))))
  RCONST(56) = (3.8D-13*EXP(780/TEMP)*(1/(1+498*EXP(-1160/TEMP))))
  RCONST(57) = (2.3D-12*EXP(360/TEMP)*0.001)
  RCONST(58) = (2.3D-12*EXP(360/TEMP)*0.999)
  RCONST(59) = (KMT13)
  RCONST(60) = (1.2D-12)
  RCONST(61) = (2*KCH3O2*RO2*7.18*EXP(-885/TEMP))
  RCONST(62) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(63) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(64) = (KRO2HO2*0.914)
  RCONST(65) = (KRO2NO)
  RCONST(66) = (KRO2NO3)
  RCONST(67) = (6.70D-15*0.1*RO2)
  RCONST(68) = (6.70D-15*0.9*RO2)
  RCONST(69) = (KRO2HO2*0.914)
  RCONST(70) = (KRO2NO)
  RCONST(71) = (KRO2NO3)
  RCONST(72) = (2.50D-13*0.1*RO2)
  RCONST(73) = (2.50D-13*0.8*RO2)
  RCONST(74) = (2.50D-13*0.1*RO2)
  RCONST(75) = (KDEC*0.55)
  RCONST(76) = (KDEC*0.45)
  RCONST(77) = (KDEC*0.50)
  RCONST(78) = (KDEC*0.50)
  RCONST(79) = (KRO2HO2*0.914)
  RCONST(80) = (KRO2NO*0.230)
  RCONST(81) = (KRO2NO*0.770)
  RCONST(82) = (KRO2NO3)
  RCONST(83) = (9.20D-14*RO2*0.7)
  RCONST(84) = (9.20D-14*RO2*0.3)
  RCONST(85) = (KRO2HO2*0.914)
  RCONST(86) = (KRO2NO*0.230)
  RCONST(87) = (KRO2NO*0.770)
  RCONST(88) = (KRO2NO3)
  RCONST(89) = (8.80D-13*RO2*0.2)
  RCONST(90) = (8.80D-13*RO2*0.6)
  RCONST(91) = (8.80D-13*RO2*0.2)
  RCONST(92) = (KRO2HO2*0.914)
  RCONST(93) = (KRO2NO*0.125)
  RCONST(94) = (KRO2NO*0.875)
  RCONST(95) = (KRO2NO3)
  RCONST(96) = (6.70D-15*RO2*0.7)
  RCONST(97) = (6.70D-15*RO2*0.3)
  RCONST(98) = (J(41))
  RCONST(99) = (5.3D-12*EXP(190/TEMP)*0.6)
  RCONST(100) = (5.3D-12*EXP(190/TEMP)*0.4)
  RCONST(101) = (J(11))
  RCONST(102) = (J(12))
  RCONST(103) = (5.5D-16)
  RCONST(104) = (5.4D-12*EXP(135/TEMP))
  RCONST(105) = (J(51))
  RCONST(106) = (4.0D-13*EXP(-845/TEMP))
  RCONST(107) = (7.2D-14*EXP(-1080/TEMP)*O2)
  RCONST(108) = (KMT14)
  RCONST(109) = (2.85D-12*EXP(-345/TEMP))
  RCONST(110) = (6.87D-12)
  RCONST(111) = (J(41))
  RCONST(112) = (KDEC)
  RCONST(113) = (3.64D-12)
  RCONST(114) = (1.90D-12*EXP(190/TEMP))
  RCONST(115) = (1.23D-11)
  RCONST(116) = (J(41))
  RCONST(117) = (KROSEC*O2)
  RCONST(118) = (4.00D+05)
  RCONST(119) = (5.50D-12)
  RCONST(120) = (5.55D-12)
  RCONST(121) = (J(55))
  RCONST(122) = (KRO2HO2*0.914)
  RCONST(123) = (KRO2NO)
  RCONST(124) = (KRO2NO3)
  RCONST(125) = (9.20D-14*0.7*RO2)
  RCONST(126) = (9.20D-14*0.3*RO2)
  RCONST(127) = (KRO2HO2*0.914)
  RCONST(128) = (KRO2NO)
  RCONST(129) = (KRO2NO3)
  RCONST(130) = (2.00D-12*RO2*0.05)
  RCONST(131) = (2.00D-12*RO2*0.90)
  RCONST(132) = (2.00D-12*RO2*0.05)
  RCONST(133) = (1.20D-15)
  RCONST(134) = (1.00D-14)
  RCONST(135) = (1.00D-15)
  RCONST(136) = (7.00D-14)
  RCONST(137) = (1.40D-17*H2O)
  RCONST(138) = (2.00D-18*H2O)
  RCONST(139) = (KRO2HO2*0.890)
  RCONST(140) = (KRO2NO*0.157)
  RCONST(141) = (KRO2NO*0.843)
  RCONST(142) = (KRO2NO3)
  RCONST(143) = (1.30D-12*0.6*RO2)
  RCONST(144) = (1.30D-12*0.2*RO2)
  RCONST(145) = (1.30D-12*0.2*RO2)
  RCONST(146) = (1.83D-11)
  RCONST(147) = (J(41))
  RCONST(148) = (KDEC)
  RCONST(149) = (1.49D-11)
  RCONST(150) = (3.28D-11)
  RCONST(151) = (J(41))
  RCONST(152) = (KDEC)
  RCONST(153) = (8.18D-12)
  RCONST(154) = (1.03D-10)
  RCONST(155) = (J(41))
  RCONST(156) = (9.87D-11)
  RCONST(157) = (J(55))
  RCONST(158) = (KDEC)
  RCONST(159) = (9.91D-11)
  RCONST(160) = (2.0D-14)
  RCONST(161) = (5.2D-12*EXP(600/TEMP)*0.772)
  RCONST(162) = (5.2D-12*EXP(600/TEMP)*0.228)
  RCONST(163) = (J(15))
  RCONST(164) = (KRO2HO2*0.914)
  RCONST(165) = (KRO2NO)
  RCONST(166) = (KRO2NO3)
  RCONST(167) = (6.70D-15*RO2)
  RCONST(168) = (KAPHO2*0.44)
  RCONST(169) = (KAPHO2*0.41)
  RCONST(170) = (KAPHO2*0.15)
  RCONST(171) = (KAPNO)
  RCONST(172) = (KFPAN)
  RCONST(173) = (KRO2NO3*1.74)
  RCONST(174) = (1.00D-11*0.7*RO2)
  RCONST(175) = (1.00D-11*0.3*RO2)
  RCONST(176) = (3.01D-11)
  RCONST(177) = (J(41)+J(15))
  RCONST(178) = (KDEC)
  RCONST(179) = (2.66D-11)
  RCONST(180) = (J(15))
  RCONST(181) = (5.47D-11)
  RCONST(182) = (J(41)+J(15))
  RCONST(183) = (J(22))
  RCONST(184) = (KDEC*0.80)
  RCONST(185) = (KDEC*0.20)
  RCONST(186) = (5.47D-11)
  RCONST(187) = (J(34)+J(15))
  RCONST(188) = (4.45D-11)
  RCONST(189) = (J(22))
  RCONST(190) = (J(15))
  RCONST(191) = (6.65D-12)
  RCONST(192) = (J(22))
  RCONST(193) = (1.90D-12*EXP(190/TEMP))
  RCONST(194) = (1.30D-11)
  RCONST(195) = (J(41)+J(22))
  RCONST(196) = (2.88D-12)
  RCONST(197) = (J(53)+J(22))
  RCONST(198) = (4.20D+10*EXP(-3523/TEMP))
  RCONST(199) = (7.67D-12)
  RCONST(200) = (J(22))
  RCONST(201) = (KNO3AL*8.5)
  RCONST(202) = (2.64D-11)
  RCONST(203) = (J(15))
  RCONST(204) = (8.8D-12*EXP(-1320/TEMP)+1.7D-14*EXP(423/TEMP))
  RCONST(205) = (J(21))
  RCONST(206) = (1.19D-10)
  RCONST(207) = (KRO2HO2*0.820)
  RCONST(208) = (KRO2NO*0.278)
  RCONST(209) = (KRO2NO*0.722)
  RCONST(210) = (KRO2NO3)
  RCONST(211) = (2.50D-13*RO2*0.6)
  RCONST(212) = (2.50D-13*RO2*0.2)
  RCONST(213) = (2.50D-13*RO2*0.2)
  RCONST(214) = (KRO2HO2*0.914)
  RCONST(215) = (KRO2NO*0.050)
  RCONST(216) = (KRO2NO*0.950)
  RCONST(217) = (KRO2NO3)
  RCONST(218) = (6.70D-15*0.7*RO2)
  RCONST(219) = (6.70D-15*0.3*RO2)
  RCONST(220) = (5.94D-12)
  RCONST(221) = (J(41))
  RCONST(222) = (KDEC)
  RCONST(223) = (9.73D-12)
  RCONST(224) = (J(41)+J(22))
  RCONST(225) = (3.66D-12)
  RCONST(226) = (KBPAN)
  RCONST(227) = (KRO2HO2*0.914)
  RCONST(228) = (KRO2NO*0.125)
  RCONST(229) = (KRO2NO*0.875)
  RCONST(230) = (KRO2NO3)
  RCONST(231) = (6.70D-15*0.7*RO2)
  RCONST(232) = (6.70D-15*0.3*RO2)
  RCONST(233) = (KAPHO2*0.44)
  RCONST(234) = (KAPHO2*0.15)
  RCONST(235) = (KAPHO2*0.41)
  RCONST(236) = (KAPNO)
  RCONST(237) = (KFPAN)
  RCONST(238) = (KRO2NO3*1.74)
  RCONST(239) = (1.00D-11*RO2*0.7)
  RCONST(240) = (1.00D-11*RO2*0.3)
  RCONST(241) = (KAPHO2*0.41)
  RCONST(242) = (KAPHO2*0.44)
  RCONST(243) = (KAPHO2*0.15)
  RCONST(244) = (KAPNO)
  RCONST(245) = (KFPAN)
  RCONST(246) = (KRO2NO3*1.74)
  RCONST(247) = (1.00D-11*RO2*0.7)
  RCONST(248) = (1.00D-11*RO2*0.3)
  RCONST(249) = (KRO2HO2*0.890)
  RCONST(250) = (KRO2NO)
  RCONST(251) = (KRO2NO3)
  RCONST(252) = (1.30D-12*RO2)
  RCONST(253) = (KRO2HO2*0.890)
  RCONST(254) = (KRO2NO)
  RCONST(255) = (KRO2NO3)
  RCONST(256) = (6.70D-15*0.7*RO2)
  RCONST(257) = (6.70D-15*0.3*RO2)
  RCONST(258) = (KAPHO2*0.56)
  RCONST(259) = (KAPHO2*0.44)
  RCONST(260) = (KAPNO)
  RCONST(261) = (KFPAN)
  RCONST(262) = (KRO2NO3*1.74)
  RCONST(263) = (1.00D-11*RO2)
  RCONST(264) = (KRO2HO2*0.859)
  RCONST(265) = (KRO2NO)
  RCONST(266) = (KRO2NO3)
  RCONST(267) = (6.70D-15*RO2)
  RCONST(268) = (1.36D-13*EXP(1250/TEMP)*0.15)
  RCONST(269) = (1.36D-13*EXP(1250/TEMP)*0.85)
  RCONST(270) = (KRO2NO)
  RCONST(271) = (KRO2NO3)
  RCONST(272) = (2*(K298CH3O2*8.0D-12)**0.5*RO2*0.2)
  RCONST(273) = (2*(K298CH3O2*8.0D-12)**0.5*RO2*0.6)
  RCONST(274) = (2*(K298CH3O2*8.0D-12)**0.5*RO2*0.2)
  RCONST(275) = (KAPHO2*0.15)
  RCONST(276) = (KAPHO2*0.41)
  RCONST(277) = (KAPHO2*0.44)
  RCONST(278) = (7.5D-12*EXP(290/TEMP))
  RCONST(279) = (KFPAN)
  RCONST(280) = (4.0D-12)
  RCONST(281) = (1.00D-11*0.3*RO2)
  RCONST(282) = (1.00D-11*0.7*RO2)
  RCONST(283) = (KRO2HO2*0.820)
  RCONST(284) = (KRO2NO*0.042)
  RCONST(285) = (KRO2NO*0.958)
  RCONST(286) = (KRO2NO3)
  RCONST(287) = (9.20D-14*RO2*0.7)
  RCONST(288) = (9.20D-14*RO2*0.3)
  RCONST(289) = (1.27D-10)
  RCONST(290) = (J(41))
  RCONST(291) = (9.60D-11)
  RCONST(292) = (J(54))
  RCONST(293) = (KROSEC*O2)
  RCONST(294) = (1.09D-10)
  RCONST(295) = (2.75D-11)
  RCONST(296) = (J(41)+J(15))
  RCONST(297) = (2.25D-11)
  RCONST(298) = (J(55)+J(15))
  RCONST(299) = (KDEC)
  RCONST(300) = (2.41D-11)
  RCONST(301) = (J(22))
  RCONST(302) = (KRO2HO2*0.914)
  RCONST(303) = (KRO2NO)
  RCONST(304) = (KRO2NO3)
  RCONST(305) = (6.70D-15*RO2)
  RCONST(306) = (6.28D-11)
  RCONST(307) = (J(41)+J(35))
  RCONST(308) = (2.85D-11)
  RCONST(309) = (J(55)+J(35))
  RCONST(310) = (KDEC)
  RCONST(311) = (5.93D-11)
  RCONST(312) = (J(35))
  RCONST(313) = (KDEC*0.80)
  RCONST(314) = (KDEC*0.20)
  RCONST(315) = (2.69D-11)
  RCONST(316) = (J(15))
  RCONST(317) = (3.00D-11)
  RCONST(318) = (J(41)+J(15))
  RCONST(319) = (2.52D-11)
  RCONST(320) = (KBPAN)
  RCONST(321) = (9.16D-12)
  RCONST(322) = (J(41)+J(22))
  RCONST(323) = (5.70D-12)
  RCONST(324) = (J(22))
  RCONST(325) = (5.56D-12)
  RCONST(326) = (KBPAN)
  RCONST(327) = (2.36D-11)
  RCONST(328) = (J(41)+J(22))
  RCONST(329) = (4.20D+10*EXP(-3523/TEMP))
  RCONST(330) = (1.05D-11)
  RCONST(331) = (J(41)+J(22))
  RCONST(332) = (KDEC)
  RCONST(333) = (7.20D-12)
  RCONST(334) = (J(22))
  RCONST(335) = (1.02D-11)
  RCONST(336) = (J(41)+J(22))
  RCONST(337) = (6.60D-12)
  RCONST(338) = (KBPAN)
  RCONST(339) = (1.29D-11)
  RCONST(340) = (J(41)+J(22))
  RCONST(341) = (KDEC)
  RCONST(342) = (KDEC)
  RCONST(343) = (1.90D-12*EXP(190/TEMP))
  RCONST(344) = (8.39D-12)
  RCONST(345) = (J(22))
  RCONST(346) = (J(41))
  RCONST(347) = (1.6D-12*EXP(305/TEMP))
  RCONST(348) = (J(22))
  RCONST(349) = (J(34))
  RCONST(350) = (KNO3AL*2.4)
  RCONST(351) = (1.9D-12*EXP(575/TEMP))
  RCONST(352) = (8.00D-13)
  RCONST(353) = (3.70D-12)
  RCONST(354) = (J(41))
  RCONST(355) = (3D-14)
  RCONST(356) = (KBPAN)
  RCONST(357) = (7.06D-11)
  RCONST(358) = (J(41))
  RCONST(359) = (1.26D-11)
  RCONST(360) = (KDEC)
  RCONST(361) = (6.72D-11)
  RCONST(362) = (KNO3AL*5.5)
  RCONST(363) = (6.70D-11)
  RCONST(364) = (J(35))
  RCONST(365) = (KRO2HO2*0.914)
  RCONST(366) = (KRO2NO*0.125)
  RCONST(367) = (KRO2NO*0.875)
  RCONST(368) = (KRO2NO3)
  RCONST(369) = (6.70D-15*0.7*RO2)
  RCONST(370) = (6.70D-15*0.3*RO2)
  RCONST(371) = (8.03D-12)
  RCONST(372) = (J(41))
  RCONST(373) = (KDEC)
  RCONST(374) = (KRO2HO2*0.820)
  RCONST(375) = (KRO2NO*0.278)
  RCONST(376) = (KRO2NO*0.722)
  RCONST(377) = (KRO2NO3)
  RCONST(378) = (2.50D-13*0.6*RO2)
  RCONST(379) = (2.50D-13*0.2*RO2)
  RCONST(380) = (2.50D-13*0.2*RO2)
  RCONST(381) = (KAPHO2*0.41)
  RCONST(382) = (KAPHO2*0.44)
  RCONST(383) = (KAPHO2*0.15)
  RCONST(384) = (KAPNO)
  RCONST(385) = (KFPAN)
  RCONST(386) = (KRO2NO3*1.74)
  RCONST(387) = (1.00D-11*RO2*0.7)
  RCONST(388) = (1.00D-11*RO2*0.3)
  RCONST(389) = (KRO2HO2*0.859)
  RCONST(390) = (KRO2NO*0.104)
  RCONST(391) = (KRO2NO*0.896)
  RCONST(392) = (KRO2NO3)
  RCONST(393) = (6.70D-15*RO2*0.7)
  RCONST(394) = (6.70D-15*RO2*0.3)
  RCONST(395) = (2*KNO3AL*5.5)
  RCONST(396) = (1.33D-10)
  RCONST(397) = (J(15)*2)
  RCONST(398) = (KRO2HO2*0.890)
  RCONST(399) = (KRO2NO)
  RCONST(400) = (KRO2NO3)
  RCONST(401) = (6.70D-15*RO2)
  RCONST(402) = (KRO2HO2*0.890)
  RCONST(403) = (KRO2NO*0.118)
  RCONST(404) = (KRO2NO*0.882)
  RCONST(405) = (KRO2NO3)
  RCONST(406) = (6.70D-15*0.7*RO2)
  RCONST(407) = (6.70D-15*0.3*RO2)
  RCONST(408) = (KRO2HO2*0.859)
  RCONST(409) = (KRO2NO)
  RCONST(410) = (KRO2NO3)
  RCONST(411) = (6.70D-15*RO2)
  RCONST(412) = (KNO3AL*5.5)
  RCONST(413) = (8.92D-11*0.232)
  RCONST(414) = (8.92D-11*0.768)
  RCONST(415) = (J(15))
  RCONST(416) = (KAPHO2*0.56)
  RCONST(417) = (KAPHO2*0.44)
  RCONST(418) = (KAPNO)
  RCONST(419) = (KFPAN)
  RCONST(420) = (KRO2NO3*1.74)
  RCONST(421) = (1.00D-11*RO2)
  RCONST(422) = (KAPHO2*0.44)
  RCONST(423) = (KAPHO2*0.56)
  RCONST(424) = (KAPNO)
  RCONST(425) = (KFPAN)
  RCONST(426) = (KRO2NO3*1.74)
  RCONST(427) = (1.00D-11*RO2)
  RCONST(428) = (8.01D-11)
  RCONST(429) = (J(41)+J(15))
  RCONST(430) = (7.03D-11)
  RCONST(431) = (J(55)+J(15))
  RCONST(432) = (KDEC)
  RCONST(433) = (7.66D-11)
  RCONST(434) = (J(15))
  RCONST(435) = (KRO2HO2*0.820)
  RCONST(436) = (KRO2NO)
  RCONST(437) = (KRO2NO3)
  RCONST(438) = (2.50D-13*RO2)
  RCONST(439) = (2.00D-10)
  RCONST(440) = (J(41)+J(35))
  RCONST(441) = (2.23D-11)
  RCONST(442) = (J(54)+J(35))
  RCONST(443) = (KROSEC*O2)
  RCONST(444) = (1.26D-10)
  RCONST(445) = (J(35))
  RCONST(446) = (1.04D-11)
  RCONST(447) = (J(41))
  RCONST(448) = (KRO2HO2*0.859)
  RCONST(449) = (KRO2NO*0.138)
  RCONST(450) = (KRO2NO*0.862)
  RCONST(451) = (KRO2NO3)
  RCONST(452) = (1.30D-12*RO2*0.2)
  RCONST(453) = (1.30D-12*RO2*0.6)
  RCONST(454) = (1.30D-12*RO2*0.2)
  RCONST(455) = (7.29D-12)
  RCONST(456) = (6.77D-12)
  RCONST(457) = (KBPAN)
  RCONST(458) = (3.61D-11)
  RCONST(459) = (J(41)+J(15))
  RCONST(460) = (2.56D-11)
  RCONST(461) = (J(55)+J(15))
  RCONST(462) = (2.70D+14*EXP(-6643/TEMP))
  RCONST(463) = (2.86D-11)
  RCONST(464) = (J(15))
  RCONST(465) = (KRO2HO2*0.625)
  RCONST(466) = (KRO2NO)
  RCONST(467) = (KRO2NO3)
  RCONST(468) = (2.00D-12*RO2)
  RCONST(469) = (1.29D-11)
  RCONST(470) = (J(41)+J(22))
  RCONST(471) = (KDEC)
  RCONST(472) = (2.05D-11)
  RCONST(473) = (J(41)+J(35))
  RCONST(474) = (5.37D-12)
  RCONST(475) = (J(55)+J(35))
  RCONST(476) = (KDEC)
  RCONST(477) = (1.69D-11)
  RCONST(478) = (J(35))
  RCONST(479) = (3.45D-11)
  RCONST(480) = (J(41)+J(15))
  RCONST(481) = (KDEC)
  RCONST(482) = (KAPHO2*0.44)
  RCONST(483) = (KAPHO2*0.15)
  RCONST(484) = (KAPHO2*0.41)
  RCONST(485) = (KAPNO)
  RCONST(486) = (KFPAN)
  RCONST(487) = (KRO2NO3*1.74)
  RCONST(488) = (1.00D-11*RO2*0.7)
  RCONST(489) = (1.00D-11*RO2*0.3)
  RCONST(490) = (KRO2HO2*0.770)
  RCONST(491) = (KRO2NO)
  RCONST(492) = (KRO2NO3)
  RCONST(493) = (2.00D-12*RO2*0.2)
  RCONST(494) = (2.00D-12*RO2*0.6)
  RCONST(495) = (2.00D-12*RO2*0.2)
  RCONST(496) = (4.75D-12)
  RCONST(497) = (J(41)+J(35))
  RCONST(498) = (KRO2HO2*0.770)
  RCONST(499) = (KRO2NO)
  RCONST(500) = (KRO2NO3)
  RCONST(501) = (2.00D-12*RO2)
  RCONST(502) = (8.83D-13)
  RCONST(503) = (KBPAN)
  RCONST(504) = (7.55D-11)
  RCONST(505) = (J(41)+J(22)+J(15))
  RCONST(506) = (7.19D-11)
  RCONST(507) = (KBPAN)
  RCONST(508) = (KRO2HO2*0.820)
  RCONST(509) = (KRO2NO)
  RCONST(510) = (KRO2NO3)
  RCONST(511) = (8.80D-13*0.6*RO2)
  RCONST(512) = (8.80D-13*0.2*RO2)
  RCONST(513) = (8.80D-13*0.2*RO2)
  RCONST(514) = (3.25D-11)
  RCONST(515) = (J(41))
  RCONST(516) = (4.00D+04)
  RCONST(517) = (KROSEC*O2)
  RCONST(518) = (1.70D-11)
  RCONST(519) = (J(41))
  RCONST(520) = (3.29D-12)
  RCONST(521) = (J(53))
  RCONST(522) = (KDEC)
  RCONST(523) = (KNO3AL*8.5)
  RCONST(524) = (2.63D-11)
  RCONST(525) = (J(15))
  RCONST(526) = (7.89D-12)
  RCONST(527) = (KRO2HO2*0.914)
  RCONST(528) = (KRO2NO*0.104)
  RCONST(529) = (KRO2NO*0.896)
  RCONST(530) = (KRO2NO3)
  RCONST(531) = (6.70D-15*RO2*0.7)
  RCONST(532) = (6.70D-15*RO2*0.3)
  RCONST(533) = (8.33D-11)
  RCONST(534) = (J(41)+J(22)+J(15))
  RCONST(535) = (KDEC)
  RCONST(536) = (KRO2HO2*0.890)
  RCONST(537) = (KRO2NO)
  RCONST(538) = (KRO2NO3)
  RCONST(539) = (6.70D-15*RO2)
  RCONST(540) = (3.22D-12)
  RCONST(541) = (J(22))
  RCONST(542) = (KRO2HO2*0.770)
  RCONST(543) = (KRO2NO*0.098)
  RCONST(544) = (KRO2NO*0.902)
  RCONST(545) = (KRO2NO3)
  RCONST(546) = (8.80D-13*0.2*RO2)
  RCONST(547) = (8.80D-13*0.6*RO2)
  RCONST(548) = (8.80D-13*0.2*RO2)
  RCONST(549) = (KRO2HO2*0.706)
  RCONST(550) = (KRO2NO)
  RCONST(551) = (KRO2NO3)
  RCONST(552) = (8.80D-13*RO2)
  RCONST(553) = (2.39D-11)
  RCONST(554) = (J(22)*2)
  RCONST(555) = (2.70D-11)
  RCONST(556) = (J(41)+J(22)*2)
  RCONST(557) = (2.29D-11)
  RCONST(558) = (KBPAN)
  RCONST(559) = (3.23D-11)
  RCONST(560) = (J(41)+J(22)*2)
  RCONST(561) = (KDEC)
  RCONST(562) = (3.55D-11)
  RCONST(563) = (J(34))
  RCONST(564) = (2.54D-11*0.890)
  RCONST(565) = (2.54D-11*0.110)
  RCONST(566) = (J(22)*2)
  RCONST(567) = (1.01D-11)
  RCONST(568) = (J(41)+J(35))
  RCONST(569) = (KDEC)
  RCONST(570) = (KNO3AL*5.5)
  RCONST(571) = (1.33D-11)
  RCONST(572) = (J(34))
  RCONST(573) = (2*KNO3AL*4.0)
  RCONST(574) = (3.39D-11)
  RCONST(575) = (J(15))
  RCONST(576) = (J(34))
  RCONST(577) = (1.20D-10)
  RCONST(578) = (J(41)+J(15))
  RCONST(579) = (KDEC)
  RCONST(580) = (1.25D-12)
  RCONST(581) = (J(55))
  RCONST(582) = (KRO2HO2*0.859)
  RCONST(583) = (KRO2NO)
  RCONST(584) = (KRO2NO3)
  RCONST(585) = (9.20D-14*RO2*0.7)
  RCONST(586) = (9.20D-14*RO2*0.3)
  RCONST(587) = (KAPHO2*0.41)
  RCONST(588) = (KAPHO2*0.44)
  RCONST(589) = (KAPHO2*0.15)
  RCONST(590) = (KAPNO)
  RCONST(591) = (KFPAN)
  RCONST(592) = (KRO2NO3*1.74)
  RCONST(593) = (1.00D-11*RO2*0.7)
  RCONST(594) = (1.00D-11*RO2*0.3)
  RCONST(595) = (KRO2HO2*0.820)
  RCONST(596) = (KRO2NO)
  RCONST(597) = (KRO2NO3)
  RCONST(598) = (1.30D-12*RO2)
  RCONST(599) = (8.35D-11)
  RCONST(600) = (J(41)+J(15))
  RCONST(601) = (4.96D-11)
  RCONST(602) = (J(55)+J(15))
  RCONST(603) = (2.70D+14*EXP(-6643/TEMP))
  RCONST(604) = (8.00D-11)
  RCONST(605) = (J(15))
  RCONST(606) = (KAPHO2*0.15)
  RCONST(607) = (KAPHO2*0.41)
  RCONST(608) = (KAPHO2*0.44)
  RCONST(609) = (KAPNO)
  RCONST(610) = (KFPAN)
  RCONST(611) = (KRO2NO3*1.74)
  RCONST(612) = (1.00D-11*0.3*RO2)
  RCONST(613) = (1.00D-11*0.7*RO2)
  RCONST(614) = (1.51D-11)
  RCONST(615) = (J(41)+J(22))
  RCONST(616) = (KDEC)
  RCONST(617) = (KRO2HO2*0.625)
  RCONST(618) = (KRO2NO)
  RCONST(619) = (KRO2NO3)
  RCONST(620) = (2.00D-12*0.6*RO2)
  RCONST(621) = (2.00D-12*0.2*RO2)
  RCONST(622) = (2.00D-12*0.2*RO2)
  RCONST(623) = (KAPHO2*0.44)
  RCONST(624) = (KAPHO2*0.15)
  RCONST(625) = (KAPHO2*0.41)
  RCONST(626) = (KAPNO)
  RCONST(627) = (KFPAN)
  RCONST(628) = (KRO2NO3*1.74)
  RCONST(629) = (1.00D-11*0.7*RO2)
  RCONST(630) = (1.00D-11*0.3*RO2)
  RCONST(631) = (8.69D-11)
  RCONST(632) = (J(41)+J(35))
  RCONST(633) = (71.11D-12)
  RCONST(634) = (J(35))
  RCONST(635) = (KDEC)
  RCONST(636) = (3.78D-11)
  RCONST(637) = (J(35))
  RCONST(638) = (7.49D-11)
  RCONST(639) = (J(41)+J(15))
  RCONST(640) = (KDEC)
  RCONST(641) = (KAPHO2*0.15)
  RCONST(642) = (KAPHO2*0.41)
  RCONST(643) = (KAPHO2*0.44)
  RCONST(644) = (KAPNO)
  RCONST(645) = (KFPAN)
  RCONST(646) = (KRO2NO3*1.74)
  RCONST(647) = (1.00D-11*RO2*0.3)
  RCONST(648) = (1.00D-11*RO2*0.7)
  RCONST(649) = (KRO2HO2*0.625)
  RCONST(650) = (KRO2NO*0.017)
  RCONST(651) = (KRO2NO*0.983)
  RCONST(652) = (KRO2NO3)
  RCONST(653) = (2.00D-12*0.2*RO2)
  RCONST(654) = (2.00D-12*0.6*RO2)
  RCONST(655) = (2.00D-12*0.2*RO2)
  RCONST(656) = (KAPHO2*0.44)
  RCONST(657) = (KAPHO2*0.56)
  RCONST(658) = (KAPNO)
  RCONST(659) = (KFPAN)
  RCONST(660) = (KRO2NO3*1.74)
  RCONST(661) = (1.00D-11*RO2)
  RCONST(662) = (KAPHO2*0.56)
  RCONST(663) = (KAPHO2*0.44)
  RCONST(664) = (KAPNO)
  RCONST(665) = (KFPAN)
  RCONST(666) = (KRO2NO3*1.74)
  RCONST(667) = (1.00D-11*RO2)
  RCONST(668) = (KRO2HO2*0.520)
  RCONST(669) = (KRO2NO)
  RCONST(670) = (KRO2NO3)
  RCONST(671) = (2.00D-12*RO2)
  RCONST(672) = (KRO2HO2*0.820)
  RCONST(673) = (KRO2NO)
  RCONST(674) = (KRO2NO3)
  RCONST(675) = (8.80D-13*RO2)
  RCONST(676) = (1.09D-11)
  RCONST(677) = (J(41))
  RCONST(678) = (KDEC)
  RCONST(679) = (7.42D-12)
  RCONST(680) = (9.65D-12)
  RCONST(681) = (J(41))
  RCONST(682) = (6.57D-12)
  RCONST(683) = (2.96D-12)
  RCONST(684) = (KBPAN)
  RCONST(685) = (1.27D-11)
  RCONST(686) = (J(41))
  RCONST(687) = (KDEC)
  RCONST(688) = (KRO2HO2*0.706)
  RCONST(689) = (KRO2NO*0.129)
  RCONST(690) = (KRO2NO*0.871)
  RCONST(691) = (KRO2NO3)
  RCONST(692) = (2.50D-13*RO2*0.6)
  RCONST(693) = (2.50D-13*RO2*0.2)
  RCONST(694) = (2.50D-13*RO2*0.2)
  RCONST(695) = (J(15))
  RCONST(696) = (2.14D-11)
  RCONST(697) = (J(41)+J(15))
  RCONST(698) = (2.49D-11)
  RCONST(699) = (KRO2HO2*0.387)
  RCONST(700) = (KRO2NO)
  RCONST(701) = (KRO2NO3)
  RCONST(702) = (2.00D-12*0.2*RO2)
  RCONST(703) = (2.00D-12*0.6*RO2)
  RCONST(704) = (2.00D-12*0.2*RO2)
  RCONST(705) = (KBPAN)
  RCONST(706) = (2.10D-11)
  RCONST(707) = (KRO2HO2*0.770)
  RCONST(708) = (KRO2NO)
  RCONST(709) = (KRO2NO3)
  RCONST(710) = (8.80D-13*RO2)
  RCONST(711) = (J(41)+J(35))
  RCONST(712) = (1.90D-12*EXP(190/TEMP))
  RCONST(713) = (5.99D-12)
  RCONST(714) = (KDEC)
  RCONST(715) = (J(35))
  RCONST(716) = (2.69D-12)
  RCONST(717) = (J(34))
  RCONST(718) = (J(35))
  RCONST(719) = (KNO3AL*4.0)
  RCONST(720) = (1.23D-11)
  RCONST(721) = (2.73D-12)
  RCONST(722) = (6.19D-12)
  RCONST(723) = (J(41))
  RCONST(724) = (1.12D-12)
  RCONST(725) = (KBPAN)
  RCONST(726) = (J(15))
  RCONST(727) = (J(35))
  RCONST(728) = (KNO3AL*5.5)
  RCONST(729) = (6.65D-11)
  RCONST(730) = (J(15)*2)
  RCONST(731) = (2*KNO3AL*2.4)
  RCONST(732) = (4.29D-11)
  RCONST(733) = (2.34D-11)
  RCONST(734) = (J(22))
  RCONST(735) = (2.65D-11)
  RCONST(736) = (J(41)+J(22))
  RCONST(737) = (7.60D-12)
  RCONST(738) = (KBPAN)
  RCONST(739) = (J(41))
  RCONST(740) = (5.77D-11)
  RCONST(741) = (J(56)*0.91)
  RCONST(742) = (2.23D-12)
  RCONST(743) = (KDEC)
  RCONST(744) = (J(15))
  RCONST(745) = (KNO3AL*4.0)
  RCONST(746) = (2.45D-11)
  RCONST(747) = (J(22))
  RCONST(748) = (1.88D-11)
  RCONST(749) = (J(41)+J(15))
  RCONST(750) = (4.23D-12)
  RCONST(751) = (KBPAN)
  RCONST(752) = (3.12D-13)
  RCONST(753) = (1.63D-11)
  RCONST(754) = (J(41)+J(34))
  RCONST(755) = (1.27D-11)
  RCONST(756) = (KBPAN)
  RCONST(757) = (2.41D-11)
  RCONST(758) = (J(41)+J(34))
  RCONST(759) = (KDEC)
  RCONST(760) = (1.85D-11)
  RCONST(761) = (J(41))
  RCONST(762) = (KDEC)
  RCONST(763) = (KRO2HO2*0.859)
  RCONST(764) = (KRO2NO*0.104)
  RCONST(765) = (KRO2NO*0.896)
  RCONST(766) = (KRO2NO3)
  RCONST(767) = (6.70D-15*RO2*0.7)
  RCONST(768) = (6.70D-15*RO2*0.3)
  RCONST(769) = (KRO2HO2*0.820)
  RCONST(770) = (KRO2NO)
  RCONST(771) = (KRO2NO3)
  RCONST(772) = (6.70D-15*RO2)
  RCONST(773) = (1.10D-10)
  RCONST(774) = (J(41)+J(15)*2)
  RCONST(775) = (4.33D-11)
  RCONST(776) = (J(54)+J(15)*2)
  RCONST(777) = (1.80D-14*EXP(-260/TEMP)*O2)
  RCONST(778) = (6.99D-11)
  RCONST(779) = (J(15)*2)
  RCONST(780) = (2.91D-11)
  RCONST(781) = (1.90D-12*EXP(190/TEMP))
  RCONST(782) = (J(41))
  RCONST(783) = (J(15))
  RCONST(784) = (KDEC)
  RCONST(785) = (J(31))
  RCONST(786) = (J(33))
  RCONST(787) = (J(32))
  RCONST(788) = (KNO3AL)
  RCONST(789) = (3.1D-12*EXP(340/TEMP))
  RCONST(790) = (KNO3AL)
  RCONST(791) = (1.00D-11*0.200)
  RCONST(792) = (1.00D-11*0.800)
  RCONST(793) = (J(15))
  RCONST(794) = (1.00D-10)
  RCONST(795) = (J(41)+J(22))
  RCONST(796) = (KDEC)
  RCONST(797) = (7.00D11*EXP(-3160/TEMP)+5.00D-12*O2)
  RCONST(798) = (5.00D-12*O2*3.2*(1-EXP(-550/TEMP)))
  RCONST(799) = (5.00D-12*O2*3.2*EXP(-550/TEMP))
  RCONST(800) = (KAPHO2*0.56)
  RCONST(801) = (KAPHO2*0.44)
  RCONST(802) = (KAPNO)
  RCONST(803) = (KFPAN)
  RCONST(804) = (KRO2NO3*1.74)
  RCONST(805) = (1.00D-11*RO2)
  RCONST(806) = (5.77D-11)
  RCONST(807) = (J(15)*2)
  RCONST(808) = (KAPHO2*0.44)
  RCONST(809) = (KAPHO2*0.56)
  RCONST(810) = (KAPNO)
  RCONST(811) = (KFPAN)
  RCONST(812) = (KRO2NO3*1.74)
  RCONST(813) = (1.00D-11*RO2)
  RCONST(814) = (1.86D-11)
  RCONST(815) = (J(41)+J(34))
  RCONST(816) = (7.82D-12)
  RCONST(817) = (J(55)+J(34))
  RCONST(818) = (KDEC)
  RCONST(819) = (1.75D-11)
  RCONST(820) = (J(34))
  RCONST(821) = (3.31D-11)
  RCONST(822) = (J(41))
  RCONST(823) = (KDEC)
  RCONST(824) = (KNO3AL*5.5)
  RCONST(825) = (2.37D-11)
  RCONST(826) = (J(15))
  RCONST(827) = (J(35))
  RCONST(828) = (KAPHO2*0.15)
  RCONST(829) = (KAPHO2*0.41)
  RCONST(830) = (KAPHO2*0.44)
  RCONST(831) = (KAPNO)
  RCONST(832) = (KFPAN)
  RCONST(833) = (KRO2NO3*1.74)
  RCONST(834) = (1.00D-11*0.7*RO2)
  RCONST(835) = (1.00D-11*0.3*RO2)
  RCONST(836) = (J(22))
  RCONST(837) = (J(41))
  RCONST(838) = (7.34D-12)
  RCONST(839) = (KBPAN)
  RCONST(840) = (3.74D-12)
  RCONST(841) = (1.68D-11)
  RCONST(842) = (J(41))
  RCONST(843) = (1.32D-11)
  RCONST(844) = (KBPAN)
  RCONST(845) = (6.69D-11)
  RCONST(846) = (J(34)+J(15))
  RCONST(847) = (KRO2HO2*0.706)
  RCONST(848) = (KRO2NO)
  RCONST(849) = (KRO2NO3)
  RCONST(850) = (8.8D-13*RO2)
  RCONST(851) = (KRO2HO2*0.625)
  RCONST(852) = (KRO2NO)
  RCONST(853) = (KRO2NO3)
  RCONST(854) = (8.80D-13*RO2)
  RCONST(855) = (KAPHO2*0.44)
  RCONST(856) = (KAPHO2*0.56)
  RCONST(857) = (KAPNO)
  RCONST(858) = (KFPAN)
  RCONST(859) = (KRO2NO3*1.74)
  RCONST(860) = (1.00D-11*RO2)
  RCONST(861) = (KRO2HO2*0.625)
  RCONST(862) = (KRO2NO)
  RCONST(863) = (KRO2NO3)
  RCONST(864) = (2.00D-12*RO2)
  RCONST(865) = (J(34))
  RCONST(866) = (1.23D-11)
  RCONST(867) = (J(41)+J(15))
  RCONST(868) = (1.58D-11)
  RCONST(869) = (J(22)+J(41))
  RCONST(870) = (3.38D-11)
  RCONST(871) = (KDEC)
  RCONST(872) = (7.46D-11)
  RCONST(873) = (J(41))
  RCONST(874) = (KDEC)
  RCONST(875) = (6.55D-12)
  RCONST(876) = (J(41)+J(35))
  RCONST(877) = (2.92D-12)
  RCONST(878) = (KBPAN)
  RCONST(879) = (9.61D-12)
  RCONST(880) = (J(41)+J(35))
  RCONST(881) = (KDEC)
  RCONST(882) = (1.44D-11)
  RCONST(883) = (J(34)+J(35))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE second_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE second_Rates

