! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : second_Global.f90
! Time                 : Thu Oct 11 16:31:07 2018
! Working directory    : /home/local/pzzhou/Documents/Research/Paper/Myself/2018/PRAM-Carlton/pram_kpp
! Equation file        : second.kpp
! Output root filename : second
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE second_Global

  USE second_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
      EQUIVALENCE( C(1),VAR(1) )
      EQUIVALENCE( C(2170),FIX(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR

! INLINED global variable declarations

 REAL(dp)::M, N2, O2, RO2, H2O
 
  ! variables
  INTEGER, PARAMETER :: NPHOT = 71
  REAL(kind=dp) :: RH,PRESS,RES1,RES2
  REAL(kind=dp) :: J(NPHOT)
  REAL(kind=dp) :: KMT01,KMT02,KMT03,KMT04,KMT05,KMT06,KMT07,KMT08,KMT09,KMT10
  REAL(kind=dp) :: KMT11,KMT12,KMT13,KMT14,KMT15,KMT16,KMT17,KMT18
  REAL(kind=dp) :: KFPAN,KBPAN,KRO2NO,KRO2HO2,KAPHO2,KAPNO,KRO2NO3,KNO3AL
  REAL(kind=dp) :: KDEC,KROPRIM,KROSEC,KCH3O2,K298CH3O2,K_CI,K_h2so4
  REAL(kind=dp) :: KMT34,KMT35,KMT36,KMT37,KMT38,KMT39,KMT40,KMT41,KMT42
  REAL(kind=dp) :: K16ISOM1,K15ISOM1,K14ISOM1,KBPPN
  REAL(kind=dp) :: F1, F10, F12, F13, F14, F15, F16, F17, F2, F3, F4, F7, F8, F9
  REAL(kind=dp) :: FC, FC1, FC10, FC12, FC13, FC14, FC15, FC16, FC17, FC2, FC3
  REAL(kind=dp) :: FC4, FC7, FC8, FC9, FCC, FCD, FCPPN, FD, FPPN, K1, K10, K100
  REAL(kind=dp) :: K10I, K120, K12I, K130, K13I, K140, K14I, K150, K15I, K160
  REAL(kind=dp) :: K16I, K170, K17I, K1I, K2, K20, K2I, K3, K30, K3I, K4, K40
  REAL(kind=dp) :: K4I, K70, K7I, K80, K8I, K90, K9I, KC0, KCI, KD0, KDI, KPPN0
  REAL(kind=dp) :: KPPNI, KR1, KR10, KR12, KR13, KR14, KR15, KR16, KR17, KR2
  REAL(kind=dp) :: KR3, KR4, KR7 , KR8, KR9, KRC, KRD, KRPPN, NC, NC1, NC10
  REAL(kind=dp) :: NC12, NC13, NC14, NC15, NC16, NC17, NC2, NC3, NC4, NC7
  REAL(kind=dp) :: NC8, NC9, NCD, NCPPN


! INLINED global variable declarations


END MODULE second_Global

