# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSD.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(9, 9, 961, 728))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainFrame.setObjectName("MainFrame")
        self.tabWidget = QtWidgets.QTabWidget(self.MainFrame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 960, 670))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(700, 10, 241, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.names_sel = QtWidgets.QListWidget(self.frame)
        self.names_sel.setGeometry(QtCore.QRect(10, 30, 221, 560))
        self.names_sel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.names_sel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.names_sel.setProperty("showDropIndicator", False)
        self.names_sel.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.names_sel.setBatchSize(100)
        self.names_sel.setObjectName("names_sel")
        item = QtWidgets.QListWidgetItem()
        self.names_sel.addItem(item)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 210, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(460, 20, 221, 160))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(10, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 30, 139, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_che = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_che.setEnabled(True)
        self.checkBox_che.setChecked(True)
        self.checkBox_che.setObjectName("checkBox_che")
        self.verticalLayout.addWidget(self.checkBox_che)
        self.checkBox_acd = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_acd.setChecked(True)
        self.checkBox_acd.setObjectName("checkBox_acd")
        self.verticalLayout.addWidget(self.checkBox_acd)
        self.checkBox_aer = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_aer.setEnabled(True)
        self.checkBox_aer.setChecked(True)
        self.checkBox_aer.setObjectName("checkBox_aer")
        self.verticalLayout.addWidget(self.checkBox_aer)
        self.layoutWidget.raise_()
        self.label_43.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 441, 291))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 30, 410, 250))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.runtime = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.runtime.setFont(font)
        self.runtime.setMaximum(999.99)
        self.runtime.setProperty("value", 24.0)
        self.runtime.setObjectName("runtime")
        self.gridLayout_2.addWidget(self.runtime, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.case_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.case_name.setFont(font)
        self.case_name.setObjectName("case_name")
        self.gridLayout_2.addWidget(self.case_name, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.run_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.run_name.setFont(font)
        self.run_name.setObjectName("run_name")
        self.gridLayout_2.addWidget(self.run_name, 2, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setDate(QtCore.QDate(2025, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 3, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 3, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.description = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.description.setFont(font)
        self.description.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description.setMaximumBlockCount(0)
        self.description.setObjectName("description")
        self.gridLayout_2.addWidget(self.description, 4, 1, 2, 4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(460, 190, 221, 280))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton.setGeometry(QtCore.QRect(420, 140, 27, 21))
        self.toolButton.setObjectName("toolButton")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_4.setEnabled(True)
        self.frame_4.setGeometry(QtCore.QRect(0, 30, 211, 240))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 190, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 0, 0, 1, 1)
        self.n_bins_particle = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.n_bins_particle.setFont(font)
        self.n_bins_particle.setMinimum(1)
        self.n_bins_particle.setMaximum(1000)
        self.n_bins_particle.setProperty("value", 100)
        self.n_bins_particle.setObjectName("n_bins_particle")
        self.gridLayout_8.addWidget(self.n_bins_particle, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 1, 0, 1, 1)
        self.psd_mode = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.psd_mode.setFont(font)
        self.psd_mode.setObjectName("psd_mode")
        self.psd_mode.addItem("")
        self.psd_mode.addItem("")
        self.psd_mode.addItem("")
        self.gridLayout_8.addWidget(self.psd_mode, 2, 0, 1, 2)
        self.use_dmps = QtWidgets.QCheckBox(self.layoutWidget2)
        self.use_dmps.setObjectName("use_dmps")
        self.gridLayout_8.addWidget(self.use_dmps, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 99, 190, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 3)
        self.min_particle_diam = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.min_particle_diam.setFont(font)
        self.min_particle_diam.setObjectName("min_particle_diam")
        self.gridLayout_12.addWidget(self.min_particle_diam, 1, 0, 1, 2)
        self.max_particle_diam = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.max_particle_diam.setFont(font)
        self.max_particle_diam.setObjectName("max_particle_diam")
        self.gridLayout_12.addWidget(self.max_particle_diam, 1, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 2, 0, 1, 3)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 4, 0, 1, 3)
        self.dmps_read_in_time = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dmps_read_in_time.setFont(font)
        self.dmps_read_in_time.setMaximum(999.99)
        self.dmps_read_in_time.setProperty("value", 2.0)
        self.dmps_read_in_time.setObjectName("dmps_read_in_time")
        self.gridLayout_12.addWidget(self.dmps_read_in_time, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 3, 1, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 330, 441, 280))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 411, 251))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_52.setObjectName("label_52")
        self.gridLayout_9.addWidget(self.label_52, 0, 0, 1, 4)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_9.addWidget(self.label_46, 1, 0, 1, 2)
        self.case_dir = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.case_dir.setFont(font)
        self.case_dir.setObjectName("case_dir")
        self.gridLayout_9.addWidget(self.case_dir, 1, 2, 1, 1)
        self.browseCommonIn = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseCommonIn.setFont(font)
        self.browseCommonIn.setObjectName("browseCommonIn")
        self.gridLayout_9.addWidget(self.browseCommonIn, 1, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_9.addWidget(self.label_47, 2, 0, 1, 2)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_9.addWidget(self.lineEdit_13, 2, 2, 1, 1)
        self.browseCommonOut = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseCommonOut.setFont(font)
        self.browseCommonOut.setObjectName("browseCommonOut")
        self.gridLayout_9.addWidget(self.browseCommonOut, 2, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_9.addWidget(self.label_44, 4, 0, 1, 1)
        self.env_file = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.env_file.setFont(font)
        self.env_file.setObjectName("env_file")
        self.gridLayout_9.addWidget(self.env_file, 4, 1, 1, 2)
        self.browseEnv = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseEnv.setFont(font)
        self.browseEnv.setObjectName("browseEnv")
        self.gridLayout_9.addWidget(self.browseEnv, 4, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_9.addWidget(self.label_45, 5, 0, 1, 1)
        self.mcm_file = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mcm_file.setFont(font)
        self.mcm_file.setObjectName("mcm_file")
        self.gridLayout_9.addWidget(self.mcm_file, 5, 1, 1, 2)
        self.browseMcm = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseMcm.setFont(font)
        self.browseMcm.setObjectName("browseMcm")
        self.gridLayout_9.addWidget(self.browseMcm, 5, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 6, 0, 1, 1)
        self.dmps_file = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dmps_file.setFont(font)
        self.dmps_file.setObjectName("dmps_file")
        self.gridLayout_9.addWidget(self.dmps_file, 6, 1, 1, 2)
        self.browsePar = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browsePar.setFont(font)
        self.browsePar.setObjectName("browsePar")
        self.gridLayout_9.addWidget(self.browsePar, 6, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_9.addWidget(self.label_53, 7, 0, 1, 1)
        self.extra_particles = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.extra_particles.setFont(font)
        self.extra_particles.setObjectName("extra_particles")
        self.gridLayout_9.addWidget(self.extra_particles, 7, 1, 1, 2)
        self.browseXtr = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.browseXtr.setFont(font)
        self.browseXtr.setObjectName("browseXtr")
        self.gridLayout_9.addWidget(self.browseXtr, 7, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 3, 0, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(460, 480, 220, 130))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 193, 90))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 2)
        self.print_interval = QtWidgets.QSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.print_interval.setFont(font)
        self.print_interval.setMinimum(0)
        self.print_interval.setMaximum(1000000)
        self.print_interval.setSingleStep(100)
        self.print_interval.setProperty("value", 600)
        self.print_interval.setObjectName("print_interval")
        self.gridLayout_5.addWidget(self.print_interval, 0, 2, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 2)
        self.fsave_interval = QtWidgets.QSpinBox(self.layoutWidget5)
        self.fsave_interval.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsave_interval.setFont(font)
        self.fsave_interval.setMaximum(1000000)
        self.fsave_interval.setSingleStep(100)
        self.fsave_interval.setProperty("value", 300)
        self.fsave_interval.setObjectName("fsave_interval")
        self.gridLayout_5.addWidget(self.fsave_interval, 1, 2, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 2, 0, 1, 1)
        self.fsave_division = QtWidgets.QSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fsave_division.setFont(font)
        self.fsave_division.setMaximum(1000000)
        self.fsave_division.setObjectName("fsave_division")
        self.gridLayout_5.addWidget(self.fsave_division, 2, 1, 1, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(700, 10, 241, 600))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.namesdat = QtWidgets.QListWidget(self.frame_2)
        self.namesdat.setGeometry(QtCore.QRect(10, 30, 221, 560))
        self.namesdat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.namesdat.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.namesdat.setBatchSize(100)
        self.namesdat.setObjectName("namesdat")
        self.label_54 = QtWidgets.QLabel(self.frame_2)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 220, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.butMoveToSelVars = QtWidgets.QPushButton(self.tab_3)
        self.butMoveToSelVars.setGeometry(QtCore.QRect(610, 230, 70, 40))
        self.butMoveToSelVars.setObjectName("butMoveToSelVars")
        self.selected_vars = QtWidgets.QTableWidget(self.tab_3)
        self.selected_vars.setGeometry(QtCore.QRect(10, 29, 590, 570))
        self.selected_vars.setObjectName("selected_vars")
        self.selected_vars.setColumnCount(8)
        self.selected_vars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.selected_vars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(7, item)
        self.butRemoveSelVars = QtWidgets.QPushButton(self.tab_3)
        self.butRemoveSelVars.setGeometry(QtCore.QRect(610, 370, 70, 40))
        self.butRemoveSelVars.setObjectName("butRemoveSelVars")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(610, 180, 70, 40))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setWordWrap(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(610, 330, 70, 40))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.markAll = QtWidgets.QPushButton(self.tab_3)
        self.markAll.setGeometry(QtCore.QRect(530, 605, 70, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.markAll.setPalette(palette)
        self.markAll.setFlat(True)
        self.markAll.setObjectName("markAll")
        self.invertMarks = QtWidgets.QPushButton(self.tab_3)
        self.invertMarks.setGeometry(QtCore.QRect(370, 605, 120, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.invertMarks.setPalette(palette)
        self.invertMarks.setFlat(True)
        self.invertMarks.setObjectName("invertMarks")
        self.loadFixed = QtWidgets.QPushButton(self.tab_3)
        self.loadFixed.setGeometry(QtCore.QRect(10, 605, 180, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.loadFixed.setPalette(palette)
        self.loadFixed.setFlat(True)
        self.loadFixed.setObjectName("loadFixed")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.PLOTHERE = QtWidgets.QFrame(self.tab_4)
        self.PLOTHERE.setGeometry(QtCore.QRect(10, 10, 680, 611))
        self.PLOTHERE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PLOTHERE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PLOTHERE.setObjectName("PLOTHERE")
        self.PLOT = PlotWidget(self.PLOTHERE)
        self.PLOT.setGeometry(QtCore.QRect(10, 10, 660, 420))
        self.PLOT.setObjectName("PLOT")
        self.fLin = QtWidgets.QRadioButton(self.PLOTHERE)
        self.fLin.setGeometry(QtCore.QRect(420, 440, 61, 20))
        self.fLin.setChecked(True)
        self.fLin.setObjectName("fLin")
        self.fLog = QtWidgets.QRadioButton(self.PLOTHERE)
        self.fLog.setGeometry(QtCore.QRect(490, 440, 101, 20))
        self.fLog.setObjectName("fLog")
        self.layoutWidget6 = QtWidgets.QWidget(self.PLOTHERE)
        self.layoutWidget6.setGeometry(QtCore.QRect(50, 470, 580, 130))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 2, 0, 1, 1)
        self.fFreq = QtWidgets.QSlider(self.layoutWidget6)
        self.fFreq.setMinimum(-20)
        self.fFreq.setMaximum(220)
        self.fFreq.setOrientation(QtCore.Qt.Horizontal)
        self.fFreq.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fFreq.setObjectName("fFreq")
        self.gridLayout.addWidget(self.fFreq, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 1, 0, 1, 1)
        self.fPeak = QtWidgets.QSlider(self.layoutWidget6)
        self.fPeak.setMinimum(-10)
        self.fPeak.setMaximum(190)
        self.fPeak.setProperty("value", 84)
        self.fPeak.setSliderPosition(84)
        self.fPeak.setOrientation(QtCore.Qt.Horizontal)
        self.fPeak.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fPeak.setObjectName("fPeak")
        self.gridLayout.addWidget(self.fPeak, 1, 1, 1, 1)
        self.fAmp = QtWidgets.QSlider(self.layoutWidget6)
        self.fAmp.setMaximum(200)
        self.fAmp.setProperty("value", 20)
        self.fAmp.setOrientation(QtCore.Qt.Horizontal)
        self.fAmp.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fAmp.setObjectName("fAmp")
        self.gridLayout.addWidget(self.fAmp, 4, 1, 1, 1)
        self.fWidth = QtWidgets.QSlider(self.layoutWidget6)
        self.fWidth.setMaximum(200)
        self.fWidth.setProperty("value", 39)
        self.fWidth.setOrientation(QtCore.Qt.Horizontal)
        self.fWidth.setInvertedAppearance(False)
        self.fWidth.setInvertedControls(False)
        self.fWidth.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fWidth.setTickInterval(1)
        self.fWidth.setObjectName("fWidth")
        self.gridLayout.addWidget(self.fWidth, 0, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 4, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget6)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fPhase = QtWidgets.QSlider(self.layoutWidget6)
        self.fPhase.setMinimum(-100)
        self.fPhase.setMaximum(100)
        self.fPhase.setOrientation(QtCore.Qt.Horizontal)
        self.fPhase.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fPhase.setObjectName("fPhase")
        self.gridLayout.addWidget(self.fPhase, 3, 1, 1, 1)
        self.layoutWidget7 = QtWidgets.QWidget(self.PLOTHERE)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 440, 390, 23))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 0, 0, 1, 1)
        self.fMin = QtWidgets.QLineEdit(self.layoutWidget7)
        self.fMin.setObjectName("fMin")
        self.gridLayout_10.addWidget(self.fMin, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_59.setObjectName("label_59")
        self.gridLayout_10.addWidget(self.label_59, 0, 2, 1, 1)
        self.fMax = QtWidgets.QLineEdit(self.layoutWidget7)
        self.fMax.setObjectName("fMax")
        self.gridLayout_10.addWidget(self.fMax, 0, 3, 1, 1)
        self.gain = QtWidgets.QSlider(self.PLOTHERE)
        self.gain.setGeometry(QtCore.QRect(640, 470, 20, 100))
        self.gain.setMinimum(1)
        self.gain.setMaximum(100)
        self.gain.setProperty("value", 50)
        self.gain.setOrientation(QtCore.Qt.Vertical)
        self.gain.setInvertedAppearance(False)
        self.gain.setInvertedControls(False)
        self.gain.setObjectName("gain")
        self.resG = QtWidgets.QToolButton(self.PLOTHERE)
        self.resG.setGeometry(QtCore.QRect(640, 580, 20, 21))
        self.resG.setObjectName("resG")
        self.label_3 = QtWidgets.QLabel(self.PLOTHERE)
        self.label_3.setGeometry(QtCore.QRect(620, 440, 40, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.layoutWidget8 = QtWidgets.QWidget(self.PLOTHERE)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 470, 30, 131))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.resW = QtWidgets.QToolButton(self.layoutWidget8)
        self.resW.setObjectName("resW")
        self.gridLayout_14.addWidget(self.resW, 0, 0, 1, 1)
        self.resP = QtWidgets.QToolButton(self.layoutWidget8)
        self.resP.setObjectName("resP")
        self.gridLayout_14.addWidget(self.resP, 1, 0, 1, 1)
        self.resA = QtWidgets.QToolButton(self.layoutWidget8)
        self.resA.setObjectName("resA")
        self.gridLayout_14.addWidget(self.resA, 2, 0, 1, 1)
        self.resPh = QtWidgets.QToolButton(self.layoutWidget8)
        self.resPh.setObjectName("resPh")
        self.gridLayout_14.addWidget(self.resPh, 3, 0, 1, 1)
        self.resAm = QtWidgets.QToolButton(self.layoutWidget8)
        self.resAm.setObjectName("resAm")
        self.gridLayout_14.addWidget(self.resAm, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(700, 10, 241, 521))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.names_sel_2 = QtWidgets.QListWidget(self.frame_3)
        self.names_sel_2.setGeometry(QtCore.QRect(10, 30, 221, 481))
        self.names_sel_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.names_sel_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.names_sel_2.setBatchSize(100)
        self.names_sel_2.setObjectName("names_sel_2")
        item = QtWidgets.QListWidgetItem()
        self.names_sel_2.addItem(item)
        self.label_40 = QtWidgets.QLabel(self.frame_3)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 210, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.saveParams = QtWidgets.QPushButton(self.tab_4)
        self.saveParams.setGeometry(QtCore.QRect(790, 540, 150, 25))
        self.saveParams.setObjectName("saveParams")
        self.layoutWidget9 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget9.setEnabled(False)
        self.layoutWidget9.setGeometry(QtCore.QRect(690, 600, 254, 23))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.monW = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.monW.setEnabled(False)
        self.monW.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monW.setSuffix("")
        self.monW.setMinimum(-99.0)
        self.monW.setObjectName("monW")
        self.horizontalLayout.addWidget(self.monW)
        self.monP = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.monP.setEnabled(False)
        self.monP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monP.setMinimum(-99.0)
        self.monP.setObjectName("monP")
        self.horizontalLayout.addWidget(self.monP)
        self.monA = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.monA.setEnabled(False)
        self.monA.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monA.setMinimum(-9.9)
        self.monA.setObjectName("monA")
        self.horizontalLayout.addWidget(self.monA)
        self.monPh = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.monPh.setEnabled(False)
        self.monPh.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monPh.setMinimum(-9.9)
        self.monPh.setObjectName("monPh")
        self.horizontalLayout.addWidget(self.monPh)
        self.monAm = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.monAm.setEnabled(False)
        self.monAm.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.monAm.setObjectName("monAm")
        self.horizontalLayout.addWidget(self.monAm)
        self.plotTo = QtWidgets.QPushButton(self.tab_4)
        self.plotTo.setGeometry(QtCore.QRect(700, 540, 80, 25))
        self.plotTo.setCheckable(True)
        self.plotTo.setObjectName("plotTo")
        self.loadParams = QtWidgets.QPushButton(self.tab_4)
        self.loadParams.setGeometry(QtCore.QRect(790, 570, 150, 25))
        self.loadParams.setObjectName("loadParams")
        self.confirm = QtWidgets.QLabel(self.tab_4)
        self.confirm.setGeometry(QtCore.QRect(110, 170, 440, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(193, 193, 193))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(193, 193, 193))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.confirm.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm.setObjectName("confirm")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(13, 30, 101, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(220, 30, 56, 21))
        self.label_18.setObjectName("label_18")
        self.dt = QtWidgets.QSpinBox(self.tab_2)
        self.dt.setGeometry(QtCore.QRect(130, 30, 85, 21))
        self.dt.setMaximum(1000000)
        self.dt.setProperty("value", 10)
        self.dt.setObjectName("dt")
        self.acdc_solve_ss = QtWidgets.QCheckBox(self.tab_2)
        self.acdc_solve_ss.setGeometry(QtCore.QRect(21, 91, 671, 20))
        self.acdc_solve_ss.setChecked(False)
        self.acdc_solve_ss.setObjectName("acdc_solve_ss")
        self.model_h2so4 = QtWidgets.QCheckBox(self.tab_2)
        self.model_h2so4.setGeometry(QtCore.QRect(21, 117, 671, 20))
        self.model_h2so4.setChecked(False)
        self.model_h2so4.setObjectName("model_h2so4")
        self.condensation = QtWidgets.QCheckBox(self.tab_2)
        self.condensation.setGeometry(QtCore.QRect(21, 143, 671, 20))
        self.condensation.setChecked(True)
        self.condensation.setObjectName("condensation")
        self.coagulation = QtWidgets.QCheckBox(self.tab_2)
        self.coagulation.setGeometry(QtCore.QRect(21, 169, 671, 20))
        self.coagulation.setChecked(True)
        self.coagulation.setObjectName("coagulation")
        self.use_dmps_special = QtWidgets.QCheckBox(self.tab_2)
        self.use_dmps_special.setEnabled(True)
        self.use_dmps_special.setGeometry(QtCore.QRect(21, 195, 671, 20))
        self.use_dmps_special.setChecked(False)
        self.use_dmps_special.setObjectName("use_dmps_special")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(20, 400, 671, 21))
        self.label_23.setObjectName("label_23")
        self.wait_for = QtWidgets.QSpinBox(self.tab_2)
        self.wait_for.setGeometry(QtCore.QRect(24, 430, 50, 21))
        self.wait_for.setMinimum(-1)
        self.wait_for.setMaximum(1000000)
        self.wait_for.setProperty("value", 0)
        self.wait_for.setObjectName("wait_for")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(85, 430, 611, 21))
        self.label_24.setObjectName("label_24")
        self.python = QtWidgets.QCheckBox(self.tab_2)
        self.python.setGeometry(QtCore.QRect(20, 460, 671, 20))
        self.python.setChecked(True)
        self.python.setObjectName("python")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 30, 201, 170))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 20, 181, 71))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget10)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.lat = QtWidgets.QDoubleSpinBox(self.layoutWidget10)
        self.lat.setDecimals(3)
        self.lat.setMinimum(-90.0)
        self.lat.setMaximum(90.0)
        self.lat.setSingleStep(1.0)
        self.lat.setProperty("value", 60.0)
        self.lat.setObjectName("lat")
        self.gridLayout_3.addWidget(self.lat, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.lon = QtWidgets.QDoubleSpinBox(self.layoutWidget10)
        self.lon.setDecimals(3)
        self.lon.setMinimum(-180.0)
        self.lon.setMaximum(180.0)
        self.lon.setSingleStep(1.0)
        self.lon.setProperty("value", -25.0)
        self.lon.setObjectName("lon")
        self.gridLayout_3.addWidget(self.lon, 1, 1, 1, 1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 120, 181, 30))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 1)
        self.ch_albedo = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.ch_albedo.setDecimals(3)
        self.ch_albedo.setMinimum(0.0)
        self.ch_albedo.setMaximum(1.0)
        self.ch_albedo.setSingleStep(0.01)
        self.ch_albedo.setProperty("value", 0.2)
        self.ch_albedo.setObjectName("ch_albedo")
        self.gridLayout_7.addWidget(self.ch_albedo, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(730, 230, 201, 210))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.resolve_base = QtWidgets.QCheckBox(self.groupBox_4)
        self.resolve_base.setEnabled(True)
        self.resolve_base.setGeometry(QtCore.QRect(10, 30, 179, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resolve_base.setFont(font)
        self.resolve_base.setCheckable(True)
        self.resolve_base.setChecked(False)
        self.resolve_base.setObjectName("resolve_base")
        self.frameBase = QtWidgets.QFrame(self.groupBox_4)
        self.frameBase.setEnabled(True)
        self.frameBase.setGeometry(QtCore.QRect(10, 50, 191, 151))
        self.frameBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBase.setObjectName("frameBase")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frameBase)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 180, 130))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setEnabled(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 1)
        self.fill_formation_with = QtWidgets.QComboBox(self.layoutWidget_2)
        self.fill_formation_with.setEnabled(True)
        self.fill_formation_with.setObjectName("fill_formation_with")
        self.fill_formation_with.addItem("")
        self.fill_formation_with.addItem("")
        self.fill_formation_with.addItem("")
        self.gridLayout_4.addWidget(self.fill_formation_with, 3, 0, 1, 2)
        self.resolve_base_precision = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.resolve_base_precision.setEnabled(True)
        self.resolve_base_precision.setDecimals(3)
        self.resolve_base_precision.setMaximum(2.0)
        self.resolve_base_precision.setSingleStep(0.01)
        self.resolve_base_precision.setProperty("value", 0.05)
        self.resolve_base_precision.setObjectName("resolve_base_precision")
        self.gridLayout_4.addWidget(self.resolve_base_precision, 0, 1, 1, 1)
        self.dma_f = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.dma_f.setEnabled(True)
        self.dma_f.setDecimals(3)
        self.dma_f.setMaximum(2.0)
        self.dma_f.setSingleStep(0.01)
        self.dma_f.setProperty("value", 0.05)
        self.dma_f.setObjectName("dma_f")
        self.gridLayout_4.addWidget(self.dma_f, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setEnabled(True)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setEnabled(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.layoutWidget11 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget11.setGeometry(QtCore.QRect(40, 220, 651, 50))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.dmps_highband_lower_limit = QtWidgets.QLineEdit(self.layoutWidget11)
        self.dmps_highband_lower_limit.setEnabled(False)
        self.dmps_highband_lower_limit.setObjectName("dmps_highband_lower_limit")
        self.gridLayout_11.addWidget(self.dmps_highband_lower_limit, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_20.setEnabled(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 1, 0, 1, 1)
        self.dmps_lowband_upper_limit = QtWidgets.QLineEdit(self.layoutWidget11)
        self.dmps_lowband_upper_limit.setEnabled(False)
        self.dmps_lowband_upper_limit.setObjectName("dmps_lowband_upper_limit")
        self.gridLayout_11.addWidget(self.dmps_lowband_upper_limit, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 2, 1, 1)
        self.vap_logical = QtWidgets.QCheckBox(self.tab_2)
        self.vap_logical.setGeometry(QtCore.QRect(20, 510, 420, 30))
        self.vap_logical.setChecked(True)
        self.vap_logical.setObjectName("vap_logical")
        self.frameVap = QtWidgets.QFrame(self.tab_2)
        self.frameVap.setGeometry(QtCore.QRect(30, 540, 470, 60))
        self.frameVap.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameVap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVap.setObjectName("frameVap")
        self.layoutWidget12 = QtWidgets.QWidget(self.frameVap)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 0, 460, 50))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget12)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_51.setObjectName("label_51")
        self.gridLayout_13.addWidget(self.label_51, 0, 0, 1, 1)
        self.vap_names = QtWidgets.QLineEdit(self.layoutWidget12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vap_names.setFont(font)
        self.vap_names.setObjectName("vap_names")
        self.gridLayout_13.addWidget(self.vap_names, 0, 1, 1, 1)
        self.butVapourNames = QtWidgets.QToolButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.butVapourNames.setFont(font)
        self.butVapourNames.setObjectName("butVapourNames")
        self.gridLayout_13.addWidget(self.butVapourNames, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget12)
        self.label_50.setObjectName("label_50")
        self.gridLayout_13.addWidget(self.label_50, 1, 0, 1, 1)
        self.vap_props = QtWidgets.QLineEdit(self.layoutWidget12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vap_props.setFont(font)
        self.vap_props.setObjectName("vap_props")
        self.gridLayout_13.addWidget(self.vap_props, 1, 1, 1, 1)
        self.butVapour = QtWidgets.QToolButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.butVapour.setFont(font)
        self.butVapour.setObjectName("butVapour")
        self.gridLayout_13.addWidget(self.butVapour, 1, 2, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(730, 470, 201, 130))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.chemistryModules = QtWidgets.QComboBox(self.groupBox_10)
        self.chemistryModules.setEnabled(True)
        self.chemistryModules.setGeometry(QtCore.QRect(10, 50, 178, 21))
        self.chemistryModules.setObjectName("chemistryModules")
        self.label_39 = QtWidgets.QLabel(self.groupBox_10)
        self.label_39.setEnabled(True)
        self.label_39.setGeometry(QtCore.QRect(10, 20, 160, 20))
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.recompile = QtWidgets.QPushButton(self.groupBox_10)
        self.recompile.setGeometry(QtCore.QRect(10, 90, 180, 30))
        self.recompile.setObjectName("recompile")
        self.compileProgressBar = QtWidgets.QProgressBar(self.tab_2)
        self.compileProgressBar.setGeometry(QtCore.QRect(10, 610, 921, 20))
        self.compileProgressBar.setProperty("value", 0)
        self.compileProgressBar.setTextVisible(False)
        self.compileProgressBar.setInvertedAppearance(False)
        self.compileProgressBar.setObjectName("compileProgressBar")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_5 = QtWidgets.QFrame(self.tab_5)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 911, 531))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MonitorWindow = QtWidgets.QPlainTextEdit(self.frame_5)
        self.MonitorWindow.setGeometry(QtCore.QRect(10, 10, 891, 511))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.MonitorWindow.setFont(font)
        self.MonitorWindow.setAcceptDrops(False)
        self.MonitorWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MonitorWindow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MonitorWindow.setUndoRedoEnabled(False)
        self.MonitorWindow.setReadOnly(True)
        self.MonitorWindow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.MonitorWindow.setBackgroundVisible(False)
        self.MonitorWindow.setObjectName("MonitorWindow")
        self.frameStart = QtWidgets.QFrame(self.tab_5)
        self.frameStart.setGeometry(QtCore.QRect(240, 560, 251, 71))
        self.frameStart.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStart.setObjectName("frameStart")
        self.startButton = QtWidgets.QPushButton(self.frameStart)
        self.startButton.setGeometry(QtCore.QRect(10, 20, 230, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.frameStop = QtWidgets.QFrame(self.tab_5)
        self.frameStop.setEnabled(True)
        self.frameStop.setGeometry(QtCore.QRect(510, 559, 261, 71))
        self.frameStop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameStop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStop.setObjectName("frameStop")
        self.stopButton = QtWidgets.QPushButton(self.frameStop)
        self.stopButton.setEnabled(True)
        self.stopButton.setGeometry(QtCore.QRect(20, 20, 200, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.pauseScroll = QtWidgets.QPushButton(self.tab_5)
        self.pauseScroll.setGeometry(QtCore.QRect(810, 560, 120, 25))
        self.pauseScroll.setCheckable(True)
        self.pauseScroll.setObjectName("pauseScroll")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.plotResultWindow = PlotWidget(self.tab_6)
        self.plotResultWindow.setGeometry(QtCore.QRect(10, 40, 690, 540))
        self.plotResultWindow.setObjectName("plotResultWindow")
        self.show_netcdf = QtWidgets.QLabel(self.plotResultWindow)
        self.show_netcdf.setGeometry(QtCore.QRect(120, 220, 440, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 136, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.show_netcdf.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.show_netcdf.setFont(font)
        self.show_netcdf.setAlignment(QtCore.Qt.AlignCenter)
        self.show_netcdf.setObjectName("show_netcdf")
        self.availableVars = QtWidgets.QListWidget(self.tab_6)
        self.availableVars.setGeometry(QtCore.QRect(710, 40, 221, 540))
        self.availableVars.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.availableVars.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.availableVars.setProperty("showDropIndicator", False)
        self.availableVars.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.availableVars.setBatchSize(100)
        self.availableVars.setObjectName("availableVars")
        self.loadNetcdf = QtWidgets.QPushButton(self.tab_6)
        self.loadNetcdf.setGeometry(QtCore.QRect(10, 600, 221, 30))
        self.loadNetcdf.setObjectName("loadNetcdf")
        self.fLog_2 = QtWidgets.QRadioButton(self.tab_6)
        self.fLog_2.setGeometry(QtCore.QRect(600, 600, 101, 20))
        self.fLog_2.setObjectName("fLog_2")
        self.fLin_2 = QtWidgets.QRadioButton(self.tab_6)
        self.fLin_2.setGeometry(QtCore.QRect(530, 600, 61, 20))
        self.fLin_2.setChecked(True)
        self.fLin_2.setObjectName("fLin_2")
        self.tabWidget.addTab(self.tab_6, "")
        self.printButton = QtWidgets.QPushButton(self.MainFrame)
        self.printButton.setGeometry(QtCore.QRect(10, 690, 221, 30))
        self.printButton.setObjectName("printButton")
        self.saveButton = QtWidgets.QPushButton(self.MainFrame)
        self.saveButton.setGeometry(QtCore.QRect(260, 690, 210, 30))
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(self.MainFrame)
        self.loadButton.setGeometry(QtCore.QRect(500, 690, 210, 30))
        self.loadButton.setObjectName("loadButton")
        self.saveDefaults = QtWidgets.QPushButton(self.MainFrame)
        self.saveDefaults.setGeometry(QtCore.QRect(740, 690, 210, 30))
        self.saveDefaults.setObjectName("saveDefaults")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionQuit_Ctrl_Q = QtWidgets.QAction(MainWindow)
        self.actionQuit_Ctrl_Q.setObjectName("actionQuit_Ctrl_Q")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionQuit_Ctrl_Q)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.names_sel.isSortingEnabled()
        self.names_sel.setSortingEnabled(False)
        item = self.names_sel.item(0)
        item.setText(_translate("MainWindow", "<select variables from next tab>"))
        self.names_sel.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(_translate("MainWindow", "Selected input variables:"))
        self.groupBox.setTitle(_translate("MainWindow", "Modules in use"))
        self.label_43.setText(_translate("MainWindow", "More features in Advanced"))
        self.checkBox_che.setText(_translate("MainWindow", "Use Chemistry"))
        self.checkBox_acd.setText(_translate("MainWindow", "Use ACDC"))
        self.checkBox_aer.setText(_translate("MainWindow", "Use Aerosols"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Model run options"))
        self.label_2.setToolTip(_translate("MainWindow", "Total simulation time in decimal hours"))
        self.label_2.setText(_translate("MainWindow", "Runtime (h)"))
        self.label_5.setToolTip(_translate("MainWindow", "Used for calculation of correct Julian day"))
        self.label_5.setText(_translate("MainWindow", "Batch name"))
        self.case_name.setToolTip(_translate("MainWindow", "Group name, output is saved under directory named after this."))
        self.label_6.setToolTip(_translate("MainWindow", "Group name, Output is saved under directory named after this"))
        self.label_6.setText(_translate("MainWindow", "Run name"))
        self.run_name.setToolTip(_translate("MainWindow", "Run name, output is saved under directory named after this, locating in Batch name directory."))
        self.label_7.setToolTip(_translate("MainWindow", "Run name, output is saved under directory named after this, locating in Batch name directory."))
        self.label_7.setText(_translate("MainWindow", "Date"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_8.setToolTip(_translate("MainWindow", "Description of the run, max 1000 characters. This will be saved in all output files."))
        self.label_8.setText(_translate("MainWindow", "Desciption"))
        self.description.setToolTip(_translate("MainWindow", "Description of the run, max 1000 characters. This will be saved in all output files."))
        self.groupBox_8.setTitle(_translate("MainWindow", "Aerosol structure"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_36.setText(_translate("MainWindow", "Number of bins"))
        self.label_37.setText(_translate("MainWindow", "PSD scheme"))
        self.psd_mode.setItemText(0, _translate("MainWindow", "Lukas basic"))
        self.psd_mode.setItemText(1, _translate("MainWindow", "Lukas advanced"))
        self.psd_mode.setItemText(2, _translate("MainWindow", "Lukas premium"))
        self.use_dmps.setText(_translate("MainWindow", "dmps"))
        self.label_35.setText(_translate("MainWindow", "Particle size range (m):"))
        self.min_particle_diam.setText(_translate("MainWindow", "1e-9"))
        self.max_particle_diam.setText(_translate("MainWindow", "1e-6"))
        self.label_41.setText(_translate("MainWindow", "Read in BG particles for*"))
        self.label_38.setText(_translate("MainWindow", "*) if BG particle file is defined"))
        self.label_42.setText(_translate("MainWindow", "hours"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Paths and files"))
        self.label_52.setText(_translate("MainWindow", "I/O directories, absolute or relative to executable"))
        self.label_46.setText(_translate("MainWindow", "Common input path"))
        self.case_dir.setText(_translate("MainWindow", "input"))
        self.browseCommonIn.setText(_translate("MainWindow", "..."))
        self.label_47.setText(_translate("MainWindow", "Common output path"))
        self.browseCommonOut.setText(_translate("MainWindow", "..."))
        self.label_44.setText(_translate("MainWindow", "ENV input"))
        self.browseEnv.setText(_translate("MainWindow", "..."))
        self.label_45.setText(_translate("MainWindow", "MCM input"))
        self.browseMcm.setText(_translate("MainWindow", "..."))
        self.label_49.setText(_translate("MainWindow", "BG particles"))
        self.browsePar.setText(_translate("MainWindow", "..."))
        self.label_53.setText(_translate("MainWindow", "Extra particles"))
        self.browseXtr.setText(_translate("MainWindow", "..."))
        self.label_48.setText(_translate("MainWindow", "Input files (relative to common input path if given)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Output"))
        self.label_11.setText(_translate("MainWindow", "Print every:"))
        self.print_interval.setSuffix(_translate("MainWindow", " s"))
        self.label_12.setText(_translate("MainWindow", "Save every:"))
        self.fsave_interval.setSuffix(_translate("MainWindow", " s"))
        self.label_15.setText(_translate("MainWindow", "or"))
        self.fsave_division.setSuffix(_translate("MainWindow", " samples"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General options"))
        self.label_54.setText(_translate("MainWindow", "Select input variables:"))
        self.butMoveToSelVars.setText(_translate("MainWindow", "<---"))
        item = self.selected_vars.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Variable"))
        item = self.selected_vars.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Column"))
        item = self.selected_vars.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Multiply"))
        item = self.selected_vars.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Shift"))
        item = self.selected_vars.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Use PM"))
        item = self.selected_vars.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "unit"))
        item = self.selected_vars.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ind"))
        self.butRemoveSelVars.setText(_translate("MainWindow", "--->"))
        self.label_60.setText(_translate("MainWindow", "Move to selected"))
        self.label_61.setText(_translate("MainWindow", "Remove selected"))
        self.markAll.setText(_translate("MainWindow", "mark all"))
        self.invertMarks.setText(_translate("MainWindow", "invert markings"))
        self.loadFixed.setToolTip(_translate("MainWindow", "Loads fixed variables from KPP def-file. These are variables under the #DEFFIX header."))
        self.loadFixed.setText(_translate("MainWindow", "Load fixed variables"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Input variables"))
        self.fLin.setText(_translate("MainWindow", "Linear"))
        self.fLog.setText(_translate("MainWindow", "Logarithmic"))
        self.label_55.setText(_translate("MainWindow", "Ang.freq"))
        self.label_34.setText(_translate("MainWindow", "Peaktime"))
        self.label_57.setText(_translate("MainWindow", "Amplitude"))
        self.label_56.setText(_translate("MainWindow", "Phase"))
        self.label.setText(_translate("MainWindow", "Width"))
        self.label_58.setText(_translate("MainWindow", "Minimum"))
        self.fMin.setText(_translate("MainWindow", "10"))
        self.label_59.setText(_translate("MainWindow", "Maximum"))
        self.fMax.setText(_translate("MainWindow", "100000"))
        self.resG.setText(_translate("MainWindow", "R"))
        self.label_3.setText(_translate("MainWindow", "Gain"))
        self.resW.setText(_translate("MainWindow", "R"))
        self.resP.setText(_translate("MainWindow", "R"))
        self.resA.setText(_translate("MainWindow", "R"))
        self.resPh.setText(_translate("MainWindow", "R"))
        self.resAm.setText(_translate("MainWindow", "R"))
        __sortingEnabled = self.names_sel_2.isSortingEnabled()
        self.names_sel_2.setSortingEnabled(False)
        item = self.names_sel_2.item(0)
        item.setText(_translate("MainWindow", "<select variables from next tab>"))
        self.names_sel_2.setSortingEnabled(__sortingEnabled)
        self.label_40.setText(_translate("MainWindow", "Selected input variables:"))
        self.saveParams.setText(_translate("MainWindow", "Save to selected"))
        self.plotTo.setText(_translate("MainWindow", "Plot 2nd"))
        self.loadParams.setText(_translate("MainWindow", "Load selected"))
        self.confirm.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Function creator"))
        self.label_17.setText(_translate("MainWindow", "Model timestep"))
        self.label_18.setText(_translate("MainWindow", "seconds"))
        self.acdc_solve_ss.setText(_translate("MainWindow", "Solve ACDC to Steady State (might be necessary, if acid/base concentrations vary rapidly)"))
        self.model_h2so4.setText(_translate("MainWindow", "Replace any H2SO4 input with modelled (requires corresponding chemistry)."))
        self.condensation.setText(_translate("MainWindow", "Aerosols includes condensation. If unchecked, condensation is not considered."))
        self.coagulation.setText(_translate("MainWindow", "Aerosols includes coagulation. If unchecked, coagulation is not considered."))
        self.use_dmps_special.setText(_translate("MainWindow", "Use background particles for the whole run"))
        self.label_23.setText(_translate("MainWindow", "Before the simulation starts, pause program for "))
        self.label_24.setText(_translate("MainWindow", "seconds (0=wait indefinitely, negative=don\'t wait)"))
        self.python.setText(_translate("MainWindow", "After the run is finished, offer to plot some of the output (with Python)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Location"))
        self.label_25.setText(_translate("MainWindow", "Latitude"))
        self.lat.setToolTip(_translate("MainWindow", "Negative values = South"))
        self.label_9.setText(_translate("MainWindow", "Longitude"))
        self.lon.setToolTip(_translate("MainWindow", "Negative values = East"))
        self.label_33.setText(_translate("MainWindow", "Surface albedo"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Formation rates"))
        self.resolve_base.setText(_translate("MainWindow", "Solve bases"))
        self.label_26.setText(_translate("MainWindow", "Precision"))
        self.fill_formation_with.setItemText(0, _translate("MainWindow", "Fixed ratio"))
        self.fill_formation_with.setItemText(1, _translate("MainWindow", "Fill with DMA"))
        self.fill_formation_with.setItemText(2, _translate("MainWindow", "Fill with NH3"))
        self.label_28.setText(_translate("MainWindow", "Use fixed ratio or fill gap from ACDC"))
        self.label_27.setText(_translate("MainWindow", "Ratio"))
        self.label_19.setText(_translate("MainWindow", "Highband lower limit (m)"))
        self.label_20.setText(_translate("MainWindow", "Larger (diam) particles will be replaced with background particles."))
        self.label_21.setText(_translate("MainWindow", "Lowband upper limit (m)"))
        self.label_22.setText(_translate("MainWindow", "Smaller (diam) particles will be replaced with background particles."))
        self.vap_logical.setText(_translate("MainWindow", "Vapour properties in use"))
        self.label_51.setText(_translate("MainWindow", "Path to vapour names"))
        self.vap_names.setText(_translate("MainWindow", "Vapour_names.dat"))
        self.butVapourNames.setText(_translate("MainWindow", "..."))
        self.label_50.setText(_translate("MainWindow", "Path to vapour properties    "))
        self.vap_props.setText(_translate("MainWindow", "Vapour_properties.dat"))
        self.butVapour.setText(_translate("MainWindow", "..."))
        self.groupBox_10.setTitle(_translate("MainWindow", "Chemistry module"))
        self.label_39.setText(_translate("MainWindow", "Available modules"))
        self.recompile.setText(_translate("MainWindow", "Recompile program"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced"))
        self.startButton.setText(_translate("MainWindow", "Run with current settings"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.pauseScroll.setText(_translate("MainWindow", "Pause scroll"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Test run"))
        self.show_netcdf.setText(_translate("MainWindow", "This feature needs NetCDF for Python"))
        self.loadNetcdf.setText(_translate("MainWindow", "Load Box output file"))
        self.fLog_2.setText(_translate("MainWindow", "Logarithmic"))
        self.fLin_2.setText(_translate("MainWindow", "Linear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Output graph"))
        self.printButton.setText(_translate("MainWindow", "Print model input"))
        self.saveButton.setText(_translate("MainWindow", "Save INITFILE"))
        self.loadButton.setText(_translate("MainWindow", "Load INITFILE"))
        self.saveDefaults.setText(_translate("MainWindow", "Save settings as defaults"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_2.setText(_translate("MainWindow", "Save current settings"))
        self.actionSave_2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit_Ctrl_Q.setText(_translate("MainWindow", "Quit"))
        self.actionQuit_Ctrl_Q.setToolTip(_translate("MainWindow", "Quit without save"))
        self.actionQuit_Ctrl_Q.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open settings file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionPrint.setText(_translate("MainWindow", "Print settings"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
from pyqtgraph import PlotWidget
