# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LSD.ui',
# licensing of 'LSD.ui' applies.
#
# Created: Sun Dec  8 00:10:49 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(979, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(9, 9, 961, 728))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MainFrame.setObjectName("MainFrame")
        self.tabWidget = QtWidgets.QTabWidget(self.MainFrame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 951, 661))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(690, 30, 241, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.names_sel = QtWidgets.QListWidget(self.frame)
        self.names_sel.setGeometry(QtCore.QRect(10, 30, 221, 491))
        self.names_sel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.names_sel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.names_sel.setProperty("showDropIndicator", False)
        self.names_sel.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.names_sel.setBatchSize(100)
        self.names_sel.setObjectName("names_sel")
        QtWidgets.QListWidgetItem(self.names_sel)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 210, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(460, 20, 221, 160))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setGeometry(QtCore.QRect(10, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_43.setFont(font)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 30, 139, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_che = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_che.setEnabled(True)
        self.checkBox_che.setChecked(True)
        self.checkBox_che.setObjectName("checkBox_che")
        self.verticalLayout.addWidget(self.checkBox_che)
        self.checkBox_acd = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_acd.setChecked(True)
        self.checkBox_acd.setObjectName("checkBox_acd")
        self.verticalLayout.addWidget(self.checkBox_acd)
        self.checkBox_aer = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_aer.setChecked(True)
        self.checkBox_aer.setObjectName("checkBox_aer")
        self.verticalLayout.addWidget(self.checkBox_aer)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 441, 291))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 30, 410, 250))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.runtime = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.runtime.setFont(font)
        self.runtime.setProperty("value", 24.0)
        self.runtime.setObjectName("runtime")
        self.gridLayout_2.addWidget(self.runtime, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.case_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.case_name.setFont(font)
        self.case_name.setObjectName("case_name")
        self.gridLayout_2.addWidget(self.case_name, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.run_name = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.run_name.setFont(font)
        self.run_name.setObjectName("run_name")
        self.gridLayout_2.addWidget(self.run_name, 2, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 3, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 3, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.description = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.description.setFont(font)
        self.description.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.description.setMaximumBlockCount(0)
        self.description.setObjectName("description")
        self.gridLayout_2.addWidget(self.description, 4, 1, 2, 4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(460, 190, 221, 280))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton.setGeometry(QtCore.QRect(420, 140, 27, 21))
        self.toolButton.setObjectName("toolButton")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_8)
        self.frame_4.setEnabled(True)
        self.frame_4.setGeometry(QtCore.QRect(0, 30, 211, 240))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 190, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 0, 0, 1, 1)
        self.n_bins_particle = QtWidgets.QSpinBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.n_bins_particle.setFont(font)
        self.n_bins_particle.setMinimum(1)
        self.n_bins_particle.setMaximum(1000)
        self.n_bins_particle.setProperty("value", 100)
        self.n_bins_particle.setObjectName("n_bins_particle")
        self.gridLayout_8.addWidget(self.n_bins_particle, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 1, 0, 1, 1)
        self.psd_mode = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.psd_mode.setFont(font)
        self.psd_mode.setObjectName("psd_mode")
        self.psd_mode.addItem("")
        self.psd_mode.addItem("")
        self.psd_mode.addItem("")
        self.gridLayout_8.addWidget(self.psd_mode, 2, 0, 1, 2)
        self.use_dmps = QtWidgets.QCheckBox(self.layoutWidget2)
        self.use_dmps.setObjectName("use_dmps")
        self.gridLayout_8.addWidget(self.use_dmps, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 99, 191, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 3)
        self.min_particle_diam = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.min_particle_diam.setFont(font)
        self.min_particle_diam.setObjectName("min_particle_diam")
        self.gridLayout_12.addWidget(self.min_particle_diam, 1, 0, 1, 2)
        self.max_particle_diam = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.max_particle_diam.setFont(font)
        self.max_particle_diam.setObjectName("max_particle_diam")
        self.gridLayout_12.addWidget(self.max_particle_diam, 1, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 2, 0, 1, 3)
        self.dmps_read_in_time = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dmps_read_in_time.setFont(font)
        self.dmps_read_in_time.setMaximum(99.99)
        self.dmps_read_in_time.setProperty("value", 2.0)
        self.dmps_read_in_time.setObjectName("dmps_read_in_time")
        self.gridLayout_12.addWidget(self.dmps_read_in_time, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 3, 1, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_38.setFont(font)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 4, 0, 1, 3)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 320, 441, 291))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 411, 251))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_52.setObjectName("label_52")
        self.gridLayout_9.addWidget(self.label_52, 0, 0, 1, 4)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_9.addWidget(self.label_46, 1, 0, 1, 2)
        self.case_dir = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.case_dir.setFont(font)
        self.case_dir.setObjectName("case_dir")
        self.gridLayout_9.addWidget(self.case_dir, 1, 2, 1, 1)
        self.browseCommonIn = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browseCommonIn.setFont(font)
        self.browseCommonIn.setObjectName("browseCommonIn")
        self.gridLayout_9.addWidget(self.browseCommonIn, 1, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_9.addWidget(self.label_47, 2, 0, 1, 2)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_9.addWidget(self.lineEdit_13, 2, 2, 1, 1)
        self.browseCommonOut = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browseCommonOut.setFont(font)
        self.browseCommonOut.setObjectName("browseCommonOut")
        self.gridLayout_9.addWidget(self.browseCommonOut, 2, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_9.addWidget(self.label_44, 4, 0, 1, 1)
        self.env_file = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.env_file.setFont(font)
        self.env_file.setObjectName("env_file")
        self.gridLayout_9.addWidget(self.env_file, 4, 1, 1, 2)
        self.browseEnv = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browseEnv.setFont(font)
        self.browseEnv.setObjectName("browseEnv")
        self.gridLayout_9.addWidget(self.browseEnv, 4, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_9.addWidget(self.label_45, 5, 0, 1, 1)
        self.mcm_file = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.mcm_file.setFont(font)
        self.mcm_file.setObjectName("mcm_file")
        self.gridLayout_9.addWidget(self.mcm_file, 5, 1, 1, 2)
        self.browseMcm = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browseMcm.setFont(font)
        self.browseMcm.setObjectName("browseMcm")
        self.gridLayout_9.addWidget(self.browseMcm, 5, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 6, 0, 1, 1)
        self.dmps_file = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.dmps_file.setFont(font)
        self.dmps_file.setObjectName("dmps_file")
        self.gridLayout_9.addWidget(self.dmps_file, 6, 1, 1, 2)
        self.browsePar = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browsePar.setFont(font)
        self.browsePar.setObjectName("browsePar")
        self.gridLayout_9.addWidget(self.browsePar, 6, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_53.setObjectName("label_53")
        self.gridLayout_9.addWidget(self.label_53, 7, 0, 1, 1)
        self.extra_particles = QtWidgets.QLineEdit(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.extra_particles.setFont(font)
        self.extra_particles.setObjectName("extra_particles")
        self.gridLayout_9.addWidget(self.extra_particles, 7, 1, 1, 2)
        self.browseXtr = QtWidgets.QToolButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browseXtr.setFont(font)
        self.browseXtr.setObjectName("browseXtr")
        self.gridLayout_9.addWidget(self.browseXtr, 7, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 3, 0, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(460, 480, 220, 130))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 193, 90))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 2)
        self.print_interval = QtWidgets.QSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.print_interval.setFont(font)
        self.print_interval.setMinimum(0)
        self.print_interval.setMaximum(1000000)
        self.print_interval.setSingleStep(100)
        self.print_interval.setProperty("value", 600)
        self.print_interval.setObjectName("print_interval")
        self.gridLayout_5.addWidget(self.print_interval, 0, 2, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 0, 1, 2)
        self.fsave_interval = QtWidgets.QSpinBox(self.layoutWidget5)
        self.fsave_interval.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.fsave_interval.setFont(font)
        self.fsave_interval.setMaximum(1000000)
        self.fsave_interval.setSingleStep(100)
        self.fsave_interval.setProperty("value", 300)
        self.fsave_interval.setObjectName("fsave_interval")
        self.gridLayout_5.addWidget(self.fsave_interval, 1, 2, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 2, 0, 1, 1)
        self.fsave_division = QtWidgets.QSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.fsave_division.setFont(font)
        self.fsave_division.setMaximum(1000000)
        self.fsave_division.setObjectName("fsave_division")
        self.gridLayout_5.addWidget(self.fsave_division, 2, 1, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 2, 3, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(690, 30, 241, 531))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.namesdat = QtWidgets.QListWidget(self.frame_2)
        self.namesdat.setGeometry(QtCore.QRect(10, 30, 221, 491))
        self.namesdat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.namesdat.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.namesdat.setBatchSize(100)
        self.namesdat.setObjectName("namesdat")
        self.label_54 = QtWidgets.QLabel(self.frame_2)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.butMoveToSelVars = QtWidgets.QPushButton(self.tab_3)
        self.butMoveToSelVars.setGeometry(QtCore.QRect(610, 230, 70, 40))
        self.butMoveToSelVars.setObjectName("butMoveToSelVars")
        self.selected_vars = QtWidgets.QTableWidget(self.tab_3)
        self.selected_vars.setGeometry(QtCore.QRect(10, 29, 590, 531))
        self.selected_vars.setObjectName("selected_vars")
        self.selected_vars.setColumnCount(8)
        self.selected_vars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.selected_vars.setHorizontalHeaderItem(7, item)
        self.butRemoveSelVars = QtWidgets.QPushButton(self.tab_3)
        self.butRemoveSelVars.setGeometry(QtCore.QRect(610, 370, 70, 40))
        self.butRemoveSelVars.setObjectName("butRemoveSelVars")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(610, 180, 70, 40))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setWordWrap(True)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(610, 330, 70, 40))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setWordWrap(True)
        self.label_61.setObjectName("label_61")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.PLOTHERE = QtWidgets.QFrame(self.tab_4)
        self.PLOTHERE.setGeometry(QtCore.QRect(10, 10, 651, 611))
        self.PLOTHERE.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PLOTHERE.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PLOTHERE.setObjectName("PLOTHERE")
        self.PLOT = QtWidgets.QWidget(self.PLOTHERE)
        self.PLOT.setGeometry(QtCore.QRect(10, 10, 631, 411))
        self.PLOT.setObjectName("PLOT")
        self.radioButton = QtWidgets.QRadioButton(self.PLOTHERE)
        self.radioButton.setGeometry(QtCore.QRect(420, 440, 61, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.PLOTHERE)
        self.radioButton_2.setGeometry(QtCore.QRect(490, 440, 101, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.layoutWidget6 = QtWidgets.QWidget(self.PLOTHERE)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 465, 621, 131))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget6)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 1, 0, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout.addWidget(self.horizontalSlider_2, 1, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 2, 0, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout.addWidget(self.horizontalSlider_3, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 3, 0, 1, 1)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout.addWidget(self.horizontalSlider_4, 3, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 4, 0, 1, 1)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout.addWidget(self.horizontalSlider_5, 4, 1, 1, 1)
        self.layoutWidget7 = QtWidgets.QWidget(self.PLOTHERE)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 440, 390, 23))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_58.setObjectName("label_58")
        self.gridLayout_10.addWidget(self.label_58, 0, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_10.addWidget(self.lineEdit_18, 0, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_59.setObjectName("label_59")
        self.gridLayout_10.addWidget(self.label_59, 0, 2, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_10.addWidget(self.lineEdit_19, 0, 3, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(690, 30, 241, 531))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.names_sel_2 = QtWidgets.QListWidget(self.frame_3)
        self.names_sel_2.setGeometry(QtCore.QRect(10, 30, 221, 491))
        self.names_sel_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.names_sel_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.names_sel_2.setBatchSize(100)
        self.names_sel_2.setObjectName("names_sel_2")
        QtWidgets.QListWidgetItem(self.names_sel_2)
        self.label_40 = QtWidgets.QLabel(self.frame_3)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 210, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 570, 241, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(690, 600, 111, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(820, 600, 111, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(13, 30, 101, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(220, 30, 56, 21))
        self.label_18.setObjectName("label_18")
        self.dt = QtWidgets.QSpinBox(self.tab_2)
        self.dt.setGeometry(QtCore.QRect(130, 30, 85, 21))
        self.dt.setMaximum(1000000)
        self.dt.setProperty("value", 10)
        self.dt.setObjectName("dt")
        self.acdc_solve_ss = QtWidgets.QCheckBox(self.tab_2)
        self.acdc_solve_ss.setGeometry(QtCore.QRect(21, 91, 671, 20))
        self.acdc_solve_ss.setChecked(False)
        self.acdc_solve_ss.setObjectName("acdc_solve_ss")
        self.model_h2so4 = QtWidgets.QCheckBox(self.tab_2)
        self.model_h2so4.setGeometry(QtCore.QRect(21, 117, 671, 20))
        self.model_h2so4.setChecked(False)
        self.model_h2so4.setObjectName("model_h2so4")
        self.condensation = QtWidgets.QCheckBox(self.tab_2)
        self.condensation.setGeometry(QtCore.QRect(21, 143, 671, 20))
        self.condensation.setChecked(True)
        self.condensation.setObjectName("condensation")
        self.coagulation = QtWidgets.QCheckBox(self.tab_2)
        self.coagulation.setGeometry(QtCore.QRect(21, 169, 671, 20))
        self.coagulation.setChecked(True)
        self.coagulation.setObjectName("coagulation")
        self.use_dmps_special = QtWidgets.QCheckBox(self.tab_2)
        self.use_dmps_special.setEnabled(True)
        self.use_dmps_special.setGeometry(QtCore.QRect(21, 195, 671, 20))
        self.use_dmps_special.setChecked(False)
        self.use_dmps_special.setObjectName("use_dmps_special")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(20, 420, 671, 21))
        self.label_23.setObjectName("label_23")
        self.wait_for = QtWidgets.QSpinBox(self.tab_2)
        self.wait_for.setGeometry(QtCore.QRect(24, 450, 50, 21))
        self.wait_for.setMinimum(-1)
        self.wait_for.setMaximum(1000000)
        self.wait_for.setProperty("value", 0)
        self.wait_for.setObjectName("wait_for")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(85, 450, 611, 21))
        self.label_24.setObjectName("label_24")
        self.python = QtWidgets.QCheckBox(self.tab_2)
        self.python.setGeometry(QtCore.QRect(20, 480, 671, 20))
        self.python.setChecked(True)
        self.python.setObjectName("python")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 30, 201, 150))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 181, 71))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 1)
        self.lat = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.lat.setDecimals(3)
        self.lat.setMinimum(-90.0)
        self.lat.setMaximum(90.0)
        self.lat.setSingleStep(1.0)
        self.lat.setProperty("value", 60.0)
        self.lat.setObjectName("lat")
        self.gridLayout_3.addWidget(self.lat, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.lon = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.lon.setDecimals(3)
        self.lon.setMinimum(-180.0)
        self.lon.setMaximum(180.0)
        self.lon.setSingleStep(1.0)
        self.lon.setProperty("value", -25.0)
        self.lon.setObjectName("lon")
        self.gridLayout_3.addWidget(self.lon, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(10, 100, 161, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(10, 120, 161, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_30.setFont(font)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(720, 330, 201, 210))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.resolve_base = QtWidgets.QCheckBox(self.groupBox_4)
        self.resolve_base.setEnabled(True)
        self.resolve_base.setGeometry(QtCore.QRect(10, 20, 179, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.resolve_base.setFont(font)
        self.resolve_base.setCheckable(True)
        self.resolve_base.setChecked(False)
        self.resolve_base.setObjectName("resolve_base")
        self.frameBase = QtWidgets.QFrame(self.groupBox_4)
        self.frameBase.setEnabled(True)
        self.frameBase.setGeometry(QtCore.QRect(10, 50, 191, 151))
        self.frameBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBase.setObjectName("frameBase")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frameBase)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 180, 140))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setEnabled(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 1)
        self.fill_formation_with = QtWidgets.QComboBox(self.layoutWidget_2)
        self.fill_formation_with.setEnabled(True)
        self.fill_formation_with.setObjectName("fill_formation_with")
        self.fill_formation_with.addItem("")
        self.fill_formation_with.addItem("")
        self.fill_formation_with.addItem("")
        self.gridLayout_4.addWidget(self.fill_formation_with, 3, 0, 1, 2)
        self.resolve_base_precision = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.resolve_base_precision.setEnabled(True)
        self.resolve_base_precision.setDecimals(3)
        self.resolve_base_precision.setMaximum(2.0)
        self.resolve_base_precision.setSingleStep(0.01)
        self.resolve_base_precision.setProperty("value", 0.05)
        self.resolve_base_precision.setObjectName("resolve_base_precision")
        self.gridLayout_4.addWidget(self.resolve_base_precision, 0, 1, 1, 1)
        self.dma_f = QtWidgets.QDoubleSpinBox(self.layoutWidget_2)
        self.dma_f.setEnabled(True)
        self.dma_f.setDecimals(3)
        self.dma_f.setMaximum(2.0)
        self.dma_f.setSingleStep(0.01)
        self.dma_f.setProperty("value", 0.05)
        self.dma_f.setObjectName("dma_f")
        self.gridLayout_4.addWidget(self.dma_f, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setEnabled(True)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 0, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setEnabled(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(720, 200, 201, 111))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 110, 181, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 22, 166, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 0, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
        self.doubleSpinBox_7.setDecimals(3)
        self.doubleSpinBox_7.setMinimum(-90.0)
        self.doubleSpinBox_7.setMaximum(90.0)
        self.doubleSpinBox_7.setSingleStep(1.0)
        self.doubleSpinBox_7.setProperty("value", 60.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_6.addWidget(self.doubleSpinBox_7, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_6.addWidget(self.label_32, 1, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
        self.doubleSpinBox_8.setDecimals(3)
        self.doubleSpinBox_8.setMinimum(-180.0)
        self.doubleSpinBox_8.setMaximum(180.0)
        self.doubleSpinBox_8.setSingleStep(1.0)
        self.doubleSpinBox_8.setProperty("value", -25.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_6.addWidget(self.doubleSpinBox_8, 1, 1, 1, 1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 22, 181, 30))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 1)
        self.ch_albedo = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.ch_albedo.setDecimals(3)
        self.ch_albedo.setMinimum(0.0)
        self.ch_albedo.setMaximum(1.0)
        self.ch_albedo.setSingleStep(1.0)
        self.ch_albedo.setProperty("value", 0.2)
        self.ch_albedo.setObjectName("ch_albedo")
        self.gridLayout_7.addWidget(self.ch_albedo, 0, 1, 1, 1)
        self.layoutWidget9 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(40, 220, 651, 50))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget9)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.dmps_highband_lower_limit = QtWidgets.QLineEdit(self.layoutWidget9)
        self.dmps_highband_lower_limit.setEnabled(False)
        self.dmps_highband_lower_limit.setObjectName("dmps_highband_lower_limit")
        self.gridLayout_11.addWidget(self.dmps_highband_lower_limit, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_20.setEnabled(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_21.setEnabled(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 1, 0, 1, 1)
        self.dmps_lowband_upper_limit = QtWidgets.QLineEdit(self.layoutWidget9)
        self.dmps_lowband_upper_limit.setEnabled(False)
        self.dmps_lowband_upper_limit.setObjectName("dmps_lowband_upper_limit")
        self.gridLayout_11.addWidget(self.dmps_lowband_upper_limit, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 1, 2, 1, 1)
        self.vap_logical = QtWidgets.QCheckBox(self.tab_2)
        self.vap_logical.setGeometry(QtCore.QRect(20, 530, 420, 30))
        self.vap_logical.setChecked(True)
        self.vap_logical.setObjectName("vap_logical")
        self.frameVap = QtWidgets.QFrame(self.tab_2)
        self.frameVap.setGeometry(QtCore.QRect(30, 560, 470, 60))
        self.frameVap.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameVap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVap.setObjectName("frameVap")
        self.widget = QtWidgets.QWidget(self.frameVap)
        self.widget.setGeometry(QtCore.QRect(10, 0, 460, 50))
        self.widget.setObjectName("widget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_51 = QtWidgets.QLabel(self.widget)
        self.label_51.setObjectName("label_51")
        self.gridLayout_13.addWidget(self.label_51, 0, 0, 1, 1)
        self.vap_names = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.vap_names.setFont(font)
        self.vap_names.setObjectName("vap_names")
        self.gridLayout_13.addWidget(self.vap_names, 0, 1, 1, 1)
        self.butVapourNames = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.butVapourNames.setFont(font)
        self.butVapourNames.setObjectName("butVapourNames")
        self.gridLayout_13.addWidget(self.butVapourNames, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget)
        self.label_50.setObjectName("label_50")
        self.gridLayout_13.addWidget(self.label_50, 1, 0, 1, 1)
        self.vap_props = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.vap_props.setFont(font)
        self.vap_props.setObjectName("vap_props")
        self.gridLayout_13.addWidget(self.vap_props, 1, 1, 1, 1)
        self.butVapour = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.butVapour.setFont(font)
        self.butVapour.setObjectName("butVapour")
        self.gridLayout_13.addWidget(self.butVapour, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_5 = QtWidgets.QFrame(self.tab_5)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 911, 531))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MonitorWindow = QtWidgets.QPlainTextEdit(self.frame_5)
        self.MonitorWindow.setGeometry(QtCore.QRect(10, 10, 891, 511))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.MonitorWindow.setFont(font)
        self.MonitorWindow.setAcceptDrops(False)
        self.MonitorWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.MonitorWindow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MonitorWindow.setUndoRedoEnabled(False)
        self.MonitorWindow.setReadOnly(True)
        self.MonitorWindow.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.MonitorWindow.setBackgroundVisible(False)
        self.MonitorWindow.setObjectName("MonitorWindow")
        self.frameStart = QtWidgets.QFrame(self.tab_5)
        self.frameStart.setGeometry(QtCore.QRect(240, 560, 251, 71))
        self.frameStart.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStart.setObjectName("frameStart")
        self.startButton = QtWidgets.QPushButton(self.frameStart)
        self.startButton.setGeometry(QtCore.QRect(10, 20, 230, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.frameStop = QtWidgets.QFrame(self.tab_5)
        self.frameStop.setEnabled(True)
        self.frameStop.setGeometry(QtCore.QRect(510, 559, 261, 71))
        self.frameStop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameStop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStop.setObjectName("frameStop")
        self.stopButton = QtWidgets.QPushButton(self.frameStop)
        self.stopButton.setEnabled(True)
        self.stopButton.setGeometry(QtCore.QRect(20, 20, 200, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.tabWidget.addTab(self.tab_5, "")
        self.printButton = QtWidgets.QPushButton(self.MainFrame)
        self.printButton.setGeometry(QtCore.QRect(100, 680, 221, 25))
        self.printButton.setObjectName("printButton")
        self.saveButton = QtWidgets.QPushButton(self.MainFrame)
        self.saveButton.setGeometry(QtCore.QRect(370, 680, 221, 25))
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(self.MainFrame)
        self.loadButton.setGeometry(QtCore.QRect(640, 680, 221, 25))
        self.loadButton.setObjectName("loadButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionQuit_Ctrl_Q = QtWidgets.QAction(MainWindow)
        self.actionQuit_Ctrl_Q.setObjectName("actionQuit_Ctrl_Q")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionQuit_Ctrl_Q)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        __sortingEnabled = self.names_sel.isSortingEnabled()
        self.names_sel.setSortingEnabled(False)
        self.names_sel.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "<select variables from next tab>", None, -1))
        self.names_sel.setSortingEnabled(__sortingEnabled)
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Selected input variables:", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Modules in use", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "More features in Advanced", None, -1))
        self.checkBox_che.setText(QtWidgets.QApplication.translate("MainWindow", "Use Chemistry", None, -1))
        self.checkBox_acd.setText(QtWidgets.QApplication.translate("MainWindow", "Use ACDC", None, -1))
        self.checkBox_aer.setText(QtWidgets.QApplication.translate("MainWindow", "Use Aerosols", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Model run options", None, -1))
        self.label_2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Total simulation time in decimal hours", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Runtime (h)", None, -1))
        self.label_5.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Used for calculation of correct Julian day", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Batch name", None, -1))
        self.case_name.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Group name, output is saved under directory named after this.", None, -1))
        self.label_6.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Group name, Output is saved under directory named after this", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Run name", None, -1))
        self.run_name.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Run name, output is saved under directory named after this, locating in Batch name directory.", None, -1))
        self.label_7.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Run name, output is saved under directory named after this, locating in Batch name directory.", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.dateEdit.setDisplayFormat(QtWidgets.QApplication.translate("MainWindow", "yyyy-MM-dd", None, -1))
        self.label_8.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Description of the run, max 1000 characters. This will be saved in all output files.", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Desciption", None, -1))
        self.description.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Description of the run, max 1000 characters. This will be saved in all output files.", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "Aerosol structure", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Number of bins", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "PSD scheme", None, -1))
        self.psd_mode.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Lukas basic", None, -1))
        self.psd_mode.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Lukas advanced", None, -1))
        self.psd_mode.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Lukas premium", None, -1))
        self.use_dmps.setText(QtWidgets.QApplication.translate("MainWindow", "dmps", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Particle size range (m):", None, -1))
        self.min_particle_diam.setText(QtWidgets.QApplication.translate("MainWindow", "1e-9", None, -1))
        self.max_particle_diam.setText(QtWidgets.QApplication.translate("MainWindow", "1e-6", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "Read in BG particles for*", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "hours", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "*) if BG particle file is defined", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "Paths and files", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "I/O directories, absolute or relative to executable", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "Common input path", None, -1))
        self.browseCommonIn.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "Common output path", None, -1))
        self.browseCommonOut.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "ENV input", None, -1))
        self.browseEnv.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "MCM input", None, -1))
        self.browseMcm.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("MainWindow", "BG particles", None, -1))
        self.browsePar.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", "Extra particles", None, -1))
        self.browseXtr.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("MainWindow", "Input files (relative to common input path if given)", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Print every:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "s", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Save every:", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "s", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "or", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "samples", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "General options", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("MainWindow", "Select input:", None, -1))
        self.butMoveToSelVars.setText(QtWidgets.QApplication.translate("MainWindow", "<---", None, -1))
        self.selected_vars.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Variable(IND)", None, -1))
        self.selected_vars.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Column", None, -1))
        self.selected_vars.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Multiply", None, -1))
        self.selected_vars.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Shift", None, -1))
        self.selected_vars.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Use PM", None, -1))
        self.selected_vars.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "unit", None, -1))
        self.selected_vars.horizontalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Ind", None, -1))
        self.butRemoveSelVars.setText(QtWidgets.QApplication.translate("MainWindow", "--->", None, -1))
        self.label_60.setText(QtWidgets.QApplication.translate("MainWindow", "Move to selected", None, -1))
        self.label_61.setText(QtWidgets.QApplication.translate("MainWindow", "Remove selected", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Input variables", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Linear", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Logarithmic", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Width", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Peaktime", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("MainWindow", "Ang.freq", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("MainWindow", "Phase", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "Amplitude", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("MainWindow", "Minimum", None, -1))
        self.label_59.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum", None, -1))
        __sortingEnabled = self.names_sel_2.isSortingEnabled()
        self.names_sel_2.setSortingEnabled(False)
        self.names_sel_2.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "<select variables from next tab>", None, -1))
        self.names_sel_2.setSortingEnabled(__sortingEnabled)
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Selected input variables:", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "Save current values to selected", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Copy current", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "Paste to current", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Function creator", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Model timestep", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "seconds", None, -1))
        self.acdc_solve_ss.setText(QtWidgets.QApplication.translate("MainWindow", "Solve ACDC to Steady State (might be necessary, if acid/base concentrations vary rapidly)", None, -1))
        self.model_h2so4.setText(QtWidgets.QApplication.translate("MainWindow", "Replace any H2SO4 input with modelled (requires corresponding chemistry).", None, -1))
        self.condensation.setText(QtWidgets.QApplication.translate("MainWindow", "Aerosols includes condensation. If unchecked, condensation is not considered.", None, -1))
        self.coagulation.setText(QtWidgets.QApplication.translate("MainWindow", "Aerosols includes coagulation. If unchecked, coagulation is not considered.", None, -1))
        self.use_dmps_special.setText(QtWidgets.QApplication.translate("MainWindow", "Use background particles for the whole run", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Before the simulation starts, pause program for ", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "seconds (0=wait indefinitely, negative=don\'t wait)", None, -1))
        self.python.setText(QtWidgets.QApplication.translate("MainWindow", "After the run is finished, offer to plot some of the output (with Python)", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Location", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Latitude", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Longitude", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Negative values =", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "East and South", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Formation rates", None, -1))
        self.resolve_base.setText(QtWidgets.QApplication.translate("MainWindow", "Solve bases", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Precision", None, -1))
        self.fill_formation_with.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Fixed ratio", None, -1))
        self.fill_formation_with.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Fill with DMA", None, -1))
        self.fill_formation_with.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Fill with NH3", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Use fixed ratio or fill gap from ACDC", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Ratio", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Miscellanious", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Location", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Latitude", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "Longitude", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Surface albedo", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Highband lower limit (m)", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Larger (diam) particles will be replaced with background particles.", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Lowband upper limit (m)", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Smaller (diam) particles will be replaced with background particles.", None, -1))
        self.vap_logical.setText(QtWidgets.QApplication.translate("MainWindow", "Vapour properties in use", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("MainWindow", "Path to vapour names", None, -1))
        self.vap_names.setText(QtWidgets.QApplication.translate("MainWindow", "Vapour_names.dat", None, -1))
        self.butVapourNames.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.label_50.setText(QtWidgets.QApplication.translate("MainWindow", "Path to vapour properties    ", None, -1))
        self.vap_props.setText(QtWidgets.QApplication.translate("MainWindow", "Vapour_properties.dat", None, -1))
        self.butVapour.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Advanced", None, -1))
        self.startButton.setText(QtWidgets.QApplication.translate("MainWindow", "Run with current settings", None, -1))
        self.stopButton.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtWidgets.QApplication.translate("MainWindow", "Process Monitor", None, -1))
        self.printButton.setText(QtWidgets.QApplication.translate("MainWindow", "Print only model input", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save INITFILE", None, -1))
        self.loadButton.setText(QtWidgets.QApplication.translate("MainWindow", "Load INITFILE", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionSave_2.setText(QtWidgets.QApplication.translate("MainWindow", "Save current settings", None, -1))
        self.actionSave_2.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionQuit_Ctrl_Q.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.actionQuit_Ctrl_Q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Quit without save", None, -1))
        self.actionQuit_Ctrl_Q.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open settings file", None, -1))
        self.actionOpen.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionPrint.setText(QtWidgets.QApplication.translate("MainWindow", "Print settings", None, -1))
        self.actionPrint.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+P", None, -1))

