# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev/Input.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(225, 93)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input = QtWidgets.QSpinBox(Dialog)
        self.input.setMinimum(-1)
        self.input.setMaximum(1000000)
        self.input.setProperty("value", 0)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setToolTip(_translate("Dialog", "Only effective when ARCA is \n"
"called from the command line:\n"
"0=don\'t wait, negative=wait indefinitely"))
        self.label.setText(_translate("Dialog", "Pause before main loop for"))
        self.input.setToolTip(_translate("Dialog", "Only effective when ARCA is \n"
"called from the command line:\n"
"0=don\'t wait, negative=wait indefinitely"))
        self.input.setSuffix(_translate("Dialog", " sec"))
