# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev/VDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(529, 433)
        Dialog.setMinimumSize(QtCore.QSize(529, 328))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(9, 20, 510, 140))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox.setObjectName("groupBox")
        self.useAMG = QtWidgets.QRadioButton(self.groupBox)
        self.useAMG.setGeometry(QtCore.QRect(11, 28, 166, 20))
        self.useAMG.setChecked(True)
        self.useAMG.setObjectName("useAMG")
        self.useUMan = QtWidgets.QRadioButton(self.groupBox)
        self.useUMan.setGeometry(QtCore.QRect(183, 28, 205, 20))
        self.useUMan.setObjectName("useUMan")
        self.smilesFile = QtWidgets.QFrame(self.groupBox)
        self.smilesFile.setEnabled(False)
        self.smilesFile.setGeometry(QtCore.QRect(10, 50, 491, 81))
        self.smilesFile.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.smilesFile.setFrameShadow(QtWidgets.QFrame.Plain)
        self.smilesFile.setObjectName("smilesFile")
        self.lineEdit = QtWidgets.QLineEdit(self.smilesFile)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 240, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.massSmilesButton = QtWidgets.QToolButton(self.smilesFile)
        self.massSmilesButton.setGeometry(QtCore.QRect(390, 10, 80, 25))
        self.massSmilesButton.setObjectName("massSmilesButton")
        self.label = QtWidgets.QLabel(self.smilesFile)
        self.label.setGeometry(QtCore.QRect(20, 17, 110, 15))
        self.label.setObjectName("label")
        self.usePRAM = QtWidgets.QCheckBox(self.smilesFile)
        self.usePRAM.setGeometry(QtCore.QRect(3, 53, 138, 20))
        self.usePRAM.setObjectName("usePRAM")
        self.PRAMframe = QtWidgets.QFrame(self.smilesFile)
        self.PRAMframe.setEnabled(False)
        self.PRAMframe.setGeometry(QtCore.QRect(140, 50, 340, 31))
        self.PRAMframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PRAMframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PRAMframe.setObjectName("PRAMframe")
        self.PramButton = QtWidgets.QToolButton(self.PRAMframe)
        self.PramButton.setGeometry(QtCore.QRect(250, 0, 80, 25))
        self.PramButton.setObjectName("PramButton")
        self.pramFile = QtWidgets.QLineEdit(self.PRAMframe)
        self.pramFile.setGeometry(QtCore.QRect(0, 0, 240, 25))
        self.pramFile.setObjectName("pramFile")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 180, 510, 91))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 79))
        self.groupBox_2.setObjectName("groupBox_2")
        self.limPsat = QtWidgets.QLineEdit(self.groupBox_2)
        self.limPsat.setGeometry(QtCore.QRect(331, 27, 149, 25))
        self.limPsat.setObjectName("limPsat")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(11, 30, 305, 16))
        self.label_2.setObjectName("label_2")
        self.saveElements = QtWidgets.QCheckBox(self.groupBox_2)
        self.saveElements.setGeometry(QtCore.QRect(12, 60, 242, 20))
        self.saveElements.setChecked(True)
        self.saveElements.setObjectName("saveElements")
        self.filterWChem = QtWidgets.QCheckBox(self.groupBox_2)
        self.filterWChem.setGeometry(QtCore.QRect(260, 60, 241, 20))
        self.filterWChem.setChecked(True)
        self.filterWChem.setObjectName("filterWChem")
        self.groupBox_21 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_21.setGeometry(QtCore.QRect(9, 290, 511, 80))
        self.groupBox_21.setMinimumSize(QtCore.QSize(0, 58))
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout.setObjectName("gridLayout")
        self.VapourPath = QtWidgets.QLineEdit(self.groupBox_21)
        self.VapourPath.setMinimumSize(QtCore.QSize(0, 0))
        self.VapourPath.setObjectName("VapourPath")
        self.gridLayout.addWidget(self.VapourPath, 0, 0, 1, 1)
        self.browseVapourPath = QtWidgets.QToolButton(self.groupBox_21)
        self.browseVapourPath.setObjectName("browseVapourPath")
        self.gridLayout.addWidget(self.browseVapourPath, 0, 1, 1, 1)
        self.createVapourFileButton = QtWidgets.QPushButton(Dialog)
        self.createVapourFileButton.setGeometry(QtCore.QRect(80, 390, 160, 27))
        self.createVapourFileButton.setObjectName("createVapourFileButton")
        self.VapourClose = QtWidgets.QPushButton(Dialog)
        self.VapourClose.setGeometry(QtCore.QRect(340, 390, 79, 27))
        self.VapourClose.setObjectName("VapourClose")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create vapour file"))
        self.groupBox.setTitle(_translate("Dialog", "Source of compound, mass and saturation vapour pressures"))
        self.useAMG.setToolTip(_translate("Dialog", "Uses computed values from AMG database. These are\n"
"saturation vapour pressures calculated using Nannolaal \n"
"et. al (2004) and (2008). "))
        self.useAMG.setText(_translate("Dialog", "use AMG server (faster)"))
        self.useUMan.setText(_translate("Dialog", "Fetch from UManProp (slower)"))
        self.lineEdit.setToolTip(_translate("Dialog", "This is the mass file from mcm ( \"Molecular Weights for all species in a subset\")  which contains compound name, mass and SMILES codes of the compounds."))
        self.massSmilesButton.setText(_translate("Dialog", "Browse"))
        self.label.setToolTip(_translate("Dialog", "This is the mass file from mcm ( \"Molecular Weights for all species in a subset\")  which contains compound name, mass and SMILES codes of the compounds."))
        self.label.setText(_translate("Dialog", "mass/SMILES file:"))
        self.usePRAM.setToolTip(_translate("Dialog", "Since MCM does not contain HOMs, additional file can be inserted here.\n"
"It should be of type text, and have the structure:\n"
"\"compound\"  \"mass\" \"parameter a\" \"parameter b\""))
        self.usePRAM.setText(_translate("Dialog", "Use PRAM from ->"))
        self.PramButton.setText(_translate("Dialog", "Browse"))
        self.pramFile.setPlaceholderText(_translate("Dialog", "If left empty, pick from AMG server"))
        self.groupBox_2.setTitle(_translate("Dialog", "Options"))
        self.limPsat.setToolTip(_translate("Dialog", "Usually there is no point considering all vapours as they are not condensing.\n"
"A safe limit is to consider only those vapours whose Psat is less than 1e-6 atm.\n"
"Leavy emoty to include all vapours."))
        self.limPsat.setText(_translate("Dialog", "1e-6"))
        self.label_2.setToolTip(_translate("Dialog", "Usually there is no point considering all vapours as they are not condensing.\n"
"A safe limit is to consider only those vapours whose Psat is less than 1e-6 atm.\n"
"Leavy emoty to include all vapours."))
        self.label_2.setText(_translate("Dialog", "Only include vapous with Psat lower than (in ATM):"))
        self.saveElements.setToolTip(_translate("Dialog", "Choosing this option will save the elemental contents in a file \n"
"\"elements_[filename]\" where [filename] is the same and same \n"
"location as in \"Save to\". "))
        self.saveElements.setText(_translate("Dialog", "Save elemental content"))
        self.filterWChem.setToolTip(_translate("Dialog", "Choosing this option will leave out all the compounds that are \n"
"not in the current chemistry. This could be practical in analysis \n"
"but is not strictly necessary for ARCA. "))
        self.filterWChem.setText(_translate("Dialog", "Filter with current chemistry"))
        self.groupBox_21.setTitle(_translate("Dialog", "Save to:"))
        self.browseVapourPath.setText(_translate("Dialog", "Browse"))
        self.createVapourFileButton.setText(_translate("Dialog", "Create Vapour file"))
        self.VapourClose.setText(_translate("Dialog", "Close"))
