! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : second_Initialize.f90
! Equation file        : second.kpp3
! Output root filename : second
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE second_Initialize

  USE second_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE second_Global

  USE second_Parameters

  INTEGER :: i
  REAL(kind=dp) :: x

! ~~~ Define scale factor for units
  CFACTOR = 1.000000e+00_dp

! ~~~ Zero C array
  C = 0.0_dp

! ~~~ Set initial species concentrations

! Begin constant rate coefficients
  RCONST(23) = 2e-11
  RCONST(27) = 4e-12
  RCONST(33) = 6e-06
  RCONST(34) = 0.0004
  RCONST(51) = 1.2e-12
  RCONST(63) = 6.65e-11
  RCONST(71) = 3.12e-13
  RCONST(73) = 4.23e-12
  RCONST(75) = 4.29e-11
  RCONST(85) = 2.1e-11
  RCONST(86) = 2.49e-11
  RCONST(88) = 2.14e-11
  RCONST(97) = 5.99e-12
  RCONST(100) = 2.69e-12
  RCONST(102) = 1.23e-11
  RCONST(116) = 2.73e-12
  RCONST(118) = 6.19e-12
  RCONST(138) = 1.58e-11
  RCONST(140) = 1.23e-11
  RCONST(149) = 2.23e-12
  RCONST(150) = 5.77e-11
  RCONST(152) = 1.88e-11
  RCONST(155) = 2.45e-11
  RCONST(163) = 3.74e-12
  RCONST(164) = 7.34e-12
  RCONST(170) = 5.5e-16
  RCONST(174) = 4e-12
  RCONST(179) = 3e-14
  RCONST(181) = 3.7e-12
  RCONST(192) = 2.91e-11
  RCONST(203) = 8.39e-12
  RCONST(217) = 7.19e-11
  RCONST(218) = 7.55e-11
  RCONST(220) = 8.33e-11
  RCONST(233) = 1.27e-11
  RCONST(234) = 1.63e-11
  RCONST(236) = 2.41e-11
  RCONST(241) = 3.39e-11
  RCONST(243) = 8e-13
  RCONST(244) = 1.44e-11
  RCONST(256) = 5.5e-12
  RCONST(258) = 1.83e-11
  RCONST(262) = 2e-14
  RCONST(322) = 2.88e-12
  RCONST(324) = 5.37e-12
  RCONST(326) = 7.111e-11
  RCONST(328) = 2.25e-11
  RCONST(330) = 7.03e-11
  RCONST(331) = 3.66e-12
  RCONST(333) = 9.73e-12
  RCONST(336) = 1.3e-11
  RCONST(338) = 1.05e-11
  RCONST(340) = 2.05e-11
  RCONST(342) = 8.69e-11
  RCONST(344) = 2.75e-11
  RCONST(346) = 8.01e-11
  RCONST(348) = 1.2e-10
  RCONST(350) = 6.65e-12
  RCONST(352) = 7.67e-12
  RCONST(354) = 7.2e-12
  RCONST(356) = 1.69e-11
  RCONST(358) = 3.78e-11
  RCONST(360) = 2.41e-11
  RCONST(362) = 7.66e-11
  RCONST(378) = 2.29e-11
  RCONST(380) = 2.7e-11
  RCONST(382) = 2.39e-11
  RCONST(384) = 3.23e-11
  RCONST(389) = 3.55e-11
  RCONST(390) = 7.6e-12
  RCONST(392) = 2.65e-11
  RCONST(394) = 2.34e-11
  RCONST(408) = 2.64e-11
  RCONST(418) = 3.22e-12
  RCONST(420) = 1.33e-11
  RCONST(423) = 6.7e-11
  RCONST(450) = 6.6e-12
  RCONST(452) = 1.02e-11
  RCONST(454) = 1.29e-11
  RCONST(456) = 3.45e-11
  RCONST(458) = 7.49e-11
  RCONST(459) = 8.83e-13
  RCONST(461) = 4.75e-12
  RCONST(463) = 1.01e-11
  RCONST(465) = 1.33e-10
  RCONST(475) = 3.64e-12
  RCONST(477) = 3.28e-11
  RCONST(478) = 1.49e-11
  RCONST(479) = 8.18e-12
  RCONST(489) = 6.87e-12
  RCONST(491) = 400000
  RCONST(500) = 1.23e-11
  RCONST(502) = 5.55e-12
  RCONST(508) = 40000
  RCONST(520) = 5.94e-12
  RCONST(522) = 8.03e-12
  RCONST(524) = 3.25e-11
  RCONST(526) = 1.25e-12
  RCONST(539) = 1.85e-11
  RCONST(540) = 1.32e-11
  RCONST(542) = 1.68e-11
  RCONST(551) = 9.87e-11
  RCONST(553) = 1.03e-10
  RCONST(554) = 9.91e-11
  RCONST(564) = 9.6e-11
  RCONST(566) = 1.27e-10
  RCONST(567) = 1.09e-10
  RCONST(568) = 1.19e-10
  RCONST(576) = 1.26e-11
  RCONST(578) = 7.06e-11
  RCONST(579) = 6.72e-11
  RCONST(606) = 2.85e-11
  RCONST(608) = 2.23e-11
  RCONST(610) = 3.01e-11
  RCONST(612) = 6.28e-11
  RCONST(614) = 2e-10
  RCONST(616) = 2.66e-11
  RCONST(618) = 5.93e-11
  RCONST(620) = 1.26e-10
  RCONST(640) = 2.37e-11
  RCONST(650) = 2.92e-12
  RCONST(652) = 6.55e-12
  RCONST(657) = 9.61e-12
  RCONST(679) = 5.47e-11
  RCONST(682) = 4.45e-11
  RCONST(684) = 5.47e-11
  RCONST(685) = 5.56e-12
  RCONST(687) = 5.7e-12
  RCONST(689) = 9.16e-12
  RCONST(691) = 2.36e-11
  RCONST(693) = 1.29e-11
  RCONST(695) = 1.51e-11
  RCONST(697) = 1e-10
  RCONST(700) = 7e-14
  RCONST(701) = 1.2e-15
  RCONST(702) = 1e-14
  RCONST(703) = 1e-15
  RCONST(709) = 5.77e-11
  RCONST(711) = 1.12e-12
  RCONST(742) = 2.52e-11
  RCONST(744) = 3e-11
  RCONST(746) = 2.69e-11
  RCONST(748) = 2.56e-11
  RCONST(750) = 3.61e-11
  RCONST(752) = 2.86e-11
  RCONST(754) = 4.96e-11
  RCONST(756) = 8.35e-11
  RCONST(758) = 8e-11
  RCONST(760) = 4.33e-11
  RCONST(762) = 1.1e-10
  RCONST(764) = 6.99e-11
  RCONST(796) = 7.82e-12
  RCONST(798) = 1.04e-11
  RCONST(800) = 1.7e-11
  RCONST(802) = 1.09e-11
  RCONST(804) = 1.86e-11
  RCONST(805) = 7.29e-12
  RCONST(806) = 7.89e-12
  RCONST(807) = 7.42e-12
  RCONST(808) = 1.75e-11
  RCONST(810) = 6.77e-12
  RCONST(812) = 6.69e-11
  RCONST(814) = 2.63e-11
  RCONST(839) = 2.96e-12
  RCONST(841) = 9.65e-12
  RCONST(842) = 6.57e-12
  RCONST(844) = 1.27e-11
  RCONST(846) = 3.31e-11
  RCONST(848) = 7.46e-11
  RCONST(851) = 3.29e-12
  RCONST(877) = 3.38e-11
! End constant rate coefficients

! Begin inlined code from F90_INIT

! End inlined code from F90_INIT

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE second_Initialize

