! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : second_Rates.f90
! Equation file        : second.kpp3
! Output root filename : second
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE second_Rates

  USE second_Parameters
  USE second_Global
  IMPLICIT NONE
  INTEGER, PARAMETER :: ASSOC = 1, DISSOC = 2

  PRIVATE :: ARR_abc_dp, ARR_abc_sp
  INTERFACE ARR_abc
     MODULE PROCEDURE ARR_abc_dp
     MODULE PROCEDURE ARR_abc_sp
  END INTERFACE ARR_abc

  PRIVATE :: ARR_ab_dp, ARR_ab_sp
  INTERFACE ARR_ab
     MODULE PROCEDURE ARR_ab_dp
     MODULE PROCEDURE ARR_ab_sp
  END INTERFACE ARR_ab

  PRIVATE :: ARR_ac_dp, ARR_ac_sp
  INTERFACE ARR_ac
     MODULE PROCEDURE ARR_ac_dp
     MODULE PROCEDURE ARR_ac_sp
  END INTERFACE ARR_ac

  PRIVATE :: EP2_dp, EP2_sp
  INTERFACE EP2
     MODULE PROCEDURE EP2_dp
     MODULE PROCEDURE EP2_sp
  END INTERFACE EP2

  PRIVATE :: EP3_dp, EP3_sp
  INTERFACE EP3
     MODULE PROCEDURE EP3_dp
     MODULE PROCEDURE EP3_sp
  END INTERFACE EP3

  PRIVATE :: FALL_dp, FALL_sp
  INTERFACE FALL
     MODULE PROCEDURE FALL_dp
     MODULE PROCEDURE FALL_sp
  END INTERFACE FALL

  PRIVATE :: k3rd_jpl_dp, k3rd_jpl_sp
  INTERFACE k3rd_jpl
     MODULE PROCEDURE k3rd_jpl_dp
     MODULE PROCEDURE k3rd_jpl_sp
  END INTERFACE k3rd_jpl

  PRIVATE :: k3rd_jpl_activation_dp, k3rd_jpl_activation_sp
  INTERFACE  k3rd_jpl_activation
     MODULE PROCEDURE  k3rd_jpl_activation_dp
     MODULE PROCEDURE  k3rd_jpl_activation_sp
  END INTERFACE  k3rd_jpl_activation

  PRIVATE :: k3rd_iupac_dp, k3rd_iupac_sp
  INTERFACE k3rd_iupac
     MODULE PROCEDURE k3rd_iupac_dp
     MODULE PROCEDURE k3rd_iupac_sp
  END INTERFACE k3rd_iupac

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!
!  NOTE: For computational efficiency, we have created duplicate rate law
!  routines here that take either all single precision or all double precision
!  arguments.  Explicit casts to DBLE are skipped in the functions that take
!  all double precision arguments (as this removes unneeded computations).
!
!  These functions are overloaded by INTERFACE statements, which are located
!  in file UserRateLawsInterfaces.f90.  The UserRateLawsInterfaces.f90 file
!  will be in-lined into the top of the second_Rates module.
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  FUNCTION ARR_abc_dp( a0, b0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0, c0 (dp args)
    REAL(dp), INTENT(IN) :: a0, b0, c0
    REAL(kind=dp) :: k
    k = a0 * EXP(-b0/TEMP) * (TEMP/300.0_dp)**C0
  END FUNCTION ARR_abc_dp

  FUNCTION ARR_abc_sp( a0, b0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0, c0 (sp args)
    REAL(sp), INTENT(IN) :: a0, b0, c0
    REAL(kind=dp) :: k
    k = DBLE(a0) * EXP(-DBLE(b0)/TEMP) * (TEMP/300.0_dp)**DBLE(c0)
  END FUNCTION ARR_abc_sp

  !---------------------------------------------------------------------------

  FUNCTION ARR_ab_dp( a0, b0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0 (dp args)
    REAL(dp), INTENT(IN) :: a0, b0
    REAL(kind=dp) :: k
    k = a0 * EXP(-b0/TEMP)
  END FUNCTION ARR_ab_dp

  FUNCTION ARR_ab_sp( a0, b0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0 (sp args)
    REAL(sp), INTENT(IN) :: a0, b0
    REAL(kind=dp) :: k
    k = DBLE(a0) * EXP(-DBLE(b0)/TEMP)
  END FUNCTION ARR_ab_sp

  !---------------------------------------------------------------------------

  FUNCTION ARR_ac_dp( a0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, c0 (dp args)
    REAL(dp), INTENT(IN) :: a0, c0
    REAL(kind=dp) :: k
    k = a0 * (TEMP/300.0_dp)**C0
  END FUNCTION ARR_ac_dp

  FUNCTION ARR_ac_sp( a0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, c0 (sp args)
    REAL(sp), INTENT(IN) :: a0, c0
    REAL(kind=dp) :: k
    k = DBLE(a0) * (TEMP/300.0_dp)**DBLE(c0)
  END FUNCTION ARR_ac_sp

  !---------------------------------------------------------------------------

  FUNCTION EP2_dp( a0, c0, a2, c2, a3, c3 ) RESULT( k )
    ! EP2 function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a0, c0, a2, c2, a3, c3
    REAL(dp) :: k0, k2, k3
    REAL(kind=dp) :: k
    k0 = a0 * EXP(-c0/temp)
    k2 = a2 * EXP(-c2/temp)
    k3 = a3 * EXP(-c3/temp)
    k3 = k3 * CFACTOR * 1.0E6_dp
    k  = k0 + k3/(1.0_dp + k3/k2)
  END FUNCTION EP2_dp

  FUNCTION EP2_sp( a0, c0, a2, c2, a3, c3 ) RESULT( k )
    ! EP2 function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a0, c0, a2, c2, a3, c3
    REAL(dp) :: k0, k2, k3
    REAL(kind=dp) :: k
    k0 = DBLE(a0) * EXP(-DBLE(c0)/TEMP)
    k2 = DBLE(a2) * EXP(-DBLE(c2)/TEMP)
    k3 = DBLE(a3) * EXP(-DBLE(c3)/TEMP)
    k3 = k3 * CFACTOR * 1.0E6_dp
    k  = k0 + K3/(1.0_dp + k3/k2)
  END FUNCTION EP2_sp

  !---------------------------------------------------------------------------

  FUNCTION EP3_dp( a1, c1, a2, c2) RESULT( k )
    ! EP3 function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a1, c1, a2, c2
    REAL(dp) :: k1, k2
    REAL(kind=dp) :: k
    k1 = a1 * EXP(-c1/TEMP)
    k2 = a2 * EXP(-c2/TEMP)
    k  = k1 + k2*(1.0E6_dp * CFACTOR)
  END FUNCTION EP3_dp

  FUNCTION EP3_sp( a1, c1, a2, c2 ) RESULT( k )
    ! EP3 function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a1, c1, a2, c2
    REAL(dp) :: k1, k2
    REAL(kind=dp) :: k
    k1 = DBLE(a1) * EXP(-DBLE(c1)/TEMP)
    k2 = DBLE(a2) * EXP(-DBLE(c2)/TEMP)
    k  = k1 + k2*(1.0E6_dp * CFACTOR)
  END FUNCTION EP3_sp

  !---------------------------------------------------------------------------

  FUNCTION FALL_dp( a0, b0, c0, a1, b1, c1, cf ) RESULT( k )
    ! FALL function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a0, b0, c0, a1, b1, c1, cf
    REAL(dp) :: k0, k1
    REAL(kind=dp) :: k
    k0 = a0 * EXP(-b0/TEMP) * (TEMP/300.0_dp)**c0
    k1 = a1 * EXP(-b1/TEMP) * (TEMP/300.0_dp)**c1
    k0 = k0 * CFACTOR * 1.0E6_dp
    k1 = k0 / k1
    k  = (k0/(1.0_dp+k1)) * cf**(1.0_dp/(1.0_dp+(LOG10(k1))**2))
  END FUNCTION FALL_dp

  FUNCTION FALL_sp( a0, b0, c0, a1, b1, c1, cf ) RESULT( k )
    ! FALL function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a0, b0, c0, a1, b1, c1, cf
    REAL(dp) :: k0, k1
    REAL(kind=dp) :: k
    k0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
    k1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
    k0 = k0 * CFACTOR * 1.0E6_dp
    k1 = k0 / k1
    k  = (k0/(1.0_dp+k1)) * DBLE(cf)**(1.0_dp/(1.0_dp+(LOG10(k1))**2))
  END FUNCTION FALL_sp

  !---------------------------------------------------------------------------

  ! JPL (jpldataeval.jpl.nasa.gov) three-body reaction formula:
  
  REAL(dp) FUNCTION k3rd_jpl_dp(cair,k0_300K,n,kinf_300K,m,fc) ! dp args
    INTRINSIC LOG10
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(dp) :: zt_help, k0_T, kinf_T, k_ratio
    zt_help  = 300._dp/temp
    k0_T     = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T   = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio  = k0_T/kinf_T
    k3rd_jpl_dp = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))
  END FUNCTION k3rd_jpl_dp

  REAL(kind=dp) FUNCTION k3rd_jpl_sp(cair,k0_300K,n,kinf_300K,m,fc) ! sp args
    INTRINSIC LOG10
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(sp) :: zt_help, k0_T, kinf_T, k_ratio
    zt_help  = 300._dp/temp
    k0_T     = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T   = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio  = k0_T/kinf_T
    k3rd_jpl_sp = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))
  END FUNCTION k3rd_jpl_sp

  ! --------------------------------------------------------------------------

  ! JPL (jpldataeval.jpl.nasa.gov) termolecular chemical activation reaction:

  FUNCTION k3rd_jpl_activation_dp(cair,k0_298K,n,kinf_298K,m,A,B) ! dp args
    INTRINSIC :: LOG10
    REAL(dp), DIMENSION(2) :: k3rd_jpl_activation_dp
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_298K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_298K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: A         ! for k_int
    REAL(dp), INTENT(IN) :: B         ! for k_int
    REAL(dp)             :: zt_help, k0_TM, kinf_T, k_ratio, k_f, k_int, k_fCA
    zt_help = 298./temp
    k0_TM   = k0_298K   * zt_help**n * cair ! k_0   at current T * M
    kinf_T  = kinf_298K * zt_help**m        ! k_inf at current T
    k_ratio = k0_TM/kinf_T
    k_f     = k0_TM/(1.+k_ratio)*0.6**(1./(1.+LOG10(k_ratio)**2))
    k_int   = A * exp(-B/temp)
    k_fCA   = k_int * (1. - k_f/kinf_T)
    k3rd_jpl_activation_dp(ASSOC)  = k_f
    k3rd_jpl_activation_dp(DISSOC) = k_fCA
  END FUNCTION k3rd_jpl_activation_dp

  FUNCTION k3rd_jpl_activation_sp(cair,k0_298K,n,kinf_298K,m,A,B) ! sp args
    INTRINSIC :: LOG10
    REAL(kind=dp), DIMENSION(2) :: k3rd_jpl_activation_sp
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_298K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_298K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: A         ! for k_int
    REAL(sp), INTENT(IN) :: B         ! for k_int
    REAL(sp)             :: zt_help, k0_TM, kinf_T, k_ratio, k_f, k_int, k_fCA
    zt_help = 298./temp
    k0_TM   = k0_298K   * zt_help**n * cair ! k_0   at current T * M
    kinf_T  = kinf_298K * zt_help**m        ! k_inf at current T
    k_ratio = k0_TM/kinf_T
    k_f     = k0_TM/(1.+k_ratio)*0.6**(1./(1.+LOG10(k_ratio)**2))
    k_int   = A * exp(-B/temp)
    k_fCA   = k_int * (1. - k_f/kinf_T)
    k3rd_jpl_activation_sp(ASSOC)  = k_f
    k3rd_jpl_activation_sp(DISSOC) = k_fCA
  END FUNCTION k3rd_jpl_activation_sp

  ! --------------------------------------------------------------------------

  ! IUPAC (iupac.pole-ether.fr) three-body reaction formula:

  REAL(dp) FUNCTION k3rd_iupac_dp(cair,k0_300K,n,kinf_300K,m,fc) ! dp args
    INTRINSIC :: LOG10
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL(dp)             :: nu        ! N
    REAL(dp)             :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k3rd_iupac_dp = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k3rd_iupac_dp

  REAL(kind=dp) FUNCTION k3rd_iupac_sp(cair,k0_300K,n,kinf_300K,m,fc) ! sp args
    INTRINSIC :: LOG10
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL(sp)             :: nu        ! N
    REAL(sp)             :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k3rd_iupac_sp = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k3rd_iupac_sp

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin inlined code from F90_RATES


! End inlined code from F90_RATES

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
    USE second_Parameters
    USE second_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


SUBROUTINE Update_RCONST ( YIN )

! Begin inlined code from F90_RCONST_USE


  USE second_Constants

! End inlined code from F90_RCONST_USE

! YIN - Optional input concentrations of variable species
  REAL(kind=dp), OPTIONAL :: YIN(NVAR)

! Y - Concentrations of species (local)
  REAL(kind=dp) :: Y(NSPEC)

! Ensure local Y array is filled with variable and constant concentrations
  Y(1:NSPEC) = C(1:NSPEC)

! Update local Y array if variable concentrations are provided
  if (present(YIN)) Y(1:NVAR) = YIN(1:NVAR)



! Begin inlined code from F90_RCONST


  ! Peroxy radicals
  ! WARNING: The following species do not have SMILES strings in the database. 
  !           If any of these are peroxy radicals the RO2 sum will be wrong! 
  ! NA H2SO4
  RO2 = C(ind_CH3O2) + C(ind_BIACETO2) + C(ind_CH3CO3) + C(ind_HCOCH2CO3) + &
    C(ind_CO23C4CO3) + C(ind_HCOCH2O2) + C(ind_HOCH2CO3) + &
    C(ind_CH3COCH2O2) + C(ind_HCOCO3) + C(ind_HMVKAO2) + &
    C(ind_CO2H3CO3) + C(ind_CHOC3COCO3) + C(ind_CHOC3COO2) + &
    C(ind_C312COCO3) + C(ind_CHOCOCH2O2) + C(ind_APINAO2) + &
    C(ind_APINBO2) + C(ind_APINCO2) + C(ind_C96O2) + &
    C(ind_C96CO3) + C(ind_PINALO2) + C(ind_C97O2) + &
    C(ind_C98O2) + C(ind_C614O2) + C(ind_C106O2) + &
    C(ind_C716O2) + C(ind_H3C25C6O2) + C(ind_H3C25C6CO3) + &
    C(ind_H3C2C4CO3) + C(ind_C85O2) + C(ind_C85CO3) + &
    C(ind_C86O2) + C(ind_C511O2) + C(ind_CO235C6CO3) + &
    C(ind_CO235C6O2) + C(ind_NAPINAO2) + C(ind_NAPINBO2) + &
    C(ind_NC101O2) + C(ind_NC102O2) + C(ind_NC71O2) + &
    C(ind_NC72O2) + C(ind_NC61CO3) + C(ind_C720O2) + &
    C(ind_C719O2) + C(ind_C107O2) + C(ind_C109O2) + &
    C(ind_C108O2) + C(ind_C717O2) + C(ind_C89CO3) + &
    C(ind_C920CO3) + C(ind_C920O2) + C(ind_C921O2) + &
    C(ind_C922O2) + C(ind_C621O2) + C(ind_H1C23C4O2) + &
    C(ind_H1C23C4CO3) + C(ind_C89O2) + C(ind_C810O2) + &
    C(ind_C514O2) + C(ind_C811CO3) + C(ind_C811O2) + &
    C(ind_C812O2) + C(ind_C813O2) + C(ind_C516O2) + &
    C(ind_C721O2) + C(ind_C721CO3) + C(ind_C722O2) + &
    C(ind_C44O2)
  CALL define_constants_mcm

! End inlined code from F90_RCONST

  RCONST(1) = (5.6E-34*N2*(TEMP/300.)**(-2.6)*O2+6.0E-34*O2*(TEMP/300.)**(-2.6)*O2)
  RCONST(2) = (8.0E-12*EXP(-2060./TEMP))
  RCONST(3) = (KMT01)
  RCONST(4) = (5.5E-12*EXP(188./TEMP))
  RCONST(5) = (KMT02)
  RCONST(6) = (3.2E-11*EXP(67./TEMP)*O2+2.0E-11*EXP(130./TEMP)*N2)
  RCONST(7) = (1.4E-12*EXP(-1310./TEMP))
  RCONST(8) = (1.4E-13*EXP(-2470./TEMP))
  RCONST(9) = (3.3E-39*EXP(530./TEMP)*O2)
  RCONST(10) = (1.8E-11*EXP(110./TEMP))
  RCONST(11) = (4.50E-14*EXP(-1260./TEMP))
  RCONST(12) = (KMT03)
  RCONST(13) = (2.14E-10*H2O)
  RCONST(14) = (1.70E-12*EXP(-940./TEMP))
  RCONST(15) = (7.7E-12*EXP(-2100./TEMP))
  RCONST(16) = (KMT05)
  RCONST(17) = (2.9E-12*EXP(-160./TEMP))
  RCONST(18) = (2.03E-16*(TEMP/300.)**(4.57)*EXP(693./TEMP))
  RCONST(19) = (4.8E-11*EXP(250./TEMP))
  RCONST(20) = (2.20E-13*KMT06*EXP(600./TEMP)+1.90E-33*M*KMT06*EXP(980./TEMP))
  RCONST(21) = (KMT07)
  RCONST(22) = (KMT08)
! RCONST(23) = constant rate coefficient
  RCONST(24) = (3.45E-12*EXP(270./TEMP))
  RCONST(25) = (KMT09)
  RCONST(26) = (3.2E-13*EXP(690./TEMP)*1.0)
! RCONST(27) = constant rate coefficient
  RCONST(28) = (2.5E-12*EXP(260./TEMP))
  RCONST(29) = (KMT11)
  RCONST(30) = (4.0E-32*EXP(-1000./TEMP)*M)
  RCONST(31) = (KMT12)
  RCONST(32) = (1.3E-12*EXP(-330./TEMP)*O2)
! RCONST(33) = constant rate coefficient
! RCONST(34) = constant rate coefficient
  RCONST(35) = (1.20E-15*H2O)
  RCONST(36) = (J(J_O3_O1D))
  RCONST(37) = (J(J_O3_O3P))
  RCONST(38) = (J(J_H2O2))
  RCONST(39) = (J(J_NO2))
  RCONST(40) = (J(J_NO3_NO))
  RCONST(41) = (J(J_NO3_NO2))
  RCONST(42) = (J(J_HONO))
  RCONST(43) = (J(J_HNO3))
  RCONST(44) = (KMT04)
  RCONST(45) = (KMT10)
  RCONST(46) = (2.3E-12*EXP(360./TEMP)*0.999)
  RCONST(47) = (2.3E-12*EXP(360./TEMP)*0.001)
  RCONST(48) = (7.2E-14*EXP(-1080./TEMP)*O2)
  RCONST(49) = (KMT13)
  RCONST(50) = (KMT14)
! RCONST(51) = constant rate coefficient
  RCONST(52) = (3.8E-13*EXP(780./TEMP)*(1.-1./(1.+498.*EXP(-1160./TEMP))))
  RCONST(53) = (2.*KCH3O2*RO2*7.18*EXP(-885./TEMP))
  RCONST(54) = (2.*KCH3O2*RO2*0.5*(1.-7.18*EXP(-885./TEMP)))
  RCONST(55) = (2.*KCH3O2*RO2*0.5*(1.-7.18*EXP(-885./TEMP)))
  RCONST(56) = (4.0E-13*EXP(-845./TEMP))
  RCONST(57) = (J(J_CH3NO3))
  RCONST(58) = (5.3E-12*EXP(190./TEMP)*0.6)
  RCONST(59) = (5.3E-12*EXP(190./TEMP)*0.4)
  RCONST(60) = (J(J_CH3OOH))
  RCONST(61) = (J(J_C3H7CHO_HCO))
  RCONST(62) = (J(J_BIACET))
! RCONST(63) = constant rate coefficient
  RCONST(64) = (KNO3AL*5.5)
  RCONST(65) = (KAPNO)
  RCONST(66) = (KFPAN)
  RCONST(67) = (KBPAN)
  RCONST(68) = (KRO2NO3*1.74)
  RCONST(69) = (KAPHO2*0.56)
  RCONST(70) = (1.00E-11*RO2)
! RCONST(71) = constant rate coefficient
  RCONST(72) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(73) = constant rate coefficient
  RCONST(74) = (J(J_C3H7CHO_HCO)*2.)
! RCONST(75) = constant rate coefficient
  RCONST(76) = (2.*KNO3AL*2.4)
  RCONST(77) = (KAPNO)
  RCONST(78) = (KFPAN)
  RCONST(79) = (KBPAN)
  RCONST(80) = (KRO2NO3*1.74)
  RCONST(81) = (KAPHO2*0.41)
  RCONST(82) = (KAPHO2*0.15)
  RCONST(83) = (1.00E-11*0.7*RO2)
  RCONST(84) = (1.00E-11*0.3*RO2)
! RCONST(85) = constant rate coefficient
! RCONST(86) = constant rate coefficient
  RCONST(87) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(88) = constant rate coefficient
  RCONST(89) = (J(J_C3H7CHO_HCO))
  RCONST(90) = (KRO2NO)
  RCONST(91) = (KDEC)
  RCONST(92) = (KRO2NO3)
  RCONST(93) = (KRO2HO2*0.625)
  RCONST(94) = (2.00E-12*0.6*RO2)
  RCONST(95) = (2.00E-12*0.2*RO2)
  RCONST(96) = (2.00E-12*0.2*RO2)
! RCONST(97) = constant rate coefficient
  RCONST(98) = (1.90E-12*EXP(190./TEMP))
  RCONST(99) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(100) = constant rate coefficient
  RCONST(101) = (J(J_BIACET))
! RCONST(102) = constant rate coefficient
  RCONST(103) = (KNO3AL*4.0)
  RCONST(104) = (1.00E-11*0.800)
  RCONST(105) = (1.00E-11*0.200)
  RCONST(106) = (J(J_C3H7CHO_HCO))
  RCONST(107) = (KNO3AL)
  RCONST(108) = (KFPAN)
  RCONST(109) = (KBPAN)
  RCONST(110) = (KAPNO)
  RCONST(111) = (KRO2NO3*1.74)
  RCONST(112) = (KAPHO2*0.41)
  RCONST(113) = (KAPHO2*0.15)
  RCONST(114) = (1.00E-11*0.7*RO2)
  RCONST(115) = (1.00E-11*0.3*RO2)
! RCONST(116) = constant rate coefficient
  RCONST(117) = (J(J_CH3OOH))
! RCONST(118) = constant rate coefficient
  RCONST(119) = (1.6E-12*EXP(305./TEMP))
  RCONST(120) = (J(J_MEK))
  RCONST(121) = (3.8E-13*EXP(780./TEMP)*(1./(1.+498.*EXP(-1160./TEMP))))
  RCONST(122) = (1.36E-13*EXP(1250./TEMP)*0.15)
  RCONST(123) = (J(J_GLYOX_H2))
  RCONST(124) = (J(J_GLYOX_HCHO))
  RCONST(125) = (J(J_GLYOX_HCO))
  RCONST(126) = (3.1E-12*EXP(340./TEMP))
  RCONST(127) = (KNO3AL)
  RCONST(128) = (KAPNO)
  RCONST(129) = (J(J_MGLYOX))
  RCONST(130) = (1.9E-12*EXP(575./TEMP))
  RCONST(131) = (KNO3AL*2.4)
  RCONST(132) = (KFPAN)
  RCONST(133) = (KRO2NO3*1.74)
  RCONST(134) = (KAPHO2*0.41)
  RCONST(135) = (KAPHO2*0.15)
  RCONST(136) = (1.00E-11*0.7*RO2)
  RCONST(137) = (1.00E-11*0.3*RO2)
! RCONST(138) = constant rate coefficient
  RCONST(139) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(140) = constant rate coefficient
  RCONST(141) = (KRO2NO*0.983)
  RCONST(142) = (KRO2NO*0.017)
  RCONST(143) = (KDEC)
  RCONST(144) = (KRO2NO3)
  RCONST(145) = (KRO2HO2*0.625)
  RCONST(146) = (2.00E-12*0.6*RO2)
  RCONST(147) = (2.00E-12*0.2*RO2)
  RCONST(148) = (2.00E-12*0.2*RO2)
! RCONST(149) = constant rate coefficient
! RCONST(150) = constant rate coefficient
  RCONST(151) = (J(J_CH3OOH))
! RCONST(152) = constant rate coefficient
  RCONST(153) = (J(J_MEK))
  RCONST(154) = (J(J_C3H7CHO_HCO))
! RCONST(155) = constant rate coefficient
  RCONST(156) = (KNO3AL*4.0)
  RCONST(157) = (KAPNO)
  RCONST(158) = (KFPAN)
  RCONST(159) = (KBPAN)
  RCONST(160) = (KRO2NO3*1.74)
  RCONST(161) = (KAPHO2*0.56)
  RCONST(162) = (1.00E-11*RO2)
! RCONST(163) = constant rate coefficient
! RCONST(164) = constant rate coefficient
  RCONST(165) = (J(J_CH3OOH))
  RCONST(166) = (J(J_MEK))
  RCONST(167) = (5.4E-12*EXP(135./TEMP))
  RCONST(168) = (J(J_HCHO_H))
  RCONST(169) = (J(J_HCHO_H2))
! RCONST(170) = constant rate coefficient
  RCONST(171) = (7.5E-12*EXP(290./TEMP))
  RCONST(172) = (KFPAN)
  RCONST(173) = (KBPAN)
! RCONST(174) = constant rate coefficient
  RCONST(175) = (KAPHO2*0.41)
  RCONST(176) = (KAPHO2*0.15)
  RCONST(177) = (1.00E-11*0.7*RO2)
  RCONST(178) = (1.00E-11*0.3*RO2)
! RCONST(179) = constant rate coefficient
  RCONST(180) = (J(J_CH3OOH))
! RCONST(181) = constant rate coefficient
  RCONST(182) = (KRO2NO)
  RCONST(183) = (KDEC)
  RCONST(184) = (KRO2NO3)
  RCONST(185) = (KRO2HO2*0.387)
  RCONST(186) = (2.00E-12*0.6*RO2)
  RCONST(187) = (2.00E-12*0.2*RO2)
  RCONST(188) = (2.00E-12*0.2*RO2)
  RCONST(189) = (J(J_CH3OOH))
  RCONST(190) = (J(J_C3H7CHO_HCO))
  RCONST(191) = (1.90E-12*EXP(190./TEMP))
! RCONST(192) = constant rate coefficient
  RCONST(193) = (J(J_CH3COCH3))
  RCONST(194) = (8.8E-12*EXP(-1320./TEMP)+1.7E-14*EXP(423./TEMP))
  RCONST(195) = (KRO2NO)
  RCONST(196) = (KDEC)
  RCONST(197) = (KRO2NO3)
  RCONST(198) = (1.36E-13*EXP(1250./TEMP)*0.85)
  RCONST(199) = (2.*(K298CH3O2*8.0E-12)**(0.5)*RO2*0.6)
  RCONST(200) = (2.*(K298CH3O2*8.0E-12)**(0.5)*RO2*0.2)
  RCONST(201) = (2.*(K298CH3O2*8.0E-12)**(0.5)*RO2*0.2)
  RCONST(202) = (1.90E-12*EXP(190./TEMP))
! RCONST(203) = constant rate coefficient
  RCONST(204) = (J(J_CH3OOH))
  RCONST(205) = (J(J_MEK))
  RCONST(206) = (KAPNO)
  RCONST(207) = (KRO2NO)
  RCONST(208) = (KDEC)
  RCONST(209) = (KFPAN)
  RCONST(210) = (KBPAN)
  RCONST(211) = (KRO2NO3*1.74)
  RCONST(212) = (KAPHO2*0.56)
  RCONST(213) = (1.00E-11*RO2)
  RCONST(214) = (KRO2NO3)
  RCONST(215) = (KRO2HO2*0.625)
  RCONST(216) = (2.00E-12*RO2)
! RCONST(217) = constant rate coefficient
! RCONST(218) = constant rate coefficient
  RCONST(219) = (J(J_CH3OOH)+J(J_MEK)+J(J_C3H7CHO_HCO))
! RCONST(220) = constant rate coefficient
  RCONST(221) = (J(J_CH3OOH)+J(J_MEK)+J(J_C3H7CHO_HCO))
  RCONST(222) = (KAPNO)
  RCONST(223) = (KRO2NO)
  RCONST(224) = (KDEC)
  RCONST(225) = (KFPAN)
  RCONST(226) = (KBPAN)
  RCONST(227) = (KRO2NO3*1.74)
  RCONST(228) = (KAPHO2*0.56)
  RCONST(229) = (1.00E-11*RO2)
  RCONST(230) = (KRO2NO3)
  RCONST(231) = (KRO2HO2*0.520)
  RCONST(232) = (2.00E-12*RO2)
! RCONST(233) = constant rate coefficient
! RCONST(234) = constant rate coefficient
  RCONST(235) = (J(J_CH3OOH)+J(J_MGLYOX))
! RCONST(236) = constant rate coefficient
  RCONST(237) = (J(J_CH3OOH)+J(J_MGLYOX))
  RCONST(238) = (2.85E-12*EXP(-345./TEMP))
  RCONST(239) = (J(J_C3H7CHO_HCO))
  RCONST(240) = (J(J_MGLYOX))
! RCONST(241) = constant rate coefficient
  RCONST(242) = (2.*KNO3AL*4.0)
! RCONST(243) = constant rate coefficient
! RCONST(244) = constant rate coefficient
  RCONST(245) = (J(J_MGLYOX)+J(J_BIACET))
  RCONST(246) = (1.2E-11*EXP(440./TEMP)*0.572)
  RCONST(247) = (1.2E-11*EXP(440./TEMP)*0.353)
  RCONST(248) = (1.2E-11*EXP(440./TEMP)*0.075)
  RCONST(249) = (KRO2NO*0.770)
  RCONST(250) = (KRO2NO*0.230)
  RCONST(251) = (KDEC)
  RCONST(252) = (KRO2NO3)
  RCONST(253) = (KRO2HO2*0.914)
  RCONST(254) = (9.20E-14*RO2*0.7)
  RCONST(255) = (9.20E-14*RO2*0.3)
! RCONST(256) = constant rate coefficient
  RCONST(257) = (J(J_CH3OOH))
! RCONST(258) = constant rate coefficient
  RCONST(259) = (J(J_C3H7CHO_HCO))
  RCONST(260) = (5.2E-12*EXP(600./TEMP)*0.772)
  RCONST(261) = (5.2E-12*EXP(600./TEMP)*0.228)
! RCONST(262) = constant rate coefficient
  RCONST(263) = (KAPNO)
  RCONST(264) = (KRO2NO*0.843)
  RCONST(265) = (KRO2NO*0.157)
  RCONST(266) = (4.20E+10*EXP(-3523./TEMP))
  RCONST(267) = (KRO2NO)
  RCONST(268) = (KDEC)
  RCONST(269) = (KRO2NO*0.882)
  RCONST(270) = (KRO2NO*0.118)
  RCONST(271) = (KDEC)
  RCONST(272) = (KRO2NO*0.902)
  RCONST(273) = (KRO2NO*0.098)
  RCONST(274) = (KDEC)
  RCONST(275) = (KRO2NO*0.950)
  RCONST(276) = (KRO2NO*0.050)
  RCONST(277) = (KDEC)
  RCONST(278) = (KRO2NO*0.875)
  RCONST(279) = (KRO2NO*0.125)
  RCONST(280) = (KDEC)
  RCONST(281) = (KRO2NO)
  RCONST(282) = (KDEC)
  RCONST(283) = (KRO2NO3*1.74)
  RCONST(284) = (KFPAN)
  RCONST(285) = (KBPAN)
  RCONST(286) = (KAPHO2*0.41)
  RCONST(287) = (KAPHO2*0.15)
  RCONST(288) = (1.00E-11*0.7*RO2)
  RCONST(289) = (1.00E-11*0.3*RO2)
  RCONST(290) = (KRO2NO3)
  RCONST(291) = (KRO2HO2*0.890)
  RCONST(292) = (1.30E-12*0.6*RO2)
  RCONST(293) = (1.30E-12*0.2*RO2)
  RCONST(294) = (1.30E-12*0.2*RO2)
  RCONST(295) = (KRO2NO3)
  RCONST(296) = (KRO2HO2*0.890)
  RCONST(297) = (6.70E-15*0.7*RO2)
  RCONST(298) = (6.70E-15*0.3*RO2)
  RCONST(299) = (KRO2NO3)
  RCONST(300) = (KRO2HO2*0.890)
  RCONST(301) = (6.70E-15*0.7*RO2)
  RCONST(302) = (6.70E-15*0.3*RO2)
  RCONST(303) = (KRO2NO3)
  RCONST(304) = (KRO2HO2*0.770)
  RCONST(305) = (8.80E-13*0.6*RO2)
  RCONST(306) = (8.80E-13*0.2*RO2)
  RCONST(307) = (8.80E-13*0.2*RO2)
  RCONST(308) = (KRO2NO3)
  RCONST(309) = (KRO2HO2*0.914)
  RCONST(310) = (6.70E-15*0.7*RO2)
  RCONST(311) = (6.70E-15*0.3*RO2)
  RCONST(312) = (KRO2NO3)
  RCONST(313) = (KRO2HO2*0.914)
  RCONST(314) = (6.70E-15*0.7*RO2)
  RCONST(315) = (6.70E-15*0.3*RO2)
  RCONST(316) = (KRO2NO3)
  RCONST(317) = (KRO2HO2*0.820)
  RCONST(318) = (8.80E-13*0.6*RO2)
  RCONST(319) = (8.80E-13*0.2*RO2)
  RCONST(320) = (8.80E-13*0.2*RO2)
  RCONST(321) = (J(J_NC3H7NO3)+J(J_MEK))
! RCONST(322) = constant rate coefficient
  RCONST(323) = (J(J_TC4H9NO3)+J(J_BIACET))
! RCONST(324) = constant rate coefficient
  RCONST(325) = (J(J_BIACET))
! RCONST(326) = constant rate coefficient
  RCONST(327) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
! RCONST(328) = constant rate coefficient
  RCONST(329) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
! RCONST(330) = constant rate coefficient
! RCONST(331) = constant rate coefficient
  RCONST(332) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(333) = constant rate coefficient
  RCONST(334) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(335) = (1.90E-12*EXP(190./TEMP))
! RCONST(336) = constant rate coefficient
  RCONST(337) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(338) = constant rate coefficient
  RCONST(339) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(340) = constant rate coefficient
  RCONST(341) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(342) = constant rate coefficient
  RCONST(343) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(344) = constant rate coefficient
  RCONST(345) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(346) = constant rate coefficient
  RCONST(347) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(348) = constant rate coefficient
  RCONST(349) = (J(J_MEK))
! RCONST(350) = constant rate coefficient
  RCONST(351) = (J(J_MEK))
! RCONST(352) = constant rate coefficient
  RCONST(353) = (J(J_MEK))
! RCONST(354) = constant rate coefficient
  RCONST(355) = (J(J_BIACET))
! RCONST(356) = constant rate coefficient
  RCONST(357) = (J(J_BIACET))
! RCONST(358) = constant rate coefficient
  RCONST(359) = (J(J_MEK))
! RCONST(360) = constant rate coefficient
  RCONST(361) = (J(J_C3H7CHO_HCO))
! RCONST(362) = constant rate coefficient
  RCONST(363) = (J(J_C3H7CHO_HCO))
  RCONST(364) = (8.92E-11*0.232)
  RCONST(365) = (8.92E-11*0.768)
  RCONST(366) = (KNO3AL*5.5)
  RCONST(367) = (KAPNO)
  RCONST(368) = (KRO2NO)
  RCONST(369) = (KDEC)
  RCONST(370) = (KAPNO)
  RCONST(371) = (KRO2NO3*1.74)
  RCONST(372) = (KFPAN)
  RCONST(373) = (KBPAN)
  RCONST(374) = (KAPHO2*0.41)
  RCONST(375) = (KAPHO2*0.15)
  RCONST(376) = (1.00E-11*RO2*0.7)
  RCONST(377) = (1.00E-11*RO2*0.3)
! RCONST(378) = constant rate coefficient
  RCONST(379) = (J(J_CH3OOH)+J(J_MEK)*2.)
! RCONST(380) = constant rate coefficient
  RCONST(381) = (J(J_MEK)*2.)
! RCONST(382) = constant rate coefficient
  RCONST(383) = (J(J_CH3OOH)+J(J_MEK)*2.)
! RCONST(384) = constant rate coefficient
  RCONST(385) = (J(J_MEK)*2.)
  RCONST(386) = (2.54E-11*0.890)
  RCONST(387) = (2.54E-11*0.110)
  RCONST(388) = (J(J_MGLYOX))
! RCONST(389) = constant rate coefficient
! RCONST(390) = constant rate coefficient
  RCONST(391) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(392) = constant rate coefficient
  RCONST(393) = (J(J_MEK))
! RCONST(394) = constant rate coefficient
  RCONST(395) = (KRO2NO3*1.74)
  RCONST(396) = (KFPAN)
  RCONST(397) = (KBPAN)
  RCONST(398) = (KAPHO2*0.41)
  RCONST(399) = (KAPHO2*0.15)
  RCONST(400) = (1.00E-11*RO2*0.7)
  RCONST(401) = (1.00E-11*RO2*0.3)
  RCONST(402) = (KRO2NO3)
  RCONST(403) = (KRO2HO2*0.770)
  RCONST(404) = (2.00E-12*RO2*0.6)
  RCONST(405) = (2.00E-12*RO2*0.2)
  RCONST(406) = (2.00E-12*RO2*0.2)
  RCONST(407) = (J(J_C3H7CHO_HCO))
! RCONST(408) = constant rate coefficient
  RCONST(409) = (KNO3AL*8.5)
  RCONST(410) = (KAPNO)
  RCONST(411) = (KRO2NO)
  RCONST(412) = (KDEC)
  RCONST(413) = (KRO2NO)
  RCONST(414) = (KDEC)
  RCONST(415) = (KRO2NO)
  RCONST(416) = (KDEC)
  RCONST(417) = (J(J_MEK))
! RCONST(418) = constant rate coefficient
  RCONST(419) = (J(J_MGLYOX))
! RCONST(420) = constant rate coefficient
  RCONST(421) = (KNO3AL*5.5)
  RCONST(422) = (J(J_BIACET))
! RCONST(423) = constant rate coefficient
  RCONST(424) = (KNO3AL*5.5)
  RCONST(425) = (KAPNO)
  RCONST(426) = (KRO2NO)
  RCONST(427) = (KDEC)
  RCONST(428) = (KRO2NO3*1.74)
  RCONST(429) = (KFPAN)
  RCONST(430) = (KBPAN)
  RCONST(431) = (KAPHO2*0.56)
  RCONST(432) = (1.00E-11*RO2)
  RCONST(433) = (KRO2NO3)
  RCONST(434) = (KRO2HO2*0.859)
  RCONST(435) = (6.70E-15*RO2)
  RCONST(436) = (KRO2NO3)
  RCONST(437) = (KRO2HO2*0.859)
  RCONST(438) = (6.70E-15*RO2)
  RCONST(439) = (KRO2NO3)
  RCONST(440) = (KRO2HO2*0.706)
  RCONST(441) = (8.80E-13*RO2)
  RCONST(442) = (KRO2NO3*1.74)
  RCONST(443) = (KFPAN)
  RCONST(444) = (KBPAN)
  RCONST(445) = (KAPHO2*0.56)
  RCONST(446) = (1.00E-11*RO2)
  RCONST(447) = (KRO2NO3)
  RCONST(448) = (KRO2HO2*0.770)
  RCONST(449) = (2.00E-12*RO2)
! RCONST(450) = constant rate coefficient
  RCONST(451) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(452) = constant rate coefficient
  RCONST(453) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(454) = constant rate coefficient
  RCONST(455) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(456) = constant rate coefficient
  RCONST(457) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(458) = constant rate coefficient
! RCONST(459) = constant rate coefficient
  RCONST(460) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(461) = constant rate coefficient
  RCONST(462) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(463) = constant rate coefficient
  RCONST(464) = (J(J_C3H7CHO_HCO)*2.)
! RCONST(465) = constant rate coefficient
  RCONST(466) = (2.*KNO3AL*5.5)
  RCONST(467) = (KRO2NO*0.770)
  RCONST(468) = (KRO2NO*0.230)
  RCONST(469) = (KDEC)
  RCONST(470) = (KRO2NO3)
  RCONST(471) = (KRO2HO2*0.914)
  RCONST(472) = (8.80E-13*RO2*0.6)
  RCONST(473) = (8.80E-13*RO2*0.2)
  RCONST(474) = (8.80E-13*RO2*0.2)
! RCONST(475) = constant rate coefficient
  RCONST(476) = (J(J_CH3OOH))
! RCONST(477) = constant rate coefficient
! RCONST(478) = constant rate coefficient
! RCONST(479) = constant rate coefficient
  RCONST(480) = (1.2E-12*EXP(490./TEMP)*0.65)
  RCONST(481) = (1.2E-12*EXP(490./TEMP)*0.35)
  RCONST(482) = (KRO2NO)
  RCONST(483) = (KDEC)
  RCONST(484) = (KRO2NO3)
  RCONST(485) = (KRO2HO2*0.914)
  RCONST(486) = (6.70E-15*0.9*RO2)
  RCONST(487) = (6.70E-15*0.1*RO2)
  RCONST(488) = (J(J_CH3OOH))
! RCONST(489) = constant rate coefficient
  RCONST(490) = (KRO2NO)
! RCONST(491) = constant rate coefficient
  RCONST(492) = (KROSEC*O2)
  RCONST(493) = (KRO2NO3)
  RCONST(494) = (KRO2HO2*0.914)
  RCONST(495) = (2.50E-13*0.8*RO2)
  RCONST(496) = (2.50E-13*0.1*RO2)
  RCONST(497) = (2.50E-13*0.1*RO2)
  RCONST(498) = (J(J_CH3OOH))
  RCONST(499) = (1.90E-12*EXP(190./TEMP))
! RCONST(500) = constant rate coefficient
  RCONST(501) = (J(J_TC4H9NO3))
! RCONST(502) = constant rate coefficient
  RCONST(503) = (KRO2NO)
  RCONST(504) = (KDEC)
  RCONST(505) = (KRO2NO)
  RCONST(506) = (KDEC)
  RCONST(507) = (KRO2NO)
! RCONST(508) = constant rate coefficient
  RCONST(509) = (KROSEC*O2)
  RCONST(510) = (KRO2NO3)
  RCONST(511) = (KRO2HO2*0.914)
  RCONST(512) = (6.70E-15*RO2)
  RCONST(513) = (KRO2NO3)
  RCONST(514) = (KRO2HO2*0.914)
  RCONST(515) = (6.70E-15*RO2)
  RCONST(516) = (KRO2NO3)
  RCONST(517) = (KRO2HO2*0.820)
  RCONST(518) = (2.50E-13*RO2)
  RCONST(519) = (J(J_CH3OOH))
! RCONST(520) = constant rate coefficient
  RCONST(521) = (J(J_CH3OOH))
! RCONST(522) = constant rate coefficient
  RCONST(523) = (J(J_CH3OOH))
! RCONST(524) = constant rate coefficient
  RCONST(525) = (J(J_TC4H9NO3))
! RCONST(526) = constant rate coefficient
  RCONST(527) = (KRO2NO)
  RCONST(528) = (KDEC)
  RCONST(529) = (KAPNO)
  RCONST(530) = (KRO2NO3)
  RCONST(531) = (KRO2HO2*0.820)
  RCONST(532) = (8.80E-13*RO2)
  RCONST(533) = (KRO2NO3*1.74)
  RCONST(534) = (KFPAN)
  RCONST(535) = (KBPAN)
  RCONST(536) = (KAPHO2*0.56)
  RCONST(537) = (1.00E-11*RO2)
  RCONST(538) = (J(J_CH3OOH))
! RCONST(539) = constant rate coefficient
! RCONST(540) = constant rate coefficient
  RCONST(541) = (J(J_CH3OOH))
! RCONST(542) = constant rate coefficient
  RCONST(543) = (KRO2NO*0.875)
  RCONST(544) = (KRO2NO*0.125)
  RCONST(545) = (KDEC)
  RCONST(546) = (KRO2NO3)
  RCONST(547) = (KRO2HO2*0.914)
  RCONST(548) = (6.70E-15*RO2*0.7)
  RCONST(549) = (6.70E-15*RO2*0.3)
  RCONST(550) = (J(J_TC4H9NO3))
! RCONST(551) = constant rate coefficient
  RCONST(552) = (J(J_CH3OOH))
! RCONST(553) = constant rate coefficient
! RCONST(554) = constant rate coefficient
  RCONST(555) = (KRO2NO*0.722)
  RCONST(556) = (KRO2NO*0.278)
  RCONST(557) = (KROSEC*O2)
  RCONST(558) = (KRO2NO3)
  RCONST(559) = (KRO2HO2*0.820)
  RCONST(560) = (2.50E-13*RO2*0.6)
  RCONST(561) = (2.50E-13*RO2*0.2)
  RCONST(562) = (2.50E-13*RO2*0.2)
  RCONST(563) = (J(J_IC3H7NO3))
! RCONST(564) = constant rate coefficient
  RCONST(565) = (J(J_CH3OOH))
! RCONST(566) = constant rate coefficient
! RCONST(567) = constant rate coefficient
! RCONST(568) = constant rate coefficient
  RCONST(569) = (KRO2NO*0.958)
  RCONST(570) = (KRO2NO*0.042)
  RCONST(571) = (KDEC)
  RCONST(572) = (KRO2NO3)
  RCONST(573) = (KRO2HO2*0.820)
  RCONST(574) = (9.20E-14*RO2*0.7)
  RCONST(575) = (9.20E-14*RO2*0.3)
! RCONST(576) = constant rate coefficient
  RCONST(577) = (J(J_CH3OOH))
! RCONST(578) = constant rate coefficient
! RCONST(579) = constant rate coefficient
  RCONST(580) = (8.05E-16*EXP(-640./TEMP)*0.6)
  RCONST(581) = (8.05E-16*EXP(-640./TEMP)*0.4)
  RCONST(582) = (KDEC*0.55)
  RCONST(583) = (KDEC*0.45)
  RCONST(584) = (KRO2NO)
  RCONST(585) = (KDEC)
  RCONST(586) = (KRO2NO*0.875)
  RCONST(587) = (KRO2NO*0.125)
  RCONST(588) = (KDEC)
  RCONST(589) = (KRO2NO*0.722)
  RCONST(590) = (KRO2NO*0.278)
  RCONST(591) = (KROSEC*O2)
  RCONST(592) = (KRO2NO3)
  RCONST(593) = (KRO2HO2*0.914)
  RCONST(594) = (9.20E-14*0.7*RO2)
  RCONST(595) = (9.20E-14*0.3*RO2)
  RCONST(596) = (KRO2NO3)
  RCONST(597) = (KRO2HO2*0.914)
  RCONST(598) = (6.70E-15*0.7*RO2)
  RCONST(599) = (6.70E-15*0.3*RO2)
  RCONST(600) = (KRO2NO3)
  RCONST(601) = (KRO2HO2*0.820)
  RCONST(602) = (2.50E-13*0.6*RO2)
  RCONST(603) = (2.50E-13*0.2*RO2)
  RCONST(604) = (2.50E-13*0.2*RO2)
  RCONST(605) = (J(J_TC4H9NO3)+J(J_BIACET))
! RCONST(606) = constant rate coefficient
  RCONST(607) = (J(J_IC3H7NO3)+J(J_BIACET))
! RCONST(608) = constant rate coefficient
  RCONST(609) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(610) = constant rate coefficient
  RCONST(611) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(612) = constant rate coefficient
  RCONST(613) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(614) = constant rate coefficient
  RCONST(615) = (J(J_C3H7CHO_HCO))
! RCONST(616) = constant rate coefficient
  RCONST(617) = (J(J_BIACET))
! RCONST(618) = constant rate coefficient
  RCONST(619) = (J(J_BIACET))
! RCONST(620) = constant rate coefficient
  RCONST(621) = (KRO2NO)
  RCONST(622) = (KDEC*0.80)
  RCONST(623) = (KDEC*0.20)
  RCONST(624) = (KRO2NO3)
  RCONST(625) = (KRO2HO2*0.914)
  RCONST(626) = (2.00E-12*RO2*0.90)
  RCONST(627) = (2.00E-12*RO2*0.05)
  RCONST(628) = (2.00E-12*RO2*0.05)
  RCONST(629) = (KAPNO)
  RCONST(630) = (KRO2NO)
  RCONST(631) = (4.20E+10*EXP(-3523./TEMP))
  RCONST(632) = (KRO2NO)
  RCONST(633) = (KDEC)
  RCONST(634) = (KRO2NO)
  RCONST(635) = (KDEC)
  RCONST(636) = (KRO2NO)
  RCONST(637) = (KDEC)
  RCONST(638) = (J(J_BIACET))
  RCONST(639) = (J(J_C3H7CHO_HCO))
! RCONST(640) = constant rate coefficient
  RCONST(641) = (KNO3AL*5.5)
  RCONST(642) = (KAPNO)
  RCONST(643) = (KRO2NO)
  RCONST(644) = (KDEC)
  RCONST(645) = (KRO2NO3*1.74)
  RCONST(646) = (KFPAN)
  RCONST(647) = (KBPAN)
  RCONST(648) = (KAPHO2*0.56)
  RCONST(649) = (1.00E-11*RO2)
! RCONST(650) = constant rate coefficient
  RCONST(651) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(652) = constant rate coefficient
  RCONST(653) = (KRO2NO3)
  RCONST(654) = (KRO2HO2*0.625)
  RCONST(655) = (2.00E-12*RO2)
  RCONST(656) = (J(J_CH3OOH)+J(J_BIACET))
! RCONST(657) = constant rate coefficient
  RCONST(658) = (KRO2NO3*1.74)
  RCONST(659) = (KFPAN)
  RCONST(660) = (KBPAN)
  RCONST(661) = (KAPHO2*0.41)
  RCONST(662) = (KAPHO2*0.15)
  RCONST(663) = (1.00E-11*RO2*0.7)
  RCONST(664) = (1.00E-11*RO2*0.3)
  RCONST(665) = (KRO2NO3)
  RCONST(666) = (KRO2HO2*0.890)
  RCONST(667) = (1.30E-12*RO2)
  RCONST(668) = (KRO2NO3)
  RCONST(669) = (KRO2HO2*0.890)
  RCONST(670) = (6.70E-15*RO2)
  RCONST(671) = (KRO2NO3)
  RCONST(672) = (KRO2HO2*0.890)
  RCONST(673) = (6.70E-15*RO2)
  RCONST(674) = (KRO2NO3)
  RCONST(675) = (KRO2HO2*0.770)
  RCONST(676) = (8.80E-13*RO2)
  RCONST(677) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(678) = (J(J_MEK))
! RCONST(679) = constant rate coefficient
  RCONST(680) = (J(J_MEK))
  RCONST(681) = (J(J_C3H7CHO_HCO))
! RCONST(682) = constant rate coefficient
  RCONST(683) = (J(J_MGLYOX)+J(J_C3H7CHO_HCO))
! RCONST(684) = constant rate coefficient
! RCONST(685) = constant rate coefficient
  RCONST(686) = (J(J_MEK))
! RCONST(687) = constant rate coefficient
  RCONST(688) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(689) = constant rate coefficient
  RCONST(690) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(691) = constant rate coefficient
  RCONST(692) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(693) = constant rate coefficient
  RCONST(694) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(695) = constant rate coefficient
  RCONST(696) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(697) = constant rate coefficient
  RCONST(698) = (KDEC*0.50)
  RCONST(699) = (KDEC*0.50)
! RCONST(700) = constant rate coefficient
! RCONST(701) = constant rate coefficient
! RCONST(702) = constant rate coefficient
! RCONST(703) = constant rate coefficient
  RCONST(704) = (1.40E-17*H2O)
  RCONST(705) = (2.00E-18*H2O)
  RCONST(706) = (J(J_MGLYOX))
  RCONST(707) = (J(J_BIACET))
  RCONST(708) = (J(J_C3H7CHO_HCO)*2.)
! RCONST(709) = constant rate coefficient
  RCONST(710) = (J(J_MGLYOX))
! RCONST(711) = constant rate coefficient
  RCONST(712) = (KAPNO)
  RCONST(713) = (KRO2NO*0.896)
  RCONST(714) = (KRO2NO*0.104)
  RCONST(715) = (2.70E+14*EXP(-6643./TEMP))
  RCONST(716) = (KRO2NO*0.896)
  RCONST(717) = (KRO2NO*0.104)
  RCONST(718) = (2.70E+14*EXP(-6643./TEMP))
  RCONST(719) = (KRO2NO*0.871)
  RCONST(720) = (KRO2NO*0.129)
  RCONST(721) = (1.80E-14*EXP(-260./TEMP)*O2)
  RCONST(722) = (KRO2NO3*1.74)
  RCONST(723) = (KFPAN)
  RCONST(724) = (KBPAN)
  RCONST(725) = (KAPHO2*0.41)
  RCONST(726) = (KAPHO2*0.15)
  RCONST(727) = (1.00E-11*RO2*0.7)
  RCONST(728) = (1.00E-11*RO2*0.3)
  RCONST(729) = (KRO2NO3)
  RCONST(730) = (KRO2HO2*0.859)
  RCONST(731) = (6.70E-15*RO2*0.7)
  RCONST(732) = (6.70E-15*RO2*0.3)
  RCONST(733) = (KRO2NO3)
  RCONST(734) = (KRO2HO2*0.914)
  RCONST(735) = (6.70E-15*RO2*0.7)
  RCONST(736) = (6.70E-15*RO2*0.3)
  RCONST(737) = (KRO2NO3)
  RCONST(738) = (KRO2HO2*0.706)
  RCONST(739) = (2.50E-13*RO2*0.6)
  RCONST(740) = (2.50E-13*RO2*0.2)
  RCONST(741) = (2.50E-13*RO2*0.2)
! RCONST(742) = constant rate coefficient
  RCONST(743) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(744) = constant rate coefficient
  RCONST(745) = (J(J_C3H7CHO_HCO))
! RCONST(746) = constant rate coefficient
  RCONST(747) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
! RCONST(748) = constant rate coefficient
  RCONST(749) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(750) = constant rate coefficient
  RCONST(751) = (J(J_C3H7CHO_HCO))
! RCONST(752) = constant rate coefficient
  RCONST(753) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
! RCONST(754) = constant rate coefficient
  RCONST(755) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
! RCONST(756) = constant rate coefficient
  RCONST(757) = (J(J_C3H7CHO_HCO))
! RCONST(758) = constant rate coefficient
  RCONST(759) = (J(J_IC3H7NO3)+J(J_C3H7CHO_HCO)*2.)
! RCONST(760) = constant rate coefficient
  RCONST(761) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO)*2.)
! RCONST(762) = constant rate coefficient
  RCONST(763) = (J(J_C3H7CHO_HCO)*2.)
! RCONST(764) = constant rate coefficient
  RCONST(765) = (KDEC*0.20)
  RCONST(766) = (KDEC*0.80)
  RCONST(767) = (KAPNO)
  RCONST(768) = (KRO2NO*0.862)
  RCONST(769) = (KDEC)
  RCONST(770) = (KRO2NO)
  RCONST(771) = (KDEC)
  RCONST(772) = (KRO2NO*0.896)
  RCONST(773) = (KRO2NO*0.104)
  RCONST(774) = (KDEC)
  RCONST(775) = (KRO2NO3*1.74)
  RCONST(776) = (KAPHO2*0.41)
  RCONST(777) = (KAPHO2*0.15)
  RCONST(778) = (1.00E-11*RO2*0.7)
  RCONST(779) = (1.00E-11*RO2*0.3)
  RCONST(780) = (KFPAN)
  RCONST(781) = (KBPAN)
  RCONST(782) = (KRO2NO3)
  RCONST(783) = (KRO2HO2*0.859)
  RCONST(784) = (1.30E-12*RO2*0.6)
  RCONST(785) = (1.30E-12*RO2*0.2)
  RCONST(786) = (1.30E-12*RO2*0.2)
  RCONST(787) = (KRO2NO3)
  RCONST(788) = (KRO2HO2*0.859)
  RCONST(789) = (9.20E-14*RO2*0.7)
  RCONST(790) = (9.20E-14*RO2*0.3)
  RCONST(791) = (KRO2NO3)
  RCONST(792) = (KRO2HO2*0.859)
  RCONST(793) = (6.70E-15*RO2*0.7)
  RCONST(794) = (6.70E-15*RO2*0.3)
  RCONST(795) = (J(J_TC4H9NO3)+J(J_MGLYOX))
! RCONST(796) = constant rate coefficient
  RCONST(797) = (J(J_CH3OOH))
! RCONST(798) = constant rate coefficient
  RCONST(799) = (J(J_CH3OOH))
! RCONST(800) = constant rate coefficient
  RCONST(801) = (J(J_CH3OOH))
! RCONST(802) = constant rate coefficient
  RCONST(803) = (J(J_CH3OOH)+J(J_MGLYOX))
! RCONST(804) = constant rate coefficient
! RCONST(805) = constant rate coefficient
! RCONST(806) = constant rate coefficient
! RCONST(807) = constant rate coefficient
! RCONST(808) = constant rate coefficient
  RCONST(809) = (J(J_MGLYOX))
! RCONST(810) = constant rate coefficient
  RCONST(811) = (J(J_MGLYOX)+J(J_C3H7CHO_HCO))
! RCONST(812) = constant rate coefficient
  RCONST(813) = (J(J_C3H7CHO_HCO))
! RCONST(814) = constant rate coefficient
  RCONST(815) = (KNO3AL*8.5)
  RCONST(816) = (KAPNO)
  RCONST(817) = (KRO2NO)
  RCONST(818) = (KDEC)
  RCONST(819) = (KRO2NO)
  RCONST(820) = (KDEC)
  RCONST(821) = (KRO2NO)
  RCONST(822) = (KDEC)
  RCONST(823) = (KRO2NO3*1.74)
  RCONST(824) = (KFPAN)
  RCONST(825) = (KBPAN)
  RCONST(826) = (KAPHO2*0.41)
  RCONST(827) = (KAPHO2*0.15)
  RCONST(828) = (1.00E-11*RO2*0.7)
  RCONST(829) = (1.00E-11*RO2*0.3)
  RCONST(830) = (KRO2NO3)
  RCONST(831) = (KRO2HO2*0.820)
  RCONST(832) = (1.30E-12*RO2)
  RCONST(833) = (KRO2NO3)
  RCONST(834) = (KRO2HO2*0.820)
  RCONST(835) = (6.70E-15*RO2)
  RCONST(836) = (KRO2NO3)
  RCONST(837) = (KRO2HO2*0.625)
  RCONST(838) = (8.80E-13*RO2)
! RCONST(839) = constant rate coefficient
  RCONST(840) = (J(J_CH3OOH))
! RCONST(841) = constant rate coefficient
! RCONST(842) = constant rate coefficient
  RCONST(843) = (J(J_CH3OOH))
! RCONST(844) = constant rate coefficient
  RCONST(845) = (J(J_CH3OOH))
! RCONST(846) = constant rate coefficient
  RCONST(847) = (J(J_CH3OOH))
! RCONST(848) = constant rate coefficient
  RCONST(849) = (KRO2NO*0.138)
  RCONST(850) = (J(J_NC3H7NO3))
! RCONST(851) = constant rate coefficient
  RCONST(852) = (KAPHO2*0.44)
  RCONST(853) = (KAPHO2*0.44)
  RCONST(854) = (KAPHO2*0.44)
  RCONST(855) = (KAPHO2*0.44)
  RCONST(856) = (KAPHO2*0.44)
  RCONST(857) = (KAPHO2*0.44)
  RCONST(858) = (KAPHO2*0.44)
  RCONST(859) = (KAPHO2*0.44)
  RCONST(860) = (KAPHO2*0.44)
  RCONST(861) = (KAPHO2*0.44)
  RCONST(862) = (KAPHO2*0.44)
  RCONST(863) = (KAPHO2*0.44)
  RCONST(864) = (KAPHO2*0.44)
  RCONST(865) = (KAPHO2*0.44)
  RCONST(866) = (KAPHO2*0.44)
  RCONST(867) = (KAPHO2*0.44)
  RCONST(868) = (KAPHO2*0.44)
  RCONST(869) = (KAPHO2*0.44)
  RCONST(870) = (KAPHO2*0.44)
  RCONST(871) = (KRO2NO)
  RCONST(872) = (KRO2NO3)
  RCONST(873) = (KRO2HO2*0.706)
  RCONST(874) = (8.8E-13*RO2)
  RCONST(875) = (KDEC)
  RCONST(876) = (J(J_CH3OOH)+J(J_MEK))
! RCONST(877) = constant rate coefficient
  RCONST(878) = (7.00E11*EXP(-3160./TEMP)+5.00E-12*O2)
  RCONST(879) = (5.00E-12*O2*3.2*EXP(-550./TEMP))
  RCONST(880) = (5.00E-12*O2*3.2*(1.-EXP(-550./TEMP)))
  RCONST(881) = (J(J_NOA)*0.91)
  RCONST(882) = (RES1)

  RCONST = RCONST * R_F
END SUBROUTINE UPDATE_RCONST
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


! Begin inlined code from F90_RCONST_USE


  USE second_Constants

! End inlined code from F90_RCONST_USE


! Begin inlined code from F90_RCONST


  ! Peroxy radicals
  ! WARNING: The following species do not have SMILES strings in the database. 
  !           If any of these are peroxy radicals the RO2 sum will be wrong! 
  ! NA H2SO4
  RO2 = C(ind_CH3O2) + C(ind_BIACETO2) + C(ind_CH3CO3) + C(ind_HCOCH2CO3) + &
    C(ind_CO23C4CO3) + C(ind_HCOCH2O2) + C(ind_HOCH2CO3) + &
    C(ind_CH3COCH2O2) + C(ind_HCOCO3) + C(ind_HMVKAO2) + &
    C(ind_CO2H3CO3) + C(ind_CHOC3COCO3) + C(ind_CHOC3COO2) + &
    C(ind_C312COCO3) + C(ind_CHOCOCH2O2) + C(ind_APINAO2) + &
    C(ind_APINBO2) + C(ind_APINCO2) + C(ind_C96O2) + &
    C(ind_C96CO3) + C(ind_PINALO2) + C(ind_C97O2) + &
    C(ind_C98O2) + C(ind_C614O2) + C(ind_C106O2) + &
    C(ind_C716O2) + C(ind_H3C25C6O2) + C(ind_H3C25C6CO3) + &
    C(ind_H3C2C4CO3) + C(ind_C85O2) + C(ind_C85CO3) + &
    C(ind_C86O2) + C(ind_C511O2) + C(ind_CO235C6CO3) + &
    C(ind_CO235C6O2) + C(ind_NAPINAO2) + C(ind_NAPINBO2) + &
    C(ind_NC101O2) + C(ind_NC102O2) + C(ind_NC71O2) + &
    C(ind_NC72O2) + C(ind_NC61CO3) + C(ind_C720O2) + &
    C(ind_C719O2) + C(ind_C107O2) + C(ind_C109O2) + &
    C(ind_C108O2) + C(ind_C717O2) + C(ind_C89CO3) + &
    C(ind_C920CO3) + C(ind_C920O2) + C(ind_C921O2) + &
    C(ind_C922O2) + C(ind_C621O2) + C(ind_H1C23C4O2) + &
    C(ind_H1C23C4CO3) + C(ind_C89O2) + C(ind_C810O2) + &
    C(ind_C514O2) + C(ind_C811CO3) + C(ind_C811O2) + &
    C(ind_C812O2) + C(ind_C813O2) + C(ind_C516O2) + &
    C(ind_C721O2) + C(ind_C721CO3) + C(ind_C722O2) + &
    C(ind_C44O2)
  CALL define_constants_mcm

! End inlined code from F90_RCONST

  RCONST(36) = (J(J_O3_O1D))
  RCONST(37) = (J(J_O3_O3P))
  RCONST(38) = (J(J_H2O2))
  RCONST(39) = (J(J_NO2))
  RCONST(40) = (J(J_NO3_NO))
  RCONST(41) = (J(J_NO3_NO2))
  RCONST(42) = (J(J_HONO))
  RCONST(43) = (J(J_HNO3))
  RCONST(57) = (J(J_CH3NO3))
  RCONST(60) = (J(J_CH3OOH))
  RCONST(61) = (J(J_C3H7CHO_HCO))
  RCONST(62) = (J(J_BIACET))
  RCONST(72) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(74) = (J(J_C3H7CHO_HCO)*2.)
  RCONST(87) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(89) = (J(J_C3H7CHO_HCO))
  RCONST(99) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(101) = (J(J_BIACET))
  RCONST(106) = (J(J_C3H7CHO_HCO))
  RCONST(117) = (J(J_CH3OOH))
  RCONST(120) = (J(J_MEK))
  RCONST(123) = (J(J_GLYOX_H2))
  RCONST(124) = (J(J_GLYOX_HCHO))
  RCONST(125) = (J(J_GLYOX_HCO))
  RCONST(129) = (J(J_MGLYOX))
  RCONST(139) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(151) = (J(J_CH3OOH))
  RCONST(153) = (J(J_MEK))
  RCONST(154) = (J(J_C3H7CHO_HCO))
  RCONST(165) = (J(J_CH3OOH))
  RCONST(166) = (J(J_MEK))
  RCONST(168) = (J(J_HCHO_H))
  RCONST(169) = (J(J_HCHO_H2))
  RCONST(180) = (J(J_CH3OOH))
  RCONST(189) = (J(J_CH3OOH))
  RCONST(190) = (J(J_C3H7CHO_HCO))
  RCONST(193) = (J(J_CH3COCH3))
  RCONST(204) = (J(J_CH3OOH))
  RCONST(205) = (J(J_MEK))
  RCONST(219) = (J(J_CH3OOH)+J(J_MEK)+J(J_C3H7CHO_HCO))
  RCONST(221) = (J(J_CH3OOH)+J(J_MEK)+J(J_C3H7CHO_HCO))
  RCONST(235) = (J(J_CH3OOH)+J(J_MGLYOX))
  RCONST(237) = (J(J_CH3OOH)+J(J_MGLYOX))
  RCONST(239) = (J(J_C3H7CHO_HCO))
  RCONST(240) = (J(J_MGLYOX))
  RCONST(245) = (J(J_MGLYOX)+J(J_BIACET))
  RCONST(257) = (J(J_CH3OOH))
  RCONST(259) = (J(J_C3H7CHO_HCO))
  RCONST(321) = (J(J_NC3H7NO3)+J(J_MEK))
  RCONST(323) = (J(J_TC4H9NO3)+J(J_BIACET))
  RCONST(325) = (J(J_BIACET))
  RCONST(327) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
  RCONST(329) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
  RCONST(332) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(334) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(337) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(339) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(341) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(343) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(345) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(347) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(349) = (J(J_MEK))
  RCONST(351) = (J(J_MEK))
  RCONST(353) = (J(J_MEK))
  RCONST(355) = (J(J_BIACET))
  RCONST(357) = (J(J_BIACET))
  RCONST(359) = (J(J_MEK))
  RCONST(361) = (J(J_C3H7CHO_HCO))
  RCONST(363) = (J(J_C3H7CHO_HCO))
  RCONST(379) = (J(J_CH3OOH)+J(J_MEK)*2.)
  RCONST(381) = (J(J_MEK)*2.)
  RCONST(383) = (J(J_CH3OOH)+J(J_MEK)*2.)
  RCONST(385) = (J(J_MEK)*2.)
  RCONST(388) = (J(J_MGLYOX))
  RCONST(391) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(393) = (J(J_MEK))
  RCONST(407) = (J(J_C3H7CHO_HCO))
  RCONST(417) = (J(J_MEK))
  RCONST(419) = (J(J_MGLYOX))
  RCONST(422) = (J(J_BIACET))
  RCONST(451) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(453) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(455) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(457) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(460) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(462) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(464) = (J(J_C3H7CHO_HCO)*2.)
  RCONST(476) = (J(J_CH3OOH))
  RCONST(488) = (J(J_CH3OOH))
  RCONST(498) = (J(J_CH3OOH))
  RCONST(501) = (J(J_TC4H9NO3))
  RCONST(519) = (J(J_CH3OOH))
  RCONST(521) = (J(J_CH3OOH))
  RCONST(523) = (J(J_CH3OOH))
  RCONST(525) = (J(J_TC4H9NO3))
  RCONST(538) = (J(J_CH3OOH))
  RCONST(541) = (J(J_CH3OOH))
  RCONST(550) = (J(J_TC4H9NO3))
  RCONST(552) = (J(J_CH3OOH))
  RCONST(563) = (J(J_IC3H7NO3))
  RCONST(565) = (J(J_CH3OOH))
  RCONST(577) = (J(J_CH3OOH))
  RCONST(605) = (J(J_TC4H9NO3)+J(J_BIACET))
  RCONST(607) = (J(J_IC3H7NO3)+J(J_BIACET))
  RCONST(609) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(611) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(613) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(615) = (J(J_C3H7CHO_HCO))
  RCONST(617) = (J(J_BIACET))
  RCONST(619) = (J(J_BIACET))
  RCONST(638) = (J(J_BIACET))
  RCONST(639) = (J(J_C3H7CHO_HCO))
  RCONST(651) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(656) = (J(J_CH3OOH)+J(J_BIACET))
  RCONST(677) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(678) = (J(J_MEK))
  RCONST(680) = (J(J_MEK))
  RCONST(681) = (J(J_C3H7CHO_HCO))
  RCONST(683) = (J(J_MGLYOX)+J(J_C3H7CHO_HCO))
  RCONST(686) = (J(J_MEK))
  RCONST(688) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(690) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(692) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(694) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(696) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(706) = (J(J_MGLYOX))
  RCONST(707) = (J(J_BIACET))
  RCONST(708) = (J(J_C3H7CHO_HCO)*2.)
  RCONST(710) = (J(J_MGLYOX))
  RCONST(743) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(745) = (J(J_C3H7CHO_HCO))
  RCONST(747) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
  RCONST(749) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(751) = (J(J_C3H7CHO_HCO))
  RCONST(753) = (J(J_TC4H9NO3)+J(J_C3H7CHO_HCO))
  RCONST(755) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO))
  RCONST(757) = (J(J_C3H7CHO_HCO))
  RCONST(759) = (J(J_IC3H7NO3)+J(J_C3H7CHO_HCO)*2.)
  RCONST(761) = (J(J_CH3OOH)+J(J_C3H7CHO_HCO)*2.)
  RCONST(763) = (J(J_C3H7CHO_HCO)*2.)
  RCONST(795) = (J(J_TC4H9NO3)+J(J_MGLYOX))
  RCONST(797) = (J(J_CH3OOH))
  RCONST(799) = (J(J_CH3OOH))
  RCONST(801) = (J(J_CH3OOH))
  RCONST(803) = (J(J_CH3OOH)+J(J_MGLYOX))
  RCONST(809) = (J(J_MGLYOX))
  RCONST(811) = (J(J_MGLYOX)+J(J_C3H7CHO_HCO))
  RCONST(813) = (J(J_C3H7CHO_HCO))
  RCONST(840) = (J(J_CH3OOH))
  RCONST(843) = (J(J_CH3OOH))
  RCONST(845) = (J(J_CH3OOH))
  RCONST(847) = (J(J_CH3OOH))
  RCONST(850) = (J(J_NC3H7NO3))
  RCONST(876) = (J(J_CH3OOH)+J(J_MEK))
  RCONST(881) = (J(J_NOA)*0.91)
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE second_Rates

